### ISSUE TITLE
Incompatibility due to targeting Android 13 "Tiramisu" as the target

### ISSUE THREAD

**Issue by Titokhan** [chenxiaolong/BCR#1]
Device: Redmi 5, Redmi Note 4
Android: 11, 12 (unofficial LineageOS builds)

After flashing the Magisk module, the application can't be found inside the app drawer. You can locate the APK under `system/priv-app`, but it's not functioning.

Curiously, if you manually try to sideload the APK using ADB, you'll get the following error:
```
adb: failed to install app-release.apk: Failure [INSTALL_FAILED_OLDER_SDK: Failed parse during installPackageLI: /data/app/vmdl822031778.tmp/base.apk (at Binary XML file line #7): Requires development platform Tiramisu but this is a release platform.]
```

I can see that `android:compileSdkVersion` is "32" and `android:compileSdkVersionCodename` is "Tiramisu" after decompiling the APK.

===

Device: Google Pixel 4a
Android: 13 Beta 2

If you manually try to sideload the APK using ADB, you'll get the following error:
```
adb: failed to install app-release.apk: Failure [INSTALL_FAILED_TEST_ONLY: installPackageLI]
```

I can only sideload it under Android 13 using the `-t` parameter (allow test packages).

The Pixel 4a's bootloader is locked, so I can't test the Magisk module yet. Will do so after backing up data from the device.

===

Android app development isn't my forte, but I think targeting Tiramisu is the primary issue here.

**Comment by chenxiaolong** [comment]
Interesting, I didn't know targeting Tiramisu would break installation on older Android versions. I should have tested that in an emulator. I'll change it to target and compile with SDK 32.
