### ISSUE TITLE
White screen on OnePlus 9 Pro

### ISSUE THREAD

**Issue by spongioblast** [chenxiaolong/BCR#100]
Hi there

I simply get a white screen when starting the app. I can kill it and start it again, however it just results in the same white screen. 

Phone: OnePlus 9 Pro
BCR 1.15
Magisk 25.1
Android 12
Firmware Stock LE21231_11.C.48

Any way I can help with debugging?

I seems to be the same issue mentioned in #8 but even with only the bcr module, no deny list and no zygisk I still get the white screen.

Maybe it has to do with the OnePlus Multi User Features or Parallel Apps space?

Interesting is that in the folder /data/user/0/com.chiller.3.bcr exists with two empty folders cache and code cache, but no folder com.chiller.3.bcr does not exist in /data/user_de/0/

Thanks

**Comment by chenxiaolong** [comment]
Yeah, this is a weird issue. I'm not sure how to troubleshoot it. When BCR is launched, Android does not even begin to execute BCR's code, causing it to sit at a blank screen.

> Maybe it has to do with the OnePlus Multi User Features or Parallel Apps space?
>
> Interesting is that in the folder /data/user/0/com.chiller.3.bcr exists with two empty folders cache and code cache, but no folder com.chiller.3.bcr does not exist in /data/user_de/0/

I'm not familiar with with how the multi-user or parallel apps are implemented, but it seems possible.

Can you try:

* removing BCR completely and rebooting
* install BCR, but don't reboot
* extract BCR's apk from the zip and install that normally
* reboot

and see if that causes `/data/user_de/0/com.chiller3.bcr` to be created?

**Comment by spongioblast** [comment]
Thanks, installing the app this way plus reboot at the end, works flawlessly and the app works and recards fine.

A new folder was created in /data/user/0/com.chiller.3.bcr with shared_prefs, the folder /data/user_de/0/com.chiller.3.bcr now also exists with empty cache folder and two files in code_cache called com.android.opengl.shaders_cache and com.android.skia.shaders_cache

**Comment by chenxiaolong** [comment]
Great! Glad to hear it's working now.

I've added documentation for this workaround in the README.
