### ISSUE TITLE
How can I create a Magisc .zip file from source code?

### ISSUE THREAD

**Issue by fahime-ghasemi** [chenxiaolong/BCR#102]
Hello
I've cloned this repo and added some features to the app. Now I'm gonna create a Magisc .zip file. I don't know how I can do that. Could anybody help me?
Thanks

**Comment by chenxiaolong** [comment]
Hello, please see the building from source section in the README. It lists the command for building the Magisk module zip. https://github.com/chenxiaolong/BCR#building-from-source
