### ISSUE TITLE
It does not record. Realme 7 Pro, custom rom

### ISSUE THREAD

**Issue by J4CKED** [chenxiaolong/BCR#104]
Hello, I installed the latest version 1.15 in Magisk. 
After rebooting, I enabled recording, gave permissions.
After making a call, the call file is not created. The application does not record.

Realme 7 Pro
Android 12, custom rom RiceDroid Version 2.5 vanilla

So far I have used Axets Call Recorder, but it did not always record.
Below is a logcat file of a call attempt.

EDIT

**Comment by J4CKED** [comment]
After reading other threads, I learned that the app does not record calls to non-existent numbers.

When I call a number, for example "*821" and a machine reports the wrong number, the application does not respond.
But when I call the real number then the application works. Hurray

**Comment by chenxiaolong** [comment]
> When I call a number, for example "*821" and a machine reports the wrong number, the application does not respond.
But when I call the real number then the application works. Hurray

Glad you got it working! Yeah, with the special/different way BCR detects calls, it will only trigger if a call successfully connects.
