### ISSUE TITLE
Create a call recorder that doesn't need to be a system app

### ISSUE THREAD

**Issue by fahime-ghasemi** [chenxiaolong/BCR#105]
Hi
I want to change this repo to create a call recorder that doesn't need to be a system app. Could you please give me some advice?
First of all I tried to change creating instance of AudioRecord. One time I tried using MediaRecorder.AudioSource.VOICE_COMMUNICATION and another time I tried using MediaRecorder.AudioSource.VOICE_RECOGNITION but none of them worked. 
It just created a file but when I play it doesn't contain any sound. 
I know that you have good knowledge about creating call recorder apps. My device is rooted and my requirement is to create a call recorder app that doesn't need to be a system app. It would be thankful if you give some advice and help me to proceed and find a way. 

Thanks in advance

**Comment by chenxiaolong** [comment]
Hello!

>  I want to change this repo to create a call recorder that doesn't need to be a system app.

This is not possible on modern versions of Android. You can only receive call audio through the `VOICE_CALL` stream or possibly the `VOICE_DOWNLINK`/`VOICE_UPLINK` streams, but all three of those require system app privileges.

I don't know if recording as root is possible (eg. via a native executable that uses the NDK AudioRecord APIs). You'll likely have to dig through the AOSP source code to determine if it has an exemption in the permission system for UID 0. I'm guessing it most likely won't.

**Comment by fahime-ghasemi** [comment]
Thanks for the response. According to my researches some apps have used Accessibility API to implement call recording feature. Do you know about it?

**Comment by chenxiaolong** [comment]
I don't believe that works in recent versions of Android anymore (and on older versions, I think it only records via the microphone instead of the actual call audio stream).

**Comment by fahime-ghasemi** [comment]
Yes, you're right. The apps that don't use call audio stream use microphone to record calls. 
I'm currently thinking about how I can get those system permissions using having root access. I want to find a way to not have to install this app using Magisk module. I'm looking for a way to install this app using .apk file on rooted device and get those required system permission using root access. I don't know if it's possible or not. I would be thankful if you share your ideas about it.

**Comment by fahime-ghasemi** [comment]
According to my researches, it seems if the app has root access that CAPTURE_AUDIO_OUTPUT permission isn't required. I'm searching to find a way so that grant root access in app startup to test it.

**Comment by RaingodSpires** [comment]
I past last days struggling on my phone to root it. Finally I got it and I'm deeply grateful with the creator, because the app it works perfectly and this is a won battle vs google and its restrictions. In my country for example is completely legal to record without advise if the recorder has participation in the talk. And in any case, is very useful if you want to remember information of work, complex, etc.

Regards and a greeting
