### ISSUE TITLE
Can the oga and m4a filename extensions be changed to ogg and aac? 

### ISSUE THREAD

**Issue by effectively0** [chenxiaolong/BCR#109]
They are more common file extensions. The problem is that my Android file Explorer does not recognise oga as an audio file and suggest suitable media players. Also other apps do not detect them as audio when scanning folders, which is important as BCR itself not offer a UI to view and playback recordings.

**Comment by chenxiaolong** [comment]
Hmm, I'll have to see if this is possible with Android's SAF (storage access framework). The way it works right now is that BCR requests the creation of a new file and it specifies the file type as `audio/mp4`, `audio/flac`, `audio/ogg`, or `audio/x-wav`, depending on which output format is chosen. Android itself is using that to determine which file extension to use.

**Comment by PatrykMis** [comment]
@effectively0  oga is not the same as ogg, aac is not the same as m4a. m4a is an aac stream contained in MP4 container.

**Comment by invisible789** [comment]
@chenxiaolong 
Thank you for this awesome recorder
Yes oga is not a common format, instead OPUS and ogg are way too common
Moreover OPUS produces better quality in comparison to ogg
Please look for OPUS format if possible, hopefully it's a least burdon on CPU as well
Looking forward to your future releases, Thank you

**Comment by PatrykMis** [comment]
Once again: .ogg and/or .oga are file extensions for OGG container. The OGG container can "hold" formats like Vorbis, Speex, OPUS or even FLAC (!).
More on this: <https://en.wikipedia.org/wiki/Ogg>

Fformat and container are completely different things.

**Comment by invisible789** [comment]
> Once again: .ogg and/or .oga are file extensions for OGG container. The OGG container can "hold" formats like Vorbis, Speex, OPUS or even FLAC (!). More on this: https://en.wikipedia.org/wiki/Ogg
> 
> Fformat and container are completely different things.
> 
> Edit: Similarely, .m4a is only extension for MPEG-4 container. The letter `a` indicates that specific file contains only audio stream. M4A can contain AAC stream or even proprietary ALAC (Apple Lossless Audio Codec).

![Screenshot_20230809-025014_DroidX-UI Launcher](https://github.com/chenxiaolong/BCR/assets/72073975/5ff565fd-2251-4ca7-ab26-5f57d94adc46)

**Comment by invisible789** [comment]
> Once again: .ogg and/or .oga are file extensions for OGG container. The OGG container can "hold" formats like Vorbis, Speex, OPUS or even FLAC (!). More on this: https://en.wikipedia.org/wiki/Ogg
> 
> Fformat and container are completely different things.
> 
> Edit: Similarely, .m4a is only extension for MPEG-4 container. The letter `a` indicates that specific file contains only audio stream. M4A can contain AAC stream or even proprietary ALAC (Apple Lossless Audio Codec).

Yes, that's the point, going for certain fFormat instead of container, for wider compatibility & sharing aspect , choose common formats is important

**Comment by PatrykMis** [comment]
@chenxiaolong to save audio in `.opus` file, we should define `audio/opus` mimetype then. I am not sure if it is natively supported by Android as MediaMuxer API does not contain it: instead, new OpusContainer should be defined which requires additional work.

**Comment by PatrykMis** [comment]
@invisible789 recordings saved using OPUS format that are in .ogg container (.ogg or .oga) are easyly convertable. The audio stream is then untouched because you are changing only container (so you are avoiding transcoding/quality loss). For Windows, if you have FFmpeg installed you can do it with following command:

<code>
ffmpeg -i inputfilename.oga -c copy outputfilename.opus
</code>

**Comment by invisible789** [comment]
> @chenxiaolong, if I understand correctly, to save OPUS audio in a `.opus` file, we should define the `audio/opus` MIME type as per the https://wiki.xiph.org/MIME_Types_and_File_Extensions. I'm not sure if this is natively supported by Android, as the [MediaMuxer](https://developer.android.com/reference/android/media/MediaMuxer) API does not include it. Instead, a new OpusContainer would need to be created, which would require additional work.

Opus is natively supported, see link

https://developer.android.com/guide/topics/media/platform/supported-formats#audio-formats

Whereas OGA is not

Point is not to change format, but having native compatibility, thanks for sharing insight :)

**Comment by PatrykMis** [comment]
@invisible789 You're right, Opus is indeed natively supported as shown [here](https://developer.android.com/guide/topics/media/platform/supported-formats#audio-formats), and FLAC is supported as well. However, the key point is the container handling. While muxing OPUS to an OGG container is easily accomplished through MediaMuxer, creating a proper .opus file requires manual container management, such as updating the duration of the recording. This makes the process more complex and differs from merely utilizing native compatibility. Thank you for bringing this up; I hope this clears up any confusion!

**Comment by PatrykMis** [comment]
@invisible789 My apologies for any confusion earlier. Upon further investigation, I've discovered that the container for .oga, .ogg and .opus files are indeed the same, and the difference is only in the file extension.

**Comment by invisible789** [comment]
> @invisible789 My apologies for any confusion earlier. Upon further investigation, I've discovered that the container for .oga, .ogg and .opus files are indeed the same, and the difference is only in the file extension. When it comes to AAC files, there is a distinction. .M4A files typically contain audio only and are formatted as MPEG-4 Part 14 files, using the .MP4 container, allowing them to include metadata and other information. .AAC, on the other hand, can represent raw AAC audio streams or AAC audio encapsulated using the Audio Data Transport Stream (ADTS).

So implementing OPUS instead of oga is just extension difference, awesome
I think this needs attention of @chenxiaolong

**Comment by chenxiaolong** [comment]
The extension is determined by Android's Storage Access Framework. BCR asks SAF to create a file of type `audio/ogg` and Android picks the `.oga` extension because it's the first option in Android's code: https://cs.android.com/android/platform/superproject/main/+/main:external/mime-support/mime.types;drc=26128456882d662cef0a6015558cc0adca33aa14;l=542

Android's SAF is a horrible API. The only way to force a specific file extension is by lying to Android about the file type and pretending the file is an unsupported type (which is how file managers do it). I don't plan on implementing that sort of workaround in BCR.

**Comment by PatrykMis** [comment]
@chenxiaolong I agree. .oga is closer to the standard. As in [Wikipedia Article](https://en.wikipedia.org/wiki/Ogg), OGG can contain audio and videostreams. It's similar to .mp4 vs. .m4a. While .mp4 is more generic extension, .m4a is dedicated for MPEG-4 containing audio streams only. The same is with .ogg vs. .oga.

**Comment by newbit1** [comment]
I just use the tool
https://play.google.com/store/apps/details?id=co.m16mb.secco.renamemyfiles

To rename the files in the recording dir.

Thanks for the awesome tool btw.
