### ISSUE TITLE
Unable to create new Folder

### ISSUE THREAD

**Issue by DrErhan** [chenxiaolong/BCR#118]
Hello. Thank you very much for your successful project. The problem is : It saves successfully after selecting folder for recording in local storage. However, after performing cloud synchronization with third-party applications, the local folder can be deleted.When the local folder is deleted, the BCR cannot create the local folder again, so it does not record. I have to recreate the local folder each time. Can this situation be resolved? Thank you and have nice work.

**Comment by chenxiaolong** [comment]
Hmm, is it possible for the cloud sync to only delete the contents, but not the folder itself?

It is not possible for BCR to recreate the folder due to limitations with Android's SAF (storage access framework). BCR has access to the contents of the selected folder only.
