### ISSUE TITLE
Unable to retrieve AudioRecord pointer

### ISSUE THREAD

**Issue by dj-tanjid** [chenxiaolong/BCR#119]
I am getting this notification while call starts,
"Unable to retrieve AudioRecord pointer for frameCount()"

Any way to fix this?
![Screenshot_20220811-013631_Chrome](https://user-images.githubusercontent.com/17379866/184005336-25668171-a970-4c40-a0e2-ffc53cd28338.png)

**Comment by chenxiaolong** [comment]
Unfortunately, when you get that error, it means your device (or maybe just your ROM) doesn't support the call audio device, which is required for call recording.

**Comment by dj-tanjid** [comment]
> Unfortunately, when you get that error, it means your device (or maybe just your ROM) doesn't support the call audio device, which is required for call recording.

Any way to add support like via any module or some file or permissions?

**Comment by chenxiaolong** [comment]
You might have to ask the developer of your ROM about that. I'm not too familiar with what's required at the ROM and firmware level for supporting call recording.
