### ISSUE TITLE
BCR going to Support VoIP Call Recording - Record calls from WhatsApp, Viber, Skype etc

### ISSUE THREAD

**Issue by hamzaharoon1314** [chenxiaolong/BCR#123]
Is BCR going to support any other chatting apps call recording like telegram WeChat and WhatsApp

**Comment by chenxiaolong** [comment]
Nope, sorry. BCR is heavily tied into Android's phone call systems and is only designed for that. It should be fine to run another call recorder app that supports VOIP at the same time though.
