### ISSUE TITLE
Call Recording Not Working on Root

### ISSUE THREAD

**Issue by rahulbhatia101** [chenxiaolong/BCR#126]
I am unable to record calls through BCR 1.8. During a call, it does record, I get a notification of it, but when I go to the actual file and listen to it, it is blank, theres no voice of either party, and the recorded length is just 3-5 seconds, regardless of my call length.

Using BCR 1.8, flashed through Magisk. I am using Redmi Note 10 pro Max (108mp) on Corvus OS 12.1.

All the screenshots I think are necessary are attached, kindly guide what I am missing here

![Screenshot_20220829-083443_Settings](https://user-images.githubusercontent.com/84509359/187115360-60a650b8-6e47-4950-a9c5-3ebbd0f0cb47.png)
![Screenshot_20220829-083348_Settings](https://user-images.githubusercontent.com/84509359/187115367-6bfd0a42-0f56-4010-924d-fb42eb98685f.png)
![Screenshot_20220829-083309_Permission controller](https://user-images.githubusercontent.com/84509359/187115369-19334982-80b3-48a6-910e-12798a8c8e9a.png)
![Screenshot_20220829-083242_Settings](https://user-images.githubusercontent.com/84509359/187115370-33f49d41-1a46-4396-aa43-1bc1d1d68387.png)
![Screenshot_20220829-083229_BCR](https://user-images.githubusercontent.com/84509359/187115371-1df9fd9d-3ab8-4bbd-a9e9-f315afe6f7be.png)

**Comment by chenxiaolong** [comment]
Can you enable debug mode (long press the version number), try to make a call, and then upload the log file it creates in the output directory?

**Comment by rahulbhatia101** [comment]
[20220902_172910.43+0530_out_121.log.txt](https://github.com/chenxiaolong/BCR/files/9477709/20220902_172910.43%2B0530_out_121.log.txt)


This is a call to 121 ( My Mobile Service Provider helpline, not to my contact, but this error happens to all my recorded files )

I hope this helps!

**Comment by chenxiaolong** [comment]
Thanks for the logs! Was that call longer than ~4.2 seconds?

If so, it might be a bug in the ROM you're using. It stopped recording after 4.2 seconds because Android is reporting that the phone call is in the `DISCONNECTING` state.

**Comment by rahulbhatia101** [comment]
Yes, the call was more than 4 seconds.

If you suspect this is a ROM problem, then I guess we are on the same page, because that was my first thought 😅.

Will try another rom, and will update you.

**Comment by rahulbhatia101** [comment]
So our thought was right, flashed a different rom, and the recording works fine! thanks, you can consider this issue closed
