### ISSUE TITLE
stereo recording

### ISSUE THREAD

**Issue by joebloe0** [chenxiaolong/BCR#127]
would there be a way to have a stereo recording. such that the caller is on the left audio channel and I'm on the right audio channel.
it would help to differentiate what people are saying if they're talking over each other a little

**Comment by chenxiaolong** [comment]
Unfortunately not. I tried implementing that, but Android's audio driver for call recording doesn't support it. Please see: https://github.com/chenxiaolong/BCR/issues/124

**Comment by chenxiaolong** [comment]
With #772, which will be included in version 2.0, BCR can now optionally record in stereo for devices that support it. The uplink is recorded to the left channel and the downlink to the right channel. Currently, only newer Google Pixel devices are known to support this.
