### ISSUE TITLE
Can u make a recovery install?

### ISSUE THREAD

**Issue by laltroweb** [chenxiaolong/BCR#128]
I root just for this atm.
With a simple recovery install (adb sideload install, like many Gapps packages).
Can be no more necessary to root 😅👍

**Comment by chenxiaolong** [comment]
That's a great idea. I implemented this in #130. Starting with version 1.19, it'll be possible to flash the BCR zip in recovery.

**Comment by laltroweb** [comment]
So good. Ty 😃
