### ISSUE TITLE
Not able to install via custom recovery 

### ISSUE THREAD

**Issue by errwnd** [chenxiaolong/BCR#131]
Ofox recovery; Derpfest rom 12L. Flashing the zip is not working.

**Comment by chenxiaolong** [comment]
Please grab the recovery log with `adb pull /tmp/recovery.log` after attempting to flash the zip and upload it here.

**Comment by errwnd** [comment]
Installing ZIP file '/sdcard/Download/BCR-1.19-release.zip'
Unmounting Super...
I:Unmounting main partitions...
I:Update binary zip
I:Extracting updater binary 'META-INF/com/google/android/update-binary'
Detecting Current Package
I:Zip does not contain SELinux file_contexts file in its root.
/tmp/updater: line 37: /data/adb/magisk/util_functions.sh: No such file or directory
/tmp/updater: line 39: install_module: command not found
Updater process ended with ERROR: 127
I:OrangeFox: installed standard zip: /sdcard/Download/BCR-1.19-release.zip
I:flash_zip: installer code = 0
Error installing ZIP file '/sdcard/Download/BCR-1.19-release.zip'
Updating partition details...
I:Data backup size is 7780MB, free: 83242MB.
I:Can't probe device /data/media/0
...done
I:Set page: 'flash_done'
I:operation_end - status=1

**Comment by chenxiaolong** [comment]
Thanks for the logs! Can you post a link to the custom recovery you're using?

Right now, BCR checks if `/sbin/recovery` exists to determine whether to do a direct install or a Magisk install. It seems that your custom recovery doesn't have `/sbin/recovery`, so it's incorrectly trying to install as a Magisk module.

**Comment by errwnd** [comment]
Hi , here is the link to the chat in telegram
https://t.me/realme7ProOfficial/503587 
And here is the link from the post 
https://drive.google.com/drive/folders/12sWsNYlBKGrY3Txf82zO9hBjjXAJv_HX?usp=sharing

**Comment by chenxiaolong** [comment]
Thanks for the links. Looks like that recovery image uses `/system/bin/recovery`.

Can you give this debug build a try? 
[BCR-1.19.r5.gf122fcf-debug.zip](https://github.com/chenxiaolong/BCR/files/9509405/BCR-1.19.r5.gf122fcf-debug.zip)

**Comment by errwnd** [comment]
Hello, Thanks for the build. This one works perfectly. 😁

**Comment by chenxiaolong** [comment]
Great! I'll release version 1.20 tomorrow with the fix.
