### ISSUE TITLE
Firmware bug on Realme device

### ISSUE THREAD

**Issue by AVAtarMod** [chenxiaolong/BCR#134]
Device model: Realme C25S
Firmware: RMX3195_11_A.20 (stock, Android 11)

Classic installation method (Magisk only) not work.
Solution: 
1. Disable module (if enabled).
2. Reboot device.
3. Manually install .apk package from module archive.
4. Enable module in Magisk.
5. Reboot

Please add info to README.md

**Comment by chenxiaolong** [comment]
Thanks for the info. So it looks like it's the same firmware bug as OnePlus. I've updated the README.

**Comment by HemanthJabalpuri** [comment]
Thanks for the solution. I can also confirm this happens in my Realme C12 running on Realme UI 2.0(Android 11). Everything is fine in Realme UI 1.0(Android 10)
