### ISSUE TITLE
Voice recording issue

### ISSUE THREAD

**Issue by Imnotgonnacode** [chenxiaolong/BCR#136]
Sometimes recording voice sounds as a robotic some sort of distorted voice

**Comment by chenxiaolong** [comment]
Can you check if the same thing happens with the WAV/PCM output format? This is unfortunately likely a bug in the ROM or the modem firmware. BCR outputs the audio it receives from Android as-is--it never touches/alters the audio data.

**Comment by konradpabijan** [comment]
I have same bug, also caller voice is low volume, but mine is loud and clear.
