### ISSUE TITLE
App doesn't work on Realme 7

### ISSUE THREAD

**Issue by leopseft** [chenxiaolong/BCR#137]
The app opens but seems too laggy plus its an empty frame, like a white page shows nothing.
I tested with the latest version of the app on stock rom with android 11 on realme 7 rmx2155.
If you need any further information please feel free to comment and I will provide you whatever you need.

**Comment by chenxiaolong** [comment]
Just to confirm, did you follow the `For OnePlus and Realme devices` section at https://github.com/chenxiaolong/BCR? There's a bug on Realme stock ROMs that requires some extra steps.
