### ISSUE TITLE
Recordings very distorted or cut short with other call recording apps

### ISSUE THREAD

**Issue by luke-jr** [chenxiaolong/BCR#141]
Initially tried to setup BCR as a 3rd alternative since ACR and com.github.axet.callrecorder have stopped working randomly. At first, calls were recorded garbled, then immediately ended after a few ms.

Using `pm hide` to disable both other apps made BCR work fine (so far).

Device: Pixel 3a

**Comment by chenxiaolong** [comment]
Ah yep, this is an audio driver limitation. Most devices' drivers are implemented in a way that only allows one audio stream. This is also why it's not possible to have stereo recordings where the two parties' voices are on two channels.

There's no way for BCR (of any other app) to work around this.

**Comment by luke-jr** [comment]
No way to use dsnoop, I guess? :\
