### ISSUE TITLE
create an addon.d script when using recovery

### ISSUE THREAD

**Issue by pokegamer5547** [chenxiaolong/BCR#142]
updating OS would delete BCR all the time, having an addon.d would be very handy.

**Comment by chenxiaolong** [comment]
Please give this debug build a try: [BCR-1.21.r2.gbf6d3b4-debug.zip](https://github.com/chenxiaolong/BCR/files/9711608/BCR-1.21.r2.gbf6d3b4-debug.zip) (built from commit bf6d3b44e81a62548b190a60379e885051c86bdd).

If it doesn't work, please upload `/tmp/recovery.log`. Unfortunately, I don't have any device that supports custom recoveries + flashable zips.

**Comment by pokegamer5547** [comment]
> Please give this debug build a try: [BCR-1.21.r2.gbf6d3b4-debug.zip](https://github.com/chenxiaolong/BCR/files/9711608/BCR-1.21.r2.gbf6d3b4-debug.zip) (built from commit [bf6d3b4](https://github.com/chenxiaolong/BCR/commit/bf6d3b44e81a62548b190a60379e885051c86bdd)).
> 
> If it doesn't work, please upload `/tmp/recovery.log`. Unfortunately, I don't have any device that supports custom recoveries + flashable zips to test this myself.

Thanks! That was really quick. I tested it just now and it survives OTA now :)

**Comment by chenxiaolong** [comment]
Great, thanks for testing! The change will be included in the next release (1.22).
