### ISSUE TITLE
Any way to install unrooted custom firmware?

### ISSUE THREAD

**Issue by Asadulit** [chenxiaolong/BCR#154]
I try to install Pixel Experience custom rom but not working. any way to install this? 

I try this method but show error!
For unrooted custom firmware, flash the zip while booted into recovery.

I can't understand this section.
Manually extracting the files from the system/ folder in the zip will also work as long as the files have 644 permissions and the u:object_r:system_file:s0 SELinux label.

Thanks.

**Comment by chenxiaolong** [comment]
What errors did you get when you tried flashing the zip? Can you `adb pull /tmp/recovery.log` right after flashing and then upload that?

**Comment by Asadulit** [comment]
Thanks for your replay. :)

Please check the attached file and Please give me a solution about this. 

Thanks 👍 

![BCR recovery log](https://user-images.githubusercontent.com/31082292/197159827-8b4b7db5-079e-45f6-a87a-2fb0b88e4d51.jpg)

![BCR Error](https://user-images.githubusercontent.com/31082292/197159895-d0cd859e-581e-4b1c-accf-33be1a2410ff.jpg)

![BCR-Phone Screen Error](https://user-images.githubusercontent.com/31082292/197159926-b0c1ca67-d23b-4e55-9bc3-2c83e9305b76.jpg)

**Comment by Asadulit** [comment]
Thanks for your recommendation, I will check and update you. :)

**Comment by Asadulit** [comment]
Basic Call Recorder Installation Tips for Unroot devices!!!

1st install app-release.apk file from original zip file. 

2nd Install OrangeFox recovery and install the original zip file. this way working my pixel experience custom rom.

Thanks a lot [Andrew Gunnerson](https://github.com/chenxiaolong)

**Comment by chenxiaolong** [comment]
Great, glad you got it working!
