### ISSUE TITLE
Upload calls to third party storage 

### ISSUE THREAD

**Issue by Hoopex** [chenxiaolong/BCR#157]
Hello
First thank you for your amazing work.
Can you ass new feature to synchronize/upload folder to 3rd storage like Google drive ?

**Comment by chenxiaolong** [comment]
Thanks for the suggestion, though this will likely not be implemented. BCR doesn't require the internet/network permission for privacy.

Android provides a way to cloud providers to integrate with Android's built in file picker. This method works out of the box with BCR, but unfortunately, not many cloud providers support it (I know Google Drive, Dropbox, etc. don't).
