### ISSUE TITLE
Still saving in data folder

### ISSUE THREAD

**Issue by laltroweb** [chenxiaolong/BCR#158]
Hi, I set media folder for allow file access and backup (like from my previous request), but seen now still saving in data folder.
See my screen.
![Screenshot_20221028-142612_BCR](https://user-images.githubusercontent.com/16841896/198587263-33a5c7ff-8f08-405e-a460-f5f5d0c93c9a.png)
![Screenshot_20221028-142625_Solid Explorer](https://user-images.githubusercontent.com/16841896/198587274-4b9d1a7a-6e40-4788-b3b3-578188b0a93a.png)

Any idea for fix?
Ty

**Comment by chenxiaolong** [comment]
Can you enable debug mode by long pressing the BCR version number and then make a new recording? It will create a log file in the output directory. Please upload that log file here.

**Comment by laltroweb** [comment]
> Can you enable debug mode by long pressing the BCR version number and then make a new recording? It will create a log file in the output directory. Please upload that log file here.

Sure and thanks for replying 👍
![Screenshot_20221028-215119_Solid Explorer](https://user-images.githubusercontent.com/16841896/198720986-ae46b69f-4eff-4536-9f9f-34312ae5a42c.png)

![Screenshot_20221028-215243_BCR](https://user-images.githubusercontent.com/16841896/198721052-10344e8a-126b-48e8-a5c0-0735364510c7.png)

[20221028_215017.449+0200_out_160__PosteItaliane_.log.txt](https://github.com/chenxiaolong/BCR/files/9891386/20221028_215017.449%2B0200_out_160__PosteItaliane_.log.txt)

**Comment by laltroweb** [comment]
Ok, seen in log a issue with moved file.
Try to set again directory and now ask me permission to use media folder.
Sorry, but cannot know why failed first time 😅🤔
Then, now seems to work as expected (new log).
[20221028_220049.624+0200_out_800003322__PosteItaliane_.log.txt](https://github.com/chenxiaolong/BCR/files/9891443/20221028_220049.624%2B0200_out_800003322__PosteItaliane_.log.txt)

**Comment by chenxiaolong** [comment]
Great! I'm not sure why it failed before either... I've never seen it lose permission to a folder after permission was already granted.
