### ISSUE TITLE
Manually extracted files in system/ and phone got stuck in a bootloop

### ISSUE THREAD

**Issue by abdulrahim-ss** [chenxiaolong/BCR#159]
The phone I have is unrooted but has custom firmware. Tried manually extracting the files and copying them to their correct destinations with the necessary permissions. But upon reboot, first, the app didn't show up (I suspect that it didn't install in the first place despite being in the `priv-app` folder with 644 permissions), but when I retried the whole process, the phone got stuck in a bootloop.
Anyone has an idea why? Otherwise, is there a package containing all the files necessary that you can just copy to `priv-app `folder which gives BCR full system app privileges in order to skip unnecessary headaches??

**Comment by chenxiaolong** [comment]
Interesting. I don't know what would cause a boot loop. If something went wrong, Android is supposed to just ignore the app like you encountered on the first try (unless the custom ROM does something different from what AOSP does).

> Otherwise, is there a package containing all the files necessary that you can just copy to priv-app folder which gives BCR full system app privileges in order to skip unnecessary headaches??

Yes, with the latest version of BCR, the zip can be directly flashed from recovery and it will set up the permissions correctly.

**Comment by abdulrahim-ss** [comment]
My phone is an old Sony XZ1 with a special firmware from Sony itself for testing purposes. I did not flash a custom recovey on it. The way I extracted the files manually was through adb root.

> the zip can be directly flashed from recovery and it will set up the permissions correctly.

Do you suggest flashing TWRP and installing the zip file from there?
Thank you for the fast response I really appreciate it!

**Comment by chenxiaolong** [comment]
Ahh, I see. Yes, I'd recommend TWRP as the best way to do it.

If you're doing it manually via `adb root`, I'd suggest making sure the permissions are all correct. The directories must be 755, the files 644, and the SELinux label for everything `u:object_r:system_file:s0`.
```bash
chmod 755 /system/priv-app/com.chiller3.bcr/
chmod 644 /system/priv-app/com.chiller3.bcr/app-release.apk
chmod 644 /system/etc/permissions/privapp-permissions-com.chiller3.bcr.xml

chcon -R u:object_r:system_file:s0 /system/priv-app/com.chiller3.bcr/
chcon u:object_r:system_file:s0 /system/etc/permissions/privapp-permissions-com.chiller3.bcr.xml
```

**Comment by abdulrahim-ss** [comment]
OK thank you so much!
