### ISSUE TITLE
App displays a black screen when opened

### ISSUE THREAD

**Issue by effectively0** [chenxiaolong/BCR#162]
Just installed this app on a new phone, rooted Realme Narzo 50. Installed version 1.22 and haven't tried previous versions before.
firmware RMX3286export_11_A.56_2022051300470000
Android 11.
Pressing the app has a delay of several seconds before opening to a black screen.

**Comment by chenxiaolong** [comment]
Just to confirm, did you follow the Realme-specific instructions in step 2 at https://github.com/chenxiaolong/BCR?

There's a bug in the OnePlus/Realme stock firmware (or ROMs based on the stock firmware) that causes the black/white screen issue, but the workaround in the link should help.
