### ISSUE TITLE
Can't enable System Mixer incall Recording

### ISSUE THREAD

**Issue by TobyAdd** [chenxiaolong/BCR#172]
![Screenshot_20221124-203919932](https://user-images.githubusercontent.com/66429886/203849236-0bd1bdd8-9535-473e-9f98-2620ab5fe2c2.jpg)
When I try to enable this item, I get this error, how to fix it?
The phone is Xiaomi Redmi Note 9 Pro,
The firmware is QQ3A.200805.001
PixelExperience_Plus_curtana-10.0-20201121-0747-OFFICIAL

**Comment by TobyAdd** [comment]
the device is rooted and installed using magisk

**Comment by chenxiaolong** [comment]
Hi, I think you reported this at the wrong place. This issue tracker is for BCR, but your screenshot is of a different app.
