### ISSUE TITLE
Add Sim Details to recording name

### ISSUE THREAD

**Issue by hubono** [chenxiaolong/BCR#177]
Hello
Thanks for your wonderful work.
I would like to request a feature if at all possible.
As the title says, upon saving the sound file, can you please add the sim number to the file name. Most use 2 or 3 Sims. BCR will record all phone calls, it would be nice to be able to tell that which recording happened using what sim.
Cheers

**Comment by chenxiaolong** [comment]
Please give the test build at #178 a try. It will add `_sim<number>` to the filename for multi-SIM devices that run Android 11 or newer.

You'll have to go to Android's settings and manually grant BCR the "phone" permission (which is required to determine the SIM slot of a call).

**Comment by hubono** [comment]
Perfect it works.
Cheers for that.
I wanted to suggest another small option. Once a call is completed, a notification currently pops up in the notification area saying recording completed with 2 options, open and share. If u could add delete also to it that will give us the option to delete unwanted recordings right after that call.
Cheers for all your work.

**Comment by chenxiaolong** [comment]
Great, thanks for testing!

> I wanted to suggest another small option. Once a call is completed, a notification currently pops up in the notification area saying recording completed with 2 options, open and share. If u could add delete also to it that will give us the option to delete unwanted recordings right after that call.

I like that idea. I've created #179 to track that feature request.
