### ISSUE TITLE
Notification issue

### ISSUE THREAD

**Issue by laltroweb** [chenxiaolong/BCR#184]
https://user-images.githubusercontent.com/16841896/204638140-95d008d9-3453-4f4f-991d-1253475657e1.mp4

Like from recording, cannot open file from notification.

**Comment by chenxiaolong** [comment]
Hmm, I can't reproduce this on my device (also opening with Solid Explorer).

Is this a fresh install of BCR or an upgrade from a previous version? If it's an upgrade, you have to use the Reset to Defaults option in BCR and pick the output directory again or else the open/share options won't work.
