### ISSUE TITLE
option to disable call recorded notification.

### ISSUE THREAD

**Issue by bonyjose** [chenxiaolong/BCR#185]
I like my recorder to run in background and do its job, i don't want a notification after every call, can you add an option to disable app notification? Thanks. Great app btw, very useful.

**Comment by chenxiaolong** [comment]
Yep, this is already supported. Just go to Android's notification settings for BCR and turn off the `Success alerts` checkbox.

For example: [Screenshot_20221202-124528](https://user-images.githubusercontent.com/646253/205353783-24665b22-7d64-4446-9fc2-87c62da7e27c.png)

**Comment by bonyjose** [comment]
@chenxiaolong Thank you, i was looking at the app settings for his option, disabling notification works great.

**Comment by bonyjose** [comment]
It worked
