### ISSUE TITLE
Add support for custom date/time format in the output filename

### ISSUE THREAD

**Issue by chenxiaolong** [chenxiaolong/BCR#204]
From @nikhilbadyal's comment at: https://github.com/chenxiaolong/BCR/pull/189#issuecomment-1363705779

> It's possible to add custom format for `${date}` like `yyyy-MM-ddHH:mm:ss` . I don't want `time_zone` in output filename. As it container ugly `+` sign.

**Comment by chenxiaolong** [comment]
This is implemented in #205 and will be part of version 1.27.

Instead of `${date}`, you can now specify any custom format. For example, `${date:yyyyMMdd_HHmmss}`. `${date:yyyy-MM-ddHH:mm:ss}` from your original comment will work too, though Android doesn't allow colons in filenames, so those would get converted to underscores.

**Comment by nikhilbadyal** [comment]
If you don't mind can you answer a question.

How do you test while developing. I want to add some features. Simply running the app in Android studio doesn't work. It doesn't start call recording if i call on the number.(I'm running an emulator).

How actually you test and develop?

**Comment by chenxiaolong** [comment]
Sure. I develop and test on a real device (Pixel 7 Pro). For testing calls, I dial voicemail (close to 300 times by now...). An emulator might work if it's possible to root the emulator image and also simulate a phone call (I'm not sure if it is).

Running from Android Studio won't work by default because it installs BCR as a user app. BCR requires system app permissions to be able to detect calls and record the audio.

The easiest way to develop is to first create a debug zip with `./gradlew zipDebug` (output is in the `app/build/distributions/debug` folder) and then flash that zip in Magisk Manager. That way, a debug build of BCR is installed as a system app. After that, you can just build and run from Android Studio. This works because Android allows updates to system apps to be installed as regular user apps.

**Comment by drkhemu** [comment]
hello developer sorry to bother you here, unfortunately i could not find bcr.properties file in output directory ? could you pls help me !! where  to find it exactly

**Comment by nikhilbadyal** [comment]
Hey @drkhemu  you will not find. You can create yourself in the same directory where your recordings are stored.

**Comment by drkhemu** [comment]
@nikhilbadyal Hello thanks for reply , actually i tried to do that but nothing happened and when i checked log file it said , " failed to load custom filename template " and it fall back to default template , could u pls helpe.to understand it more.
i am in severe need of that

**Comment by nikhilbadyal** [comment]
@drkhemu in that case can you share the content and location (as screenshot) of the `bcr.properties` file.

**Comment by drkhemu** [comment]
@nikhilbadyal hello it got solved actually , thanks for reply and time
chenxiaolong answered that you can not change ${date} in custom template as it has to be first name compulsary. So when I did that it worked.

**Comment by nikhilbadyal** [comment]
@chenxiaolong module after zipDebug fails to install.
![Screenshot_1672502192](https://user-images.githubusercontent.com/59223300/210148986-1e513b23-bac2-4815-9b32-2ee90a39b241.png)

Any idea why so ?

**Comment by chenxiaolong** [comment]
Hmm, I've never seen that before. Does anything show up in Magisk's logs? Can you upload the zip file you built?

**Comment by nikhilbadyal** [comment]
[Here it is.](https://github.com/chenxiaolong/BCR/files/10327839/BCR-1.29.r2.g52bef6d-debug.zip)

**Comment by chenxiaolong** [comment]
```
[13:59:48] cxl-desktop-1 …/bcr/temp
❯ unzip ../BCR-1.29.r2.g52bef6d-debug.zip
Archive:  ../BCR-1.29.r2.g52bef6d-debug.zip
  inflating: module.prop
  inflating: LICENSE
  inflating: README.md
   creating: system/
   creating: system/addon.d/
  inflating: system/addon.d/51-com.chiller3.bcr.sh
   creating: system/etc/
   creating: system/etc/permissions/
  inflating: system/etc/permissions/privapp-permissions-com.chiller3.bcr.xml
   creating: system/priv-app/
   creating: system/priv-app/com.chiller3.bcr/
  inflating: system/priv-app/com.chiller3.bcr/app-debug.apk
   creating: META-INF/
   creating: META-INF/com/
   creating: META-INF/com/google/
   creating: META-INF/com/google/android/
  inflating: META-INF/com/google/android/update-binary
  inflating: META-INF/com/google/android/updater-script

[13:59:51] cxl-desktop-1 …/bcr/temp
❯ file META-INF/com/google/android/update-binary
META-INF/com/google/android/update-binary: a /sbin/sh script, ASCII text executable, with CRLF line terminators
```

It looks like the text files in the zip have Windows line endings (`\r\n`) instead of Unix ones (`\n`). That's probably why Magisk won't install it.

Googling the issue, it seems like git does this conversion by default on Windows, but you can disable it with:
```
git config --global core.autocrlf false
```
and then cloning the git repo again.

**Comment by nikhilbadyal** [comment]
Thanks for the help. I was thinking the same. As it appeared to work in Mac but not in Windows.
<img width="469" alt="image" src="https://user-images.githubusercontent.com/59223300/210153478-dd4c29d3-db22-4490-9492-aac9966cb16e.png">
