### ISSUE TITLE
Fail to load custom filename template and it fall back to default filename template 

### ISSUE THREAD

**Issue by drkhemu** [chenxiaolong/BCR#208]
![Screenshot_20221227-155230_Material Files](https://user-images.githubusercontent.com/120331419/209653362-361c5442-f18a-4c0a-b298-6fa2493d554e.png)
It says fail to load custom filename template

[Log file link ](https://we.tl/t-xQO76K1Wvy) 
Here is link of full logfile

Pls help in this 

@chenxiaolong

**Comment by chenxiaolong** [comment]
Thanks for the logs. The issue is `The first filename component must be ${date}`.

BCR currently requires to the date to be at the beginning of the filename. This is needed for the file retention feature to work.

You'll have to move `${date}` back to the beginning (`filename.0.text`).

**Comment by drkhemu** [comment]
@chenxiaolong thanks for your answer and time. I did exactly what you said and my problem got fixed. Thanks again 👍💐
