### ISSUE TITLE
No Sound In Recorded call

### ISSUE THREAD

**Issue by hypersoumya** [chenxiaolong/BCR#214]
Hello , I found one issue that its recording my call but there is no sound in recorded call .. can you tell me please how can i fix this .. this is the only annoying things i found otherwise your app is one of the best call recording app .. waiting for your reply
Thank you

**Comment by chenxiaolong** [comment]
Please try setting the output format to WAV. If those recordings also have no sound, then unfortunately, your device (or the ROM you're running) doesn't support call recording.

**Comment by hypersoumya** [comment]
> Please try setting the output format to WAV. If those recordings also have no sound, then unfortunately, your device (or the ROM you're running) doesn't support call recording.

I also tried that .. but same problem .. i am running derpfest on my redmi note 10 pro .. here its not working but on my another device same rom i am using but there it was working..

**Comment by chenxiaolong** [comment]
> The actually problem is .. if my calling time is for around 3 minutes the recorded file is showing 0.2 min with no sound ..

Can you enable debug mode by long pressing BCR's version number and then try to record a call? It'll create a log file in the output directory. Please upload that here.

**Comment by hypersoumya** [comment]
[20230113_231851.904+0530_out_sim1_199_Vodafone Care.log.txt](https://github.com/chenxiaolong/BCR/files/10414130/20230113_231851.904%2B0530_out_sim1_199_Vodafone.Care.log.txt)

Here is the log @chenxiaolong 
I am using Pixel rom

Sorry for late reply

**Comment by chenxiaolong** [comment]
No worries. It's likely that your device or the ROM you're running doesn't properly support call recording. It's correctly detecting when the call begins and ends, but Android is not providing audio data to BCR. 

I'd suggest trying the 16000 Hz sample rate. If that also doesn't work, there's probably nothing that can be done.
