### ISSUE TITLE
Building the magisk module zip

### ISSUE THREAD

**Issue by Ceynou** [chenxiaolong/BCR#215]
```bash
export RELEASE_KEYSTORE=/path/to/keystore.jks
export RELEASE_KEY_ALIAS=alias_name

read -r -s RELEASE_KEYSTORE_PASSPHRASE
read -r -s RELEASE_KEY_PASSPHRASE
export RELEASE_KEYSTORE_PASSPHRASE
export RELEASE_KEY_PASSPHRASE
```
So it seems that `export` is `set` on windows but I can't find anything for `read` because the command doesn't work

**Comment by chenxiaolong** [comment]
Hmm, I'm not familiar with Windows' cmd, but maybe you can just set the environment variables directly? Eg.

```
set RELEASE_KEYSTORE_PASSPHRASE=<password here>
```

(On Unix-like systems, the `read` command just prompts for the password invisibly so that it won't show up on screen.)

**Comment by Ceynou** [comment]
I ended up building the zip on a linux VM, for some reason it wouldn't even get the path of the keystore file, maybe I just had to type `\:` instead of plain `:`
