### ISSUE TITLE
Call Recorder Folder

### ISSUE THREAD

**Issue by Savaturkey** [chenxiaolong/BCR#216]
even though I have selected the save folder in the application settings, it saves to the android>data>com.chilller3.bcr>files folder, which is the default. Even though I edit it from the app, it doesn't save it to the folder I want. this problem started with the last two updates.

**Comment by chenxiaolong** [comment]
Does it work if you hit the reset to defaults button for the output directory and pick it again? Some versions of Android have a bug where permissions to selected directories are sometimes lost after a reboot.

**Comment by Savaturkey** [comment]
unfortunately it didn't work. After restarting it goes back to default settings. I installed version 1.26, there is no problem in that version.
I think there is a problem with apk. When I flashed it with 1.29 magisk and changed the apk files from priv-app and moduls folders, the problem was gone.

**Comment by chenxiaolong** [comment]
I'm not fully understanding what you mean in the 1.29 part. What did you have to change to fix the problem?

**Comment by Savaturkey** [comment]
To be more clarified, I installed version 1.29 with magisk. I then deleted the bcr 1.26 apk file with root access inside the modul folder under the system and copied the 1.26 apk file here. then I deleted the bcr app in priv-app under the system folder again and copied the 1.26 apk file in the same way. It's working smoothly right now.

**Comment by chenxiaolong** [comment]
Interesting. I wonder why that would be needed on your device. Magisk is supposed to automatically remove the old files during an upgrade.

Glad you got it working though.

**Comment by Savaturkey** [comment]
The problem has been fixed in the latest version.
