### ISSUE TITLE
integration is off

### ISSUE THREAD

**Issue by ghorbat** [chenxiaolong/BCR#218]
hi tjanks for madule
I want to use this module with a True Phone Dialer & Contacts
( https://play.google.com/store/apps/details?id=com.hb.dialer.free )
 program, but the said program says in its settings that you must activate the option in the picture, but I did not find it. Please help me.
 
![photo_2023-01-10_14-57-25](https://user-images.githubusercontent.com/23626707/211541854-ea7a716c-56c9-4742-8f42-94edeb8b9d5c.jpg)

**Comment by SigmaBonder** [comment]
You're in the wrong repo.

**Comment by chenxiaolong** [comment]
If you're asking about the SKVALEX call recorder, then this is the wrong place for that (different app).

However, if you're asking about BCR, then there's nothing that needs to be done. BCR doesn't conflict with True Phone and they should work together without changing any settings.

**Comment by ghorbat** [comment]
> If you're asking about the SKVALEX call recorder, then this is the wrong place for that (different app).
> 
> However, if you're asking about BCR, then there's nothing that needs to be done. BCR doesn't conflict with True Phone and they should work together without changing any settings.

tanks but by true phone not work

**Comment by chenxiaolong** [comment]
If you're talking about features, like pausing/resuming the recording, the only way to do that with BCR is via its notification.
