### ISSUE TITLE
app doesn't appear while call, there is no sign of permission in system settings

### ISSUE THREAD

**Issue by alex1299** [chenxiaolong/BCR#227]
Poco f4, xiaomi.eu 14 ( android 13 ), magisk.
There is no sign of permission in system settings, although the app asked them and got. While call there is no trace of app and no sound files.

**Comment by chenxiaolong** [comment]
> and the app doesn't ask for the root

That's normal. Magisk is used for installation as a system app only. BCR does not require root once installed.

---

During a call, is there any notification from BCR? If not, please use `adb logcat` (or a logcat app) to grab the logs immediately after making a phone call.

**Comment by KyleBroflowski** [comment]
Try starting in paused state. Do you get the notified?

**Comment by KyleBroflowski** [comment]
Try starting in paused state. Do you get the notified?

**Comment by alex1299** [comment]
Sorry, forget to mention that I tried telegram and the recording didn't work. Today I make a cellular call and it appears that BCR works fine: it recorded the audio and made the log. But cellular call I could record even without root and additional program.

**Comment by KyleBroflowski** [comment]
@alex1299  same. Same case with WhatsApp too.

**Comment by chenxiaolong** [comment]
Ah, yep. BCR supports phone calls only. For WhatsApp, Telegram, or calls in any other third party app, you'll have to use a different call recorder app.
