### ISSUE TITLE
[REQUEST] KernelSU based module 

### ISSUE THREAD

**Issue by drkhemu** [chenxiaolong/BCR#234]
@chenxiaolong Hello , first of all i am enjoying the app most.

3 Questions
1) can i flash the module in kernelSU manager (kernel based root) safely ? If yes then it's fine
2) if Q1 ans is no, can u pls make BCR module that work in kernelSU ?
3) if Q2 ans is no, can u pls provide an apk for bcr that would ask root permission while setting it up ? (So kernel based su manager can give it root permission to work properly)

Thanks n regards

**Comment by chenxiaolong** [comment]
> 1. can i flash the module in kernelSU manager (kernel based root) safely ? If yes then it's fine

It should be safe to try. The only thing the flashing scripts do is put BCR's files in `/data/adb/modules`. If KernelSU's modules work differently from Magisk's, then the files won't do anything.

> 2. if Q1 ans is no, can u pls make BCR module that work in kernelSU ?

Do you know of any examples of KernelSU modules? I can't find any documentation about it besides this: https://kernelsu.org/guide/faq.html#does-kernelsu-support-modules If it's not too different from how Magisk modules work, then I might consider supporting it.

> 3. if Q2 ans is no, can u pls provide an apk for bcr that would ask root permission while setting it up ? (So kernel based su manager can give it root permission to work properly)

It can't work this way. Call recording requires system app permissions, not root. The only thing BCR uses Magisk for is to easily install it as a system app.

**Comment by drkhemu** [comment]
@chenxiaolong Hi , thanks for your answers sir,
i took risk and decide to try it and you know the AWESOME thing is , **_ITS WORKING in KernelSu manager_** ...i did not face any boot loop problem and also it records all calls fine just like it work wid magisk

i would highly appreciate your efforts **if you could provide separate kernelsu compatible module in future.**

but as now now i am enjoyin kernelsu and bcr both.. 
i would hv returned to magisk just for bcr but now  kernelsu will be continued .

again thanks you very much for the  wonderful app

**Comment by chenxiaolong** [comment]
Glad it's working! It seems like KernelSU uses the same module format as Magisk then.

> i would highly appreciate your efforts if you could provide separate kernelsu compatible module in future.

I don't think it should be necessary, but if it is in the future, then we can reopen this issue.
