### ISSUE TITLE
First half second not recorded

### ISSUE THREAD

**Issue by NMBlanco** [chenxiaolong/BCR#236]
When I make an outgoing call, the first half second is never recorded. Sometimes its even up to 1 second thats missing from the recording. It might sound not too bad but I just wanted to ask if thats normal behaviour?

Android 12, Motorola Edge 30 Ultra, Stock Rom, latest Magisk and LSposed using BCR 1.30

**Comment by chenxiaolong** [comment]
Can you enable debug mode by long pressing BCR's version number and then upload the log file it creates in the output directory after a call?

**Comment by NMBlanco** [comment]
Its kinda weird, I can't really reproduce it with an outgoing call anymore. 
Its more present when somebody calls me (incoming), the first second just gets cut off.
I try to log it next time

**Comment by chenxiaolong** [comment]
Version 1.35 added a workaround will likely fix this. If you run into this again after updating, please feel free to reopen this issue.
