### ISSUE TITLE
NFC not working on Xiaomi 12 Pro MIUI 14

### ISSUE THREAD

**Issue by Donaldcwl** [chenxiaolong/BCR#242]
After upgrading to MIUI 14, the NFC crash on boot and NFC is not working. I can only use NFC after disabling BCR in Magisk followed by a reboot.

here is the error trace:
![Screenshot_2023-02-12-21-04-25-567_com miui bugreport](https://user-images.githubusercontent.com/11781337/218319822-9f64e468-cca3-4b1e-9982-c3f5463c0caa.jpg)

Appreciate if anyone can help with this. Thanks

**Comment by chenxiaolong** [comment]
Hmm, I have no idea what might be causing this. BCR's Magisk module doesn't do anything more than installing it as a system app (it doesn't modify other apps or components). BCR doesn't even run in the background until a phone call begins.

**Comment by Donaldcwl** [comment]
I guess there my be some conflict in my Magisk.
I would like to reinstall the BCR. May I know if there is any way to uninstall the BCR from Magisk without residual files/config? (because the config is still there after I reinstall it)

**Comment by Donaldcwl** [comment]
No luck :( Don't know why NFC still not working when BCR is enabled in Magisk.

**Comment by chenxiaolong** [comment]
Does it only happen if BCR is enabled in Magisk or does NFC break whenever any module is enabled?

**Comment by Donaldcwl** [comment]
Thanks for your help.
It only happens if BCR is enabled in Magisk.

My other modules are Shamiko and Universal SafetyNet Fix. NFC works no matter they are enabled or disabled.

**Comment by chenxiaolong** [comment]
If you're able to grab the full logcat immediately after a reboot (once with BCR and once without), I can try to take a look, but I don't really have any more ideas.
