### ISSUE TITLE
Getting notification error "Failed to record call" on /e/OS, 

### ISSUE THREAD

**Issue by samkhao** [chenxiaolong/BCR#247]
BCR 1.33
e/OS 1.7-r-20230110250404-stable-emerald
running on Teracube 2e

At start of call getting notification:

> **Failed to record call**
> 
> The recording failed in an internal Android component (android.media.AudioRecord.native_gte_buffer_size_in_frames). This device or firmware might not support call recording.
> 
> Unable to retrieve AudioRecord pointer for frameCount()

When I click on the notification I also get toast:

> I/O error!

Tried OGA, M4A, FLAC, and WAV output formats; each time file appears in output directory but with size 0.

Enabled debug mode and noticed the following debug output with error codes -22 and -20:

```
--------- beginning of main
....655  3126  3317 E AudioRecord: createRecord_l(540697972): AudioFlinger could not create record track, status: -22
....660  3126  3317 E AudioRecord-JNI: Error creating AudioRecord instance: initialization check failed with status -22.
....662  3126  3317 E android.media.AudioRecord: Error code -20 when initializing native AudioRecord object.
....665  3126  3317 D RecorderThread/302: Creating ..._in_<phone number>.oga with MIME type audio/ogg in content://com.android.externalstorage.documents/tree/primary%3A...
....748  3126  3317 I RecorderThread/302: Successfully moved file:///storage/emulated/0/Android/data/com.chiller3.bcr/files/..._in_<phone number>.oga to content://com.android.externalstorage.documents/tree/primary:..._in_<phone number>.oga
....751  3126  3317 I RecorderThread/302: Keeping all existing files
....752  3126  3317 E RecorderThread/302: Error during recording
....752  3126  3317 E RecorderThread/302: java.lang.IllegalStateException: Unable to retrieve AudioRecord pointer for frameCount()
....752  3126  3317 E RecorderThread/302:    at android.media.AudioRecord.native_get_buffer_size_in_frames(Native Method)
....752  3126  3317 E RecorderThread/302:    at android.media.AudioRecord.getBufferSizeInFrames(AudioRecord.java:1013)
....752  3126  3317 E RecorderThread/302:    at com.chiller3.bcr.RecorderThread.recordUntilCancelled(RecorderThread.kt:52)
....752  3126  3317 E RecorderThread/302:    at com.chiller3.bcr.RecorderThread.run(RecorderThread.kt:99)
....752  3126  3317 I RecorderThread/302: Recording thread completed
....753  3126  3317 D RecorderThread/302: Stopping log file
....762  3126  3317 D RecorderThread/302: Creating ..._in_<phone number>.log.txt with MIME type text/plain in content://com.android.externalstorage.documents/tree/primary%3A...
....872  3126  3317 I RecorderThread/302: Successfully moved file:///storage/emulated/0/Android/data/com.chiller3.bcr/files/..._in_<phone number>.log.txt to content://com.android.externalstorage.documents/tree/primary:..._in_<phone number>.log.txt
....874  3126  3317 W RecorderInCallService: Recording failed: 302: content://com.android.externalstorage.documents/tree/primary:..._in_<phone number>.oga
....373  3126  3126 D RecorderInCallService: onStateChanged: Call [id: TC@1, state: DISCONNECTED, details: [id: TC@1, pa: ComponentInfo{com.android.phone/com.android.services.telephony.TelephonyConnectionService}, ***, UserHandle{0}, hdl: tel:************, hdlPres: 1, videoState: Audio Only, caps: [Capabilities: CAPABILITY_HOLD CAPABILITY_SUPPORT_HOLD CAPABILITY_MUTE CAPABILITY_SUPPORTS_VT_LOCAL_RX CAPABILITY_SUPPORTS_VT_LOCAL_TX CAPABILITY_SUPPORTS_VT_LOCAL_BIDIRECTIONAL], props: [Properties: PROPERTY_HIGH_DEF_AUDIO]]], 7
....374  3126  3126 D RecorderInCallService: handleStateChange: Call [id: TC@1, state: DISCONNECTED, details: [id: TC@1, pa: ComponentInfo{com.android.phone/com.android.services.telephony.TelephonyConnectionService}, ***, UserHandle{0}, hdl: tel:************, hdlPres: 1, videoState: Audio Only, caps: [Capabilities: CAPABILITY_HOLD CAPABILITY_SUPPORT_HOLD CAPABILITY_MUTE CAPABILITY_SUPPORTS_VT_LOCAL_RX CAPABILITY_SUPPORTS_VT_LOCAL_TX CAPABILITY_SUPPORTS_VT_LOCAL_BIDIRECTIONAL], props: [Properties: PROPERTY_HIGH_DEF_AUDIO]]], 7, 7
....375  3126  3126 D RecorderThread/302: Requested cancellation

```

**Comment by chenxiaolong** [comment]
Unfortunately, your device + ROM combination won't work for call recording. It's failing at the very first step of setting up the Android audio device. `-22` is `-EINVAL` (`Invalid argument`), which happens if the call recording audio device does not exist.

**Comment by vnt-83** [comment]
> BCR 1.33 e/OS 1.7-r-20230110250404-stable-emerald running on Teracube 2e
> 
> At start of call getting notification:
> 
> > **Failed to record call**
> > The recording failed in an internal Android component (android.media.AudioRecord.native_gte_buffer_size_in_frames). This device or firmware might not support call recording.
> > Unable to retrieve AudioRecord pointer for frameCount()
> 
> When I click on the notification I also get toast:
> 
> > I/O error!
> 
> Tried OGA, M4A, FLAC, and WAV output formats; each time file appears in output directory but with size 0.
> 
> Enabled debug mode and noticed the following debug output with error codes -22 and -20:
> 
> ```
> --------- beginning of main
> ....655  3126  3317 E AudioRecord: createRecord_l(540697972): AudioFlinger could not create record track, status: -22
> ....660  3126  3317 E AudioRecord-JNI: Error creating AudioRecord instance: initialization check failed with status -22.
> ....662  3126  3317 E android.media.AudioRecord: Error code -20 when initializing native AudioRecord object.
> ....665  3126  3317 D RecorderThread/302: Creating ..._in_<phone number>.oga with MIME type audio/ogg in content://com.android.externalstorage.documents/tree/primary%3A...
> ....748  3126  3317 I RecorderThread/302: Successfully moved file:///storage/emulated/0/Android/data/com.chiller3.bcr/files/..._in_<phone number>.oga to content://com.android.externalstorage.documents/tree/primary:..._in_<phone number>.oga
> ....751  3126  3317 I RecorderThread/302: Keeping all existing files
> ....752  3126  3317 E RecorderThread/302: Error during recording
> ....752  3126  3317 E RecorderThread/302: java.lang.IllegalStateException: Unable to retrieve AudioRecord pointer for frameCount()
> ....752  3126  3317 E RecorderThread/302:    at android.media.AudioRecord.native_get_buffer_size_in_frames(Native Method)
> ....752  3126  3317 E RecorderThread/302:    at android.media.AudioRecord.getBufferSizeInFrames(AudioRecord.java:1013)
> ....752  3126  3317 E RecorderThread/302:    at com.chiller3.bcr.RecorderThread.recordUntilCancelled(RecorderThread.kt:52)
> ....752  3126  3317 E RecorderThread/302:    at com.chiller3.bcr.RecorderThread.run(RecorderThread.kt:99)
> ....752  3126  3317 I RecorderThread/302: Recording thread completed
> ....753  3126  3317 D RecorderThread/302: Stopping log file
> ....762  3126  3317 D RecorderThread/302: Creating ..._in_<phone number>.log.txt with MIME type text/plain in content://com.android.externalstorage.documents/tree/primary%3A...
> ....872  3126  3317 I RecorderThread/302: Successfully moved file:///storage/emulated/0/Android/data/com.chiller3.bcr/files/..._in_<phone number>.log.txt to content://com.android.externalstorage.documents/tree/primary:..._in_<phone number>.log.txt
> ....874  3126  3317 W RecorderInCallService: Recording failed: 302: content://com.android.externalstorage.documents/tree/primary:..._in_<phone number>.oga
> ....373  3126  3126 D RecorderInCallService: onStateChanged: Call [id: TC@1, state: DISCONNECTED, details: [id: TC@1, pa: ComponentInfo{com.android.phone/com.android.services.telephony.TelephonyConnectionService}, ***, UserHandle{0}, hdl: tel:************, hdlPres: 1, videoState: Audio Only, caps: [Capabilities: CAPABILITY_HOLD CAPABILITY_SUPPORT_HOLD CAPABILITY_MUTE CAPABILITY_SUPPORTS_VT_LOCAL_RX CAPABILITY_SUPPORTS_VT_LOCAL_TX CAPABILITY_SUPPORTS_VT_LOCAL_BIDIRECTIONAL], props: [Properties: PROPERTY_HIGH_DEF_AUDIO]]], 7
> ....374  3126  3126 D RecorderInCallService: handleStateChange: Call [id: TC@1, state: DISCONNECTED, details: [id: TC@1, pa: ComponentInfo{com.android.phone/com.android.services.telephony.TelephonyConnectionService}, ***, UserHandle{0}, hdl: tel:************, hdlPres: 1, videoState: Audio Only, caps: [Capabilities: CAPABILITY_HOLD CAPABILITY_SUPPORT_HOLD CAPABILITY_MUTE CAPABILITY_SUPPORTS_VT_LOCAL_RX CAPABILITY_SUPPORTS_VT_LOCAL_TX CAPABILITY_SUPPORTS_VT_LOCAL_BIDIRECTIONAL], props: [Properties: PROPERTY_HIGH_DEF_AUDIO]]], 7, 7
> ....375  3126  3126 D RecorderThread/302: Requested cancellation
> ```

Try update your software. BCR 1.36 work perfectly on /e/OS 1.8.1
