### ISSUE TITLE
Make it easier to enable recording when paused

### ISSUE THREAD

**Issue by ofirnk** [chenxiaolong/BCR#248]
Thanks for all the effort!

Would it possible to make it easier to enable recording when it's paused by default?

Thought about making the current notification a high priority one so it is expanded by default (at least it should, on most devices).
This is the lower hanging fruit.

I'll give another idea on separate comment

**Comment by ofirnk** [comment]
Another possibility is to add a floating notification/button, which would probably make it easier to enable recording.
But also harder to implement , I guess..

**Comment by chenxiaolong** [comment]
That's a good idea. I've changed the default importance to high in #249.

A floating button would be nice, but I'd rather not make the code more complex by adding an accessibility service.

**Comment by ofirnk** [comment]
> That's a good idea. I've changed the default importance to high in #249.

Cool thanks!

> A floating button would be nice, but I'd rather not make the code more complex by adding an accessibility service.


Perhaps Bubbles integration would be easier and with similar value (it's an extension over Notification, and not an extra view)
https://developer.android.com/develop/ui/views/notifications/bubbles
