### ISSUE TITLE
Add an option to delete the call recording after a certian period of time (3 days , 7 days , 14 days , 1 month etc.)

### ISSUE THREAD

**Issue by AdishSagarawat** [chenxiaolong/BCR#25]
hi , 
Please add an option to BCR to automatically delete call recording after a certian period so that I doesn't eats up our phone storage.

**Comment by chenxiaolong** [comment]
While I agree it'd be a nice feature, I currently do not plan on implementing this. However, #21 is getting implemented soon, which will allow for much smaller files than the current FLAC files.
