### ISSUE TITLE
First nearly 7-8 seconds not recorded

### ISSUE THREAD

**Issue by yahorchik1** [chenxiaolong/BCR#252]
As mentioned https://github.com/chenxiaolong/BCR/issues/246#issuecomment-1440508476 
[20230222_233816.187 0300_out_0870.log.txt](https://github.com/chenxiaolong/BCR/files/10808221/20230222_233816.187.0300_out_0870.log.txt)
![33](https://user-images.githubusercontent.com/106557393/220756006-0776912e-41ba-4259-bcc8-744d01e21261.jpg)
Call in 23:38 with duration 18 secs was recorded as 9 secs.  
I use M4A/AAC 64kbps/48kHz output, try to use default settings, same situation.

**Comment by chenxiaolong** [comment]
Thanks for the logs! Can you try this debug build and upload the new logs? [BCR-1.34.r2.gee78dc5-debug.zip](https://github.com/chenxiaolong/BCR/files/10808740/BCR-1.34.r2.gee78dc5-debug.zip)

This debug build does not fix anything. It only adds more information to the logs so I can try to track this down.

**Comment by yahorchik1** [comment]
[20230223_084446.292 0300_out_0870.log.txt](https://github.com/chenxiaolong/BCR/files/10810604/20230223_084446.292.0300_out_0870.log.txt)
The same. Call in 08:44 with duration 20 secs was recorded as 12 secs.

**Comment by chenxiaolong** [comment]
Thanks for the new logs. This might be another case of Android's Storage Access Framework being horribly slow on some devices. I believe Android is taking 7 seconds just to find out that a config file does not exist.

Can you try this new debug build [BCR-1.34.r3.g462ffb6-debug.zip](https://github.com/chenxiaolong/BCR/files/10817396/BCR-1.34.r3.g462ffb6-debug.zip) and upload logs for these two cases?

* Custom output directory (same as what you've been doing)
* Default output directory (with "Reset to defaults" button)

(This build doesn't fix anything either--just adds more log messages)

**Comment by yahorchik1** [comment]
Done. I didn't test early with default output directory. With it record begins from start, without delay.
First log is with custom directory, second with default.
[20230223_224709.93 0300_out_0870.log.txt](https://github.com/chenxiaolong/BCR/files/10817835/20230223_224709.93.0300_out_0870.log.txt)
[20230223_224952.15 0300_out_0870.log.txt](https://github.com/chenxiaolong/BCR/files/10817838/20230223_224952.15.0300_out_0870.log.txt)

**Comment by chenxiaolong** [comment]
Thanks for the new logs. That confirms my theory that Android's storage access framework is horribly slow on your device.

With a custom directory (which must go through Android's Storage Access Framework due to Android's restrictions), it takes 8s 255ms just to check if a file named `bcr.properties` exists.

```
02-23 22:47:12.863  8034 15590 E issue252: [FilenameTemplate] Finding bcr.properties
...
02-23 22:47:21.118  8034 15590 E issue252: [FilenameTemplate] templateFile: null
```

With the default output directory (which has direct file access), it only takes 2ms:

```
02-23 22:49:54.812  8034 17971 E issue252: [FilenameTemplate] Finding bcr.properties
02-23 22:49:54.814  8034 17971 E issue252: [FilenameTemplate] templateFile: null
```

I will try to find a way to work around this.

**Comment by chenxiaolong** [comment]
Please give this new debug build a try and upload the logs (just for the custom directory is enough): [BCR-1.34.r4.gbb23236-debug.zip](https://github.com/chenxiaolong/BCR/files/10819286/BCR-1.34.r4.gbb23236-debug.zip)

This build should hopefully fix the delay.

**Comment by yahorchik1** [comment]
[20230224_080221.206 0300_out_0870.log.txt](https://github.com/chenxiaolong/BCR/files/10822168/20230224_080221.206.0300_out_0870.log.txt)
Now record starts nearly after 0,5 secs.

**Comment by chenxiaolong** [comment]
Awesome. From the logs:

```
02-24 08:02:23.658 18666 20011 E issue252: [FilenameTemplate] Finding bcr.properties
...
02-24 08:02:24.254 18666 20011 E issue252: [FilenameTemplate] templateFile: null
```

596ms to check for a file is still annoyingly slow, but that's an Android limitation. I will keep looking into making this better. It's not possible to speed this step up any further, but I can maybe change it so it happens after the call ends instead of at the beginning.

**Comment by chenxiaolong** [comment]
Stable version 1.35 has been released with further improvements. Hopefully, it'll be much less than 500ms now.
