### ISSUE TITLE
BCR 1.34 don’t work

### ISSUE THREAD

**Issue by geppone70** [chenxiaolong/BCR#253]
Hi
Im using Arrowos 12.1 lavender, vers. 1.34 acts as uninstaller, no app in present After flashing.
I roll back to 1.33. How to uninstall BCR? (To perform a clean flash)

**Comment by chenxiaolong** [comment]
Are you flashing directly from recovery? If so, I think I know where the bug is.

**Comment by geppone70** [comment]
yes, from OrangeFox

**Comment by chenxiaolong** [comment]
Please give this debug build a try: [BCR-1.34.r2.g4dcda5d-debug.zip](https://github.com/chenxiaolong/BCR/files/10819356/BCR-1.34.r2.g4dcda5d-debug.zip)

It should hopefully fix this issue.

**Comment by geppone70** [comment]
This version works correctly, thanks

Il ven 24 feb 2023, 00:39 Andrew Gunnerson ***@***.***> ha
scritto:

**Comment by chenxiaolong** [comment]
Great, thanks for testing. The fix will be included in the next stable version (1.35).
