### ISSUE TITLE
echo

### ISSUE THREAD

**Issue by somelias** [chenxiaolong/BCR#255]
oneplus 7t, oos12 current update. when BCR is active, callers can hear echo. disabling BCR fixes echo issue for caller on other side.

**Comment by chenxiaolong** [comment]
Unfortunately, this is a bug in either the Android audio drivers or the modem firmware. Those components completely control what happens with the call audio. There's nothing BCR can do to work around this.

**Comment by kubo6472** [comment]
Sorry for necroposting, wanted to ask if you can recommend any solutions to this? Like a different ROM?

**Comment by chenxiaolong** [comment]
Yep, using a different ROM is likely the only option for fixing this. Usually, something based on the device's stock OS has a better chance of working well. There's not much you can do besides trial and error though.
