### ISSUE TITLE
How to customize recording name?

### ISSUE THREAD

**Issue by ZooNooU** [chenxiaolong/BCR#256]
I know that it's clearly mentioned in the main page, but I couldn't make it work (I don't know how, frankly)
I created a txt file in the recordings folder (I did set a custom path) and pasted whatever inside that text file had 
and renamed it to `bcr.properties`

all I'm asking for is a step by step user friendly guide on how to make that work if possible (I want to set it so it looks like this `date-contact name` and that's it, no more info) , and thanks in advance for this amazing app 👌🏻

**Comment by chenxiaolong** [comment]
> I created a txt file in the recordings folder (I did set a custom path) and pasted whatever inside that text file had and renamed it to `bcr.properties`

What you did was exactly correct. I assume your text file looked something like this?

```
filename.0.text = ${date}

filename.1.text = ${contact_name}
filename.1.prefix = -
```

If so, can you enable debug mode by long pressing BCR's version number and then upload the log it creates in the output directory after a call?

**Comment by ZooNooU** [comment]
actually no, the content didn't look like that,
as I've said, I copied all what's inside `bcr.properties` (including instructions and # lines) in the main page without making the modifications you mentioned above.

I'll copy paste the lines you wrote above and test.
thanks for the clarification!

**Comment by ZooNooU** [comment]
would this work?
![Screenshot_20230224-200912_MiXplorer](https://user-images.githubusercontent.com/103965987/221269993-16b1a6f1-39a7-4a71-aad7-3fda41b3f099.png)

**Comment by chenxiaolong** [comment]
You'll have to use a different character than `/` (eg. `${date:dd-MM-yyyy}`), but otherwise, yes, that should work.

`/` can't be in the filename because slashes are used to separate the folders in a path, like `/sdcard/Download/<filename>`.

**Comment by ZooNooU** [comment]
> You'll have to use a different character than `/` (eg. `${date:dd-MM-yyyy}`), but otherwise, yes, that should work.
> 
> `/` can't be in the filename because slashes are used to separate the folders in a path, like `/sdcard/Download/<filename>`.

okay got it! thanks alot!
can I use space as a separator? if yes, how?
otherwise I'll just use the underscore.

**Comment by chenxiaolong** [comment]
No problem! Yep, you can use spaces for sure.

If you just want spaces for the date:

```
filename.0.text = ${date:dd MM yyyy}

filename.1.text = ${contact_name}
filename.1.prefix = -
```

If you also want the date and contact name to be separated by a space:

```
filename.0.text = ${date:dd MM yyyy}

filename.1.text = ${contact_name}
filename.1.prefix = \ 
#                    ^
# There is a space here
```

**Comment by ZooNooU** [comment]
alright, perfectly understood.
thanks alot man! :D
