### ISSUE TITLE
Custom name template is failing to load 

### ISSUE THREAD

**Issue by drkhemu** [chenxiaolong/BCR#260]
@chenxiaolong 
Hello sir, 
All of a sudden after updating to new version the custom made template is failing to load and it gives files name as per default format

Here by, i am attaching the log file please help me to fix it. 

Thannks

Files 
@
[20230301_160019.603+0530_out_121_customer care.log.txt](https://github.com/chenxiaolong/BCR/files/10860010/20230301_160019.603%2B0530_out_121_customer.care.log.txt)

Here is custom template i used (it use to work previously)
Download : https://we.tl/t-7hPbqJPAF1

**Comment by chenxiaolong** [comment]
I think this is caused by a workaround for slow SAF (Android Storage Access Framework) on some devices (#257). There's nothing wrong with your config file.

I'll look into getting this fixed.

**Comment by chenxiaolong** [comment]
This is fixed by #261 (included in version 1.37).
