### ISSUE TITLE
BCR app not showing up after installing module

### ISSUE THREAD

**Issue by kartikbillimoria** [chenxiaolong/BCR#262]
This is happening on both my Pixel 4 XL and Pixel XL.

Happy to share whatever information is required.

Please advise.

**Comment by chenxiaolong** [comment]
Can you use Magisk's save logs button in the top right corner when flashing the module and upload the log here?

**Comment by kartikbillimoria** [comment]
Here you just flashed the module again and saved the log.

- Copying zip to temp directory
- Installing BCR-1.37(75008).zip
- Current boot slot: _a
- Device is system-as-root
Archive:  /data/user/0/e.yjndokk/cache/flash/install.zip
  inflating: module.prop
*****************
 BCR 
 by chenxiaolong 
*****************
*******************
 Powered by Magisk 
*******************
Archive:  /data/user/0/e.yjndokk/cache/flash/install.zip
  inflating: customize.sh
- Extracting module files
Archive:  /data/user/0/e.yjndokk/cache/flash/install.zip
  inflating: module.prop
  inflating: customize.sh
  inflating: LICENSE
  inflating: README.md
   creating: system/
   creating: system/addon.d/
  inflating: system/addon.d/51-com.chiller3.bcr.sh
   creating: system/etc/
   creating: system/etc/permissions/
  inflating: system/etc/permissions/privapp-permissions-com.chiller3.bcr.xml
   creating: system/priv-app/
   creating: system/priv-app/com.chiller3.bcr/
  inflating: system/priv-app/com.chiller3.bcr/app-release.apk
Using /system as the installation target
- Done

**Comment by supermansaga** [comment]
Didn't work for me on my Pixel 7 Pro which is on Feb 2023 stable build, but did have the latest Play System Update OTA from few days ago that I have forgot to install Magisk 25209 to inactive slot for. Maybe 25209 is now corrupted by the latest update? https://www.xda-developers.com/google-play-system-update-march-2022-play-games-services-privacy-settings/

**Comment by chenxiaolong** [comment]
Thanks for the logs. I believe this is a bug in the latest debug/canary builds of Magisk. It's already been fixed by https://github.com/topjohnwu/Magisk/commit/4709a326419a51233a2e7113a3f4f8acd7ecdb8f, but a new release has not been made yet.

In the meantime, you'll have to downgrade Magisk.

**Comment by JHNBOS** [comment]
I had the same problem on my Pixel 7 Pro. I upgraded Magisk to v26(latest canary), and BCR is working again.
