### ISSUE TITLE
Failed to Record call; internal component

### ISSUE THREAD

**Issue by K-plus69** [chenxiaolong/BCR#265]
![Screenshot_20230313-195320~2.png](https://user-images.githubusercontent.com/90862487/224801848-eec6ebdc-3a6d-45e2-873a-ed5b910d25f1.png)

I tried changing the output format settings and it doesn't work in any way.

I have a Huawei P20 lite (ANE-LX1) and use a custom AOSP Android 13 ROM.
Is it possible to get it work, or not?

**Comment by chenxiaolong** [comment]
Thanks for the logs. Unfortunately, call recording won't work with your setup. It's not supported with your device + ROM combination.

(`Unable to retrieve AudioRecord pointer for frameCount()` means there's no Android audio device for capturing call audio.)
