### ISSUE TITLE
caller ID

### ISSUE THREAD

**Issue by Savaturkey** [chenxiaolong/BCR#27]
please    Write the caller ID to the record file name. I'm having trouble distinguishing. It is not clear who is calling.

**Comment by chenxiaolong** [comment]
This was already implemented in version 1.2 :)

**Comment by Savaturkey** [comment]
> lütfen arayan kimliğini kayıt dosya adına yazın. Ayırt etmekte zorlanıyorum. Kimin aradığı belli değ

> Bu zaten 1.2 sürümünde uygulanmıştı :)

I may have misunderstood. Or you misunderstood. I want a caller ID in my phone book to be included in the record name. If it is not registered in my directory, it already writes a phone number.
