### ISSUE TITLE
[Question] Installing by android sideload

### ISSUE THREAD

**Issue by tdas777** [chenxiaolong/BCR#276]
Hi,

Can it be installed using Android sideload in non-root phone (Oneplus9R on custom ROM, Andorid 13)?

I love this project; currently I'm using it, installed by magisk; but due to magisk I'm facing issue with work apps like ms intune.

**Comment by chenxiaolong** [comment]
BCR can be used without Magisk if you flash it from a custom recovery. This only works for custom ROMs that have a writable `system` partition though.

If that won't work with the ROM you're running, then unfortunately, you're out of luck. Call recording can only work when BCR has system app privileges.
