### ISSUE TITLE
Add contact name to filename

### ISSUE THREAD

**Issue by Savaturkey** [chenxiaolong/BCR#28]
I may have misunderstood or you may have misunderstood. I want the name of a person in my phonebook to be in the audio recording file. If it's not in my phonebook it already has a phone number. Did you understand me?
Thank you.

**Comment by chenxiaolong** [comment]
Ah, I see. You'd like the filename to contain the name from the contacts.

I'll investigate and see if it's easy to implement. No promises though :)

**Comment by Savaturkey** [comment]
> Ah, I see. You'd like the filename to contain the name from the contacts.
> 
> I'll investigate and see if it's easy to implement. No promises though :)

Thank You...

**Comment by chenxiaolong** [comment]
This has been implemented in #42 and will be included in the next version of BCR (version 1.5).

The feature can be enabled by going into the Android settings and giving BCR the Contacts permission. Also, this feature requires Android 11 or newer. Older versions of Android do not have the necessary API.

**Comment by greatcoder88** [comment]
> This has been implemented in #42 and will be included in the next version of BCR (version 1.5).
> 
> The feature can be enabled by going into the Android settings and giving BCR the Contacts permission. Also, this feature requires Android 11 or newer. Older versions of Android do not have the necessary API.

Thanks for adding the feature to include contact name in file name based on the contacts permission.
