### ISSUE TITLE
Remove plus from phone number

### ISSUE THREAD

**Issue by Daeamon** [chenxiaolong/BCR#290]
Hello, if filename contains plus symbol as in phone number +79999999999 then i couldn't sync this file to my cloud.
Can you add format feature to phone numbers too?

**Comment by chenxiaolong** [comment]
The next BCR release (version 1.40) will officially support custom filename templates. You'll be able to edit the template and change `{phone_number}` to `{phone_number:digits_only}` to get this behavior.
