### ISSUE TITLE
Google Phone app labels outgoing calls to businesses with the business name; can BCR do the same?

### ISSUE THREAD

**Issue by blackwind** [chenxiaolong/BCR#291]
To my surprise and delight, every single business number I've manually dialed since moving from VoIP to a cell plan has been correctly identified and labelled by Google Phone in my call logs. Is there a way to obtain this information through the telephony framework and apply it to `${caller_name}` when empty, or is this a Phone-exclusive feature with no retrieval interface?

**Comment by chenxiaolong** [comment]
> this a Phone-exclusive feature with no retrieval interface?

This is unfortunately the case. The online lookup process is done entirely within Google Dialer and it doesn't provide that information back to the telephony framework or anywhere else.

**Comment by chenxiaolong** [comment]
Hmm, I didn't think to go at it via the call log API. I'm not very familiar with it, but I wonder if it allows dialer apps to put whatever information they want in it. I'll investigate.

Which third party dialer did you use for testing?

**Comment by blackwind** [comment]
[Simple Dialer](https://play.google.com/store/apps/details?id=com.simplemobiletools.dialer) does the trick.

**Comment by chenxiaolong** [comment]
Thanks! Looks like `CACHED_NAME` is the call log field that Simple Dialer displays for the name and sure enough, AOSP dialer has [some code for updating that](https://cs.android.com/android/platform/superproject/+/android-13.0.0_r41:packages/apps/Dialer/java/com/android/dialer/calllog/CallLogCacheUpdater.java), so I assume Google Dialer does too.

I'm going to finish tackling #288 before coming back to this. If the call log is updated by the time the call reaches the `DISCONNECTING` state, then I'm definitely happy to add this. But if it requires waiting for the call log to update, then I probably won't because the recording process is too closely tied to the lifecycle of the call.

**Comment by chenxiaolong** [comment]
Do you happen to have a test number that I can try calling to trigger Google Dialer's business lookup feature? (I can call numbers in the US or Canada.)

I've tried calling a few random ISP's customer service numbers and even if they trigger the fancy Google Assistant speech recognition thing, the call log only shows the phone number.

**Comment by blackwind** [comment]
Anything you can look up in Google Maps should work. Here's one that just worked for me: 204-269-6548. Note that you need to have the associated option enabled in Phone.

**Comment by blackwind** [comment]
Oh, just saw your edit. I can't call US numbers to confirm, so, Google Maps it is.

**Comment by chenxiaolong** [comment]
Thanks! Any chance you know what the option is?

I looked through my call history for something with a business name, called it again, and the new call log entry only has a phone number.

**Comment by blackwind** [comment]
Settings > Caller ID & spam > See caller and spam ID

**Comment by chenxiaolong** [comment]
Hmm, I already have that enabled. Doesn't seem to work on VoWIFI or cellular.

**Comment by blackwind** [comment]
Bizarre. I just turned it off, tried another grocery store, and it didn't identify it.

**Comment by chenxiaolong** [comment]
Gah, Google must've pushed out a bad update or something. I uninstalled Google Dialer updates and it's working. Installed the update again and it broke.

**Comment by chenxiaolong** [comment]
Well anyway, I have enough logs from a few test calls with the old Google Dialer. It looks like Google Dialer takes anywhere from 100ms to 1200ms to update the call log after the call enters the `DISCONNECTED` state. The new busted Google Dialer still updates the call log, but the name is set to an empty string.

I'm going to make BCR poll every 100ms for up to 2s after the call completes to get the call log name, but only if `{call_log_name}` is in the template and its value must be computed. Crappy solution, but seems to work well enough.
