### ISSUE TITLE
After downloading and opening the project without SHA256 key giving gradle error

### ISSUE THREAD

**Issue by chinmay4github1987** [chenxiaolong/BCR#312]
Namespace not specified. Please specify a namespace in the module's build.gradle file like so:
android {
    namespace 'com.example.namespace'
}

If the package attribute is specified in the source AndroidManifest.xml, it can be migrated automatically to the namespace value in the build.gradle file using the AGP Upgrade Assistant; please refer to https://developer.android.com/studio/build/agp-upgrade-assistant for more information.

**Comment by chenxiaolong** [comment]
BCR already specified `namespace` in the gradle script since version 1.2 last year: https://github.com/chenxiaolong/BCR/commit/5f52fdc8d0f9c5b25a8892a9519d25501f8676f3
