### ISSUE TITLE
App Disappear after update

### ISSUE THREAD

**Issue by ag6ag1** [chenxiaolong/BCR#313]
Phone : xiaomi poco x3 pro
miui 14.0.2, androi 13
miui optimization disabled

last working version 1.39

on both 1.40 and 1.41 even tried them from scratch the app dissappear completely

magisk log attached 

tried to install apk manually from adb/modules the app got installed but not working 

[magisk_log_2023-04-24T16.06.41.log](https://github.com/chenxiaolong/BCR/files/11310729/magisk_log_2023-04-24T16.06.41.log)

**Comment by chenxiaolong** [comment]
> update after some search with BCR-1.41.r6.g11f3106-release.zip problem solved. :sweat_smile:

Great! The changes from that test build will be part of version 1.42.
