### ISSUE TITLE
Is it possible to record calls at their originating volume?

### ISSUE THREAD

**Issue by blackwind** [chenxiaolong/BCR#317]
I just noticed that, when I reduce the volume of a call using the volume buttons on my device, BCR's recording mirrors that reduction -- the person on the other end is quiet on the recording, but I remain just as loud. Obviously less than ideal. Since you're capturing an internal stream, is it possible to capture that stream in its original state, as it arrived over the network, before the output volume adjustment is applied by the mixer?

**Comment by chenxiaolong** [comment]
As far as I'm aware, BCR is already capturing the most unprocessed audio that Android provides. At least on my previous Qualcomm devices, the actual raw audio stream from the IMS connection never leaves the modem firmware. I no longer have any interest in reverse engineering modem things, but I bet the situation is not too different on Pixels.
