### ISSUE TITLE
Date format

### ISSUE THREAD

**Issue by Antoder10** [chenxiaolong/BCR#318]
Hi! I'm trying to format the date like this dd/MM/yyyy @ k:mm:ss

But the output that I get is giving _ instead of / and :

Are those forbidden characters?

**Comment by chenxiaolong** [comment]
Yep, that's right. `/` is not allowed in a filename on Linux/Android because it's used to separate folders in a path (eg. `/sdcard/Recordings/filename.m4a`). `:` is additionally not allowed by Android so that files can be copied to/from Windows, which doesn't support `:`.
