### ISSUE TITLE
Mp3 audio output 

### ISSUE THREAD

**Issue by smiler007** [chenxiaolong/BCR#321]
pls add mp3 audio output support.. and more recording filters like "only unknown numbers", "all numbers except", " record only selected"  etc

**Comment by chenxiaolong** [comment]
I won't be adding MP3 support because BCR relies on Android's builtin encoders and there isn't one for MP3: https://developer.android.com/guide/topics/media/media-formats#audio-formats

For filtering, I'll consider it (but I'm closing this issue since we already have #320 for that).
