### ISSUE TITLE
Version Info under About Section

### ISSUE THREAD

**Issue by cybercool10** [chenxiaolong/BCR#33]
**Suggestion** : Clicking on Version (Under About Section) should take the user directly to the [Release Page](https://github.com/chenxiaolong/BCR/releases)  / fetch the latest version.

If [Readme](https://github.com/chenxiaolong/BCR/tree/84a9723e8c69832bc980461d36a327319fbcb257)  is target then it would be easy if the download page is linked at the top of the Readme. 

![Example](https://user-images.githubusercontent.com/68607944/170576544-d2caefa6-2a49-49ad-9d42-4c3541096276.png)

**Comment by chenxiaolong** [comment]
I added badges to the README, similar to the Magisk one you linked. It'll start showing up after the next release (version 1.6).
