### ISSUE TITLE
Record WhatsApp calls.

### ISSUE THREAD

**Issue by oim37** [chenxiaolong/BCR#340]
30% calls makes by WhatsApp, 10% Skype snd other 60% by mobile operator. Make record for whatsapp too.

**Comment by chenxiaolong** [comment]
Sorry, this is not something that will be implemented in BCR. BCR is heavily tied in with how cellular calls work on Android and cannot handle calls in third party apps. You'll have to use a different call recorder for that.

(Duplicate of #228, #235, #267)
