### ISSUE TITLE
Force close while running in Shamilo whitelist mode

### ISSUE THREAD

**Issue by xtay573269555** [chenxiaolong/BCR#342]
The BCR is running normal in Shamilo's default mode(blacklist). After i switch Shamilo's running mode to whitelist, the BCR cannot working and force close all the time.

When running in Shamilo whitelist mode, no app except granted in magisk can get the root permission. Is BCR require root permission ? I did not find the root permission request record when the BCR running normally in Shamilo's default mode(blacklist).

Following is my env and logs:

```
Environment:
Phone: Pixel 4a
OS version: Android 13
Magisk version: 26.1
Shamilo version: v0.7.1
BCR version: 1.42
```

[DevCheck.txt](https://github.com/chenxiaolong/BCR/files/11450484/DevCheck.txt)

[magisk_log_2023-05-11T17.07.47.log](https://github.com/chenxiaolong/BCR/files/11450485/magisk_log_2023-05-11T17.07.47.log)

[bcr_remove_hard_restrictions.log](https://github.com/chenxiaolong/BCR/files/11450486/bcr_remove_hard_restrictions.log)

**Comment by chenxiaolong** [comment]
I assume you meant Shamiko? I couldn't find anything related to "Shamilo". Shamiko unfortunately isn't open source and I don't plan on reverse engineering it to find out exactly what it does.

If I had to guess, it's probably unmounting BCR's Magisk module directories. The system must be able to read BCR's APK at `/system/priv-app/com.chiller3.bcr/app-release.apk` at all times or else it will crash.

> Is BCR require root permission ? I did not find the root permission request record when the BCR running normally in Shamilo's default mode(blacklist).

BCR itself does not require root so it never requests it. The only reason Magisk is used is to install `/system/etc/permissions/privapp-permissions-com.chiller3.bcr.xml` and `/system/priv-app/com.chiller3.bcr/app-release.apk`

**Comment by xtay573269555** [comment]
Yes, it is Shamiko. I made a typo, I should have put an “k” where the “l” is. 

Thanks for explaining the relationship between BCR and magisk. Since the reason is nothing to do with BCR, I am closing the issue.

**Comment by TLSMars** [comment]
How can I resolve this issue? I would like to use BCR in Shamiko's whitelist mode. Is there any way to grant root permissions to BCR or move its APK and related files to a specific directory? I'm not very familiar with how the root environment works. I look forward to your response. Thank you!
