### ISSUE TITLE
[Discussion] Change in the "Initially Paused" behavior.

### ISSUE THREAD

**Issue by bagarwa** [chenxiaolong/BCR#344]
Hi. After updating to the latest BCR version, I see the "[**Initially Paused**](https://raw.githubusercontent.com/chenxiaolong/BCR/master/app/images/dark.png)" option has been replaced with "**Auto-record rules**". Reading the description there, I want to confirm / clarify a few things.

Can you please help me understand this new [Auto-record rules](https://i.imgur.com/JlAeewZ.jpg) screen?

First two options are greyed out and not tap-able. I'm guessing that's because I didn't grant it contacts permission. (BCR will still work without it, right? I removed "contact name" chip from the file naming template too.)

In this scenario, does "All **_other_** calls" means "all calls", period? (i.e. contacts and unknowns.)
With "all other calls" toggle turned on, am I correct to assume that all calls will be recorded and the recording will be saved? If I don't want some of those recordings, I have to manually go to the recording save location and delete them?

Alternatively, if I turn off this "all other calls" toggle, all calls will  still be recorded during the call but will be deleted when the call ends? If I want to save any recording, I will have an option to click "save recording" option in the BCR menu while the call is ongoing?

Thanks.

**Comment by chenxiaolong** [comment]
Yep! Everything you described is exactly how the app behaves.

> If I don't want some of those recordings, I have to manually go to the recording save location and delete them?

You can mark the recording for deletion (at the end of the call) via the notification too.

In general:

* If auto-record is turned on, the notification will have a delete option
* If auto-record is turned off, the notification will have a restore option
* Switching between delete/restore during the call can be done as many times as needed because the deletion happens only at the end of the call

**Comment by bagarwa** [comment]
Great, thanks.

**Comment by etihwjd** [comment]
No worries, dude.  With the benefit this software brings to me, I'm happy to contribute if it means sorting it out for others. Looks like changing the rules and directory isn't solving the issue though, looks like calls are still failing to record.

I'll have a play and see if I can find a work around to share. 

I'm on A14 Beta 2 on a P6P if that's any help.

**Comment by chenxiaolong** [comment]
Would you mind creating a new issue for the Android 14 issues? I probably won't be installing the Android 14 beta builds on my P7P, but I'd be happy to help troubleshoot.
