### ISSUE TITLE
[REQUEST] widget button that allows recording

### ISSUE THREAD

**Issue by f1-outsourcing** [chenxiaolong/BCR#345]
I know you want to keep things simple, but having a widget button that would just start/stop recording from the microphone would be nice to have. Albeit only for testing the correctly recording of files .

**Comment by chenxiaolong** [comment]
I don't quite understand what you're asking for. Could you explain further?

> having a widget button

What do you mean by widget button? Like a home screen widget?

> start/stop recording from the microphone would be nice to have. Albeit only for testing the correctly recording of files .

Many devices can't support a "test recording" feature. In the best case, Android's audio driver for call recording just doesn't produce any data. In the worst case, it just crashes.

The best way to test that I've found is to call the voicemail number.

**Comment by f1-outsourcing** [comment]
> What do you mean by widget button? Like a home screen widget?

Yes, 
![1](https://github.com/chenxiaolong/BCR/assets/13450219/d1c8cf4f-b1be-4909-bced-8d4c91cf8ece)
![2](https://github.com/chenxiaolong/BCR/assets/13450219/4693cf6e-b903-403b-86b1-16883025f0be)

**Comment by f1-outsourcing** [comment]
> Many devices can't support a "test recording" feature. In the best case, Android's audio driver for call recording just doesn't produce any data. In the worst case, it just crashes.
> 
> The best way to test that I've found is to call the voicemail number.

Also not with root access? I was using boldbeast recorder, but it does not seem to work on the tablet (newer android). On this older android boldbeast has option to select 10 audio sources, also alsa ones.

**Comment by chenxiaolong** [comment]
Thanks for clarifying. I probably won't be adding a widget for immediately starting a recording given how buggy the drivers are. It wouldn't work on most devices.

> Also not with root access? I was using boldbeast recorder, but it does not seem to work on the tablet (newer android). On this older android boldbeast has option to select 10 audio sources, also alsa ones.

BCR doesn't use root access (Magisk is just for installing BCR as a system app), but root access wouldn't really help. The issues are at the kernel or even modem firmware level.
