### ISSUE TITLE
Cannot access the default directory (invisible)

### ISSUE THREAD

**Issue by superuser7777** [chenxiaolong/BCR#366]
Tap the output directory to close the BCR app.
I checked with termux, `/sdcard/android/data/com.chiller3.bcr/` does not exist or is hidden.
I've looked into past issues, is this a phenomenon specific to MIUI?

When recording is finished, toast appears and when I specify the app to play it, it plays without problems, but I am unable to access the save folder.
Permissions, settings and automatic recording are working fine.

root magisk install
MIUI.eu 14.0.19.0 stable

```
- Copying zip to temp directory
- Installing BCR-1.46-release.zip
Magisk version: 26100
- Current boot slot: _a
- Device is system-as-root
Archive:  /data/user/0/tdnbr.i/cache/flash/install.zip
  inflating: module.prop
*****************
 BCR 
 by chenxiaolong 
*****************
Archive:  /data/user/0/tdnbr.i/cache/flash/install.zip
*******************
 Powered by Magisk 
*******************
- Extracting module files
Archive:  /data/user/0/tdnbr.i/cache/flash/install.zip
  inflating: module.prop
  inflating: boot_common.sh
  inflating: post-fs-data.sh
  inflating: service.sh
  inflating: LICENSE
  inflating: README.md
   creating: system/
   creating: system/addon.d/
  inflating: system/addon.d/51-com.chiller3.bcr.sh
   creating: system/etc/
   creating: system/etc/permissions/
  inflating: system/etc/permissions/privapp-permissions-com.chiller3.bcr.xml
   creating: system/priv-app/
   creating: system/priv-app/com.chiller3.bcr/
  inflating: system/priv-app/com.chiller3.bcr/app-release.apk
- Done
```

**Comment by chenxiaolong** [comment]
This isn't specific to MIUI. Unfortunately, as of Android 12, access to `/sdcard/Android/data/` is no longer allowed in 3rd party apps. You can still access them via a computer over USB.

To access the files from the phone itself, you have to use DocumentsUI. DocumentsUI is Android's built-in file picker, which is different from the default Files app. On AOSP and less customized Android ROMs, you can access it from Settings -> Storage -> Documents & other. If MIUI doesn't have that, you can use https://play.google.com/store/apps/details?id=com.marc.files, which is just a shortcut to open DocumentsUI.

Alternatively, you can just use a file manager that supports root.

I would suggest using a custom output directory in the future to avoid trouble in accessing the files.

**Comment by superuser7777** [comment]
solved.
Thank you so so much!!

@chenxiaolong pointed out, I was able to browse the directory using the OS standard files.app.
It was caused by disabling the OS standard files.app because it was a behavior that started the application without permission in the background.

This is a FAQ suggestion.

```
Q:If you choose to change the default directory, the app exits.
A:To access the files from the phone itself, you have to use DocumentsUI.
This is not a problem with the BCR. and, It's also not an OS-specific issue.

DocumentsUI is Android's built-in file picker, which is different from the default Files app. On AOSP and less customized Android ROMs, you can access it from Settings -> Storage -> Documents & other. If MIUI doesn't have that, you can use https://play.google.com/store/apps/details?id=com.marc.files, which is just a shortcut to open DocumentsUI.

Alternatively, you can just use a file manager that supports root.

I would suggest using a custom output directory in the future to avoid trouble in accessing the files.
```

**Comment by chenxiaolong** [comment]
Great, thanks for reporting back!
