### ISSUE TITLE
Ver: 1.46 - format issue

### ISSUE THREAD

**Issue by tdas777** [chenxiaolong/BCR#367]
I have selected m4a/aac as recording format, but all my call recordings are saved with mp3 extension.

General
Complete name               : E:\********************.mp3
Format                      : MPEG-4
Format profile              : Base Media / Version 2
Codec ID                    : mp42 (isom/mp42)
File size                   : 13.0 KiB
Duration                    : 3 s 280 ms
Overall bit rate mode       : Constant
Overall bit rate            : 32.4 kb/s
Encoded date                : UTC 2023-07-02 15:45:16
Tagged date                 : UTC 2023-07-02 15:45:16
com.android.version         : 13
com.android.manufacturer    : OnePlus
com.android.model           : LE2101
FileExtension_Invalid       : braw mov mp4 m4v m4a m4b m4p m4r 3ga 3gpa 3gpp 3gp 3gpp2 3g2 k3g jpm jpx mqv ismv isma ismt f4a f4b f4v

Audio
ID                          : 1
Format                      : AAC LC SBR
Format/Info                 : Advanced Audio Codec Low Complexity with Spectral Band Replication
Commercial name             : HE-AAC
Format settings             : NBC
Codec ID                    : mp4a-40-5
Duration                    : 3 s 280 ms
Source duration             : 3 s 323 ms
Source_Duration_LastFrame   : 37 ms
Bit rate mode               : Constant
Bit rate                    : 24.0 kb/s
Channel(s)                  : 1 channel
Channel layout              : C
Sampling rate               : 48.0 kHz
Frame rate                  : 23.438 FPS (2048 SPF)
Compression mode            : Lossy
Stream size                 : 9.71 KiB (75%)
Source stream size          : 9.71 KiB (75%)
Title                       : SoundHandle
Language                    : English
Encoded date                : UTC 2023-07-02 15:45:16
Tagged date                 : UTC 2023-07-02 15:45:16
mdhd_Duration               : 3280

**Comment by chenxiaolong** [comment]
> Format : MPEG-4
> ...
> Commercial name : HE-AAC

It looks like the actual file format is AAC, but the file extension is wrong. Can you enable debug mode by long pressing BCR's version number, make a call, and then upload the log file that gets created in the output directory?

I suspect this is a bug in the Android ROM you're using though. Android is responsible for determining the file extension, not BCR.

**Comment by tdas777** [comment]
PFA log
[20230703_024932.006+0530_out_198.log[1].txt](https://github.com/chenxiaolong/BCR/files/11931503/20230703_024932.006%2B0530_out_198.log.1.txt)

**Comment by chenxiaolong** [comment]
Thanks for the logs. This might actually be a BCR bug. I'm looking into it now.

**Comment by chenxiaolong** [comment]
This is fixed in #368, which will be included in version 1.47.

For your existing recordings, you can just manually rename them from `.mp3` back to `.m4a` since the file contents is already a valid M4A/AAC file.

**Comment by tdas777** [comment]
Thanks. Love this project <3
