### ISSUE TITLE
Date format give wrong monthly number

### ISSUE THREAD

**Issue by lavoie005** [chenxiaolong/BCR#386]
Hi and thx for that awesome app.
I dont know what happen but now when i record date format i recive bad month
Format is [{phone_number} |r][[{contact_name} |{caller_name} |{call_log_name}] |]{date:dd-mm-yyyy@k'h'mm(XXX zzzz)}[-{direction}|]

Date i recive for july 21 2023 is
21-59-2023

The month change each time
I recive 57, 58 and last one is 59

Any idea what happen?

Thx in advance

**Comment by chenxiaolong** [comment]
Looking at https://developer.android.com/reference/java/time/format/DateTimeFormatterBuilder#appendPattern(java.lang.String), I think you want to use uppercase `MM`. Lowercase `mm` is for the minute.

**Comment by lavoie005** [comment]
you are some awesome, that work perfectly, thank a lot :)
