### ISSUE TITLE
Can not success instalation

### ISSUE THREAD

**Issue by KH0000001** [chenxiaolong/BCR#390]
Pixel 4a5G
Android 13 (TQ2A.230305.008.C1)
Magisk 26.1(26100)
BCR v1.48
I installed by install from storage in Magisk app. But I can't see in superuser. 

What should I do in this happening?

I did the below
- Update v1.38->v1.48 (Because I looked up for didn't move BCR)

- Restart my phone
- Remove BCR app

**Comment by chenxiaolong** [comment]
Can you explain a bit more about what's happening?

It's normal for BCR to not show up in Magisk's `Superuser` tab because BCR doesn't use root access at all. It only uses the Magisk module to install as a system app.

**Comment by KH0000001** [comment]
It doesn't receive the notifications.

**Comment by chenxiaolong** [comment]
Please grab a logcat right after making a phone call and upload that. (You can either use a logcat app or if you're familiar with adb, `adb logcat -d > logcat.txt`.)

**Comment by KH0000001** [comment]
I don't have trying time now, will do later.
