### ISSUE TITLE
Separation of recording streams (separately yourself and the interlocutor)

### ISSUE THREAD

**Issue by oim37** [chenxiaolong/BCR#405]
Hi, 
I would like to have the opportunity to receive by the end (some option in the settings) 2 files by the end of 1 conversation, separately what I said and separately the interlocutor. That is, to record from a microphone and from a line. Not mixing them like now.

Is it possible?

**Comment by chenxiaolong** [comment]
With #772, which will be included in version 2.0, BCR can now optionally record in stereo for devices that support it. The uplink is recorded to the left channel and the downlink to the right channel. Currently, only newer Google Pixel devices are known to support this.
