### ISSUE TITLE
Feature Request: Add a toggle to split inbound and outbound audio between left and right channel.

### ISSUE THREAD

**Issue by Warrentheo** [chenxiaolong/BCR#409]
Feature Request: Add a toggle to split inbound and outbound audio between left and right channel.  Just allow microphone to record to left channel, and speaker to record to the righthand side.  Makes the audio easier to understand.

I think this software is very cool, so thank you in advance no matter the direction chosen :-D

**Comment by chenxiaolong** [comment]
Glad you're enjoying BCR!

I would very much like to add this feature, but currently there's no device that actually supports this (more details in #124). If any new future devices support stereo recording, I'll definitely add support for it.

**Comment by chenxiaolong** [comment]
With #772, which will be included in version 2.0, BCR can now optionally record in stereo for devices that support it. The uplink is recorded to the left channel and the downlink to the right channel. Currently, only newer Google Pixel devices are known to support this.
