### ISSUE TITLE
Feature Request: Enable a +/- DB setting for the Microphone.

### ISSUE THREAD

**Issue by Warrentheo** [chenxiaolong/BCR#410]
Feature Request: Enable a +/- DB setting for the Microphone.  This would only need to be used to get the audio level for the microphone to more closely match up with the speaker volume.  A similar setting for the speaker is not needed since that is already controlled by the normal volume controls.

**Comment by chenxiaolong** [comment]
Sorry, adjusting the volume for just one side of the call isn't possible on any device I'm aware of. There's no way to tell the difference between the two sides of the call--they're merged by Android's audio driver before it reaches BCR.

You might be able to work around this by messing with the mixer config files using root, but I don't have any personal experience with doing that.

(More details in #124)

**Comment by chenxiaolong** [comment]
With #772, which will be included in version 2.0, BCR can now optionally record in stereo for devices that support it. The uplink is recorded to the left channel and the downlink to the right channel. Currently, only newer Google Pixel devices are known to support this.

While BCR does not support automatically increasing the volume, with an external tool like Audacity, it is possible to edit the audio of a stereo recording to boost the volume of one of the two channels.
