### ISSUE TITLE
Don't record calls under 10 seconds

### ISSUE THREAD

**Issue by jbro129** [chenxiaolong/BCR#411]
Would it be possible for an option to added where you can specify an amount of seconds and if a call doesn't reach that length then it won't be saved or it'll be deleted immediately after the call ends.

**Comment by Alex2036** [comment]
@chenxiaolong Can you please tell me why you couldn't add such a necessary option? 
Do you plan to add it in the nearest updates?

**Comment by chenxiaolong** [comment]
Even though the idea is simple, implementing this in a way that doesn't conflict with BCR's autorecord rules is not trivial.

I think it's a good idea, but I don't expect I'll have time to implement it any time soon.

**Comment by chenxiaolong** [comment]
Please give the test build at https://github.com/chenxiaolong/BCR/pull/605#issuecomment-2362648389 a try.

**Comment by Alex2036** [comment]
> Пожалуйста, попробуйте тестовую сборку [#605 (комментарий)](https://github.com/chenxiaolong/BCR/pull/605#issuecomment-2362648389) .

Unfortunately, the tested test assembly records calls immediately after picking up the handset. And the time specified in the options does not fix this.
Is it possible to make sure that calls limited to N - amount of time are not recorded in BCR?

**Comment by chenxiaolong** [comment]
I'm not sure I fully understand what you're saying. It sounds like you're asking for a feature to have a delay the start of the recording? If so, that's not supported.

The feature request from this ticket was for automatically deleting recordings that were shorter than N seconds.

**Comment by Alex2036** [comment]
> Я не уверен, что полностью понимаю, о чем вы говорите. Похоже, вы просите функцию задержки начала записи? Если так, то это не поддерживается.
Yes, it was about that. Thanks for the clarification.
