### ISSUE TITLE
Flashing zip via recovery fails on TWRP (Lineage GSI 19)

### ISSUE THREAD

**Issue by Deathwish98** [chenxiaolong/BCR#415]
Here's the recovery log file -

[recovery.log](https://github.com/chenxiaolong/BCR/files/12484654/recovery.log)

**Comment by chenxiaolong** [comment]
Thanks for the logs. It looks like the problem is that the system partition is mounted as read-write:

```
+ mount -o remount,rw /system_root
```

but writes are still being denied:

```
+ unzip -o /sideload/package.zip system/* -d /system_root
unknown fuse request opcode 2016
Archive:  /sideload/package.zip
unzip: can't open 'system/addon.d/51-com.chiller3.bcr.sh': Read-only file system
```

If you want to stick with your currently ROM, you'll probably have to install BCR as a Magisk module instead.

**Comment by Deathwish98** [comment]
Okay, Thanks.
