### ISSUE TITLE
Recording disabled

### ISSUE THREAD

**Issue by Uj947nXmRqV2nRaWshKtHzTvckUUpD** [chenxiaolong/BCR#417]
Recording disables by itself after a while (the toggle)

Note that i recently updated magisk

**Comment by chenxiaolong** [comment]
Did all of the settings reset or just the call recording toggle? There are two known cases where settings are reset:

* If BCR loses access to the required permissions (eg. microphone), the call recording toggle will be disabled. Some ROMs are very aggressive about this and remove permissions if you don't open the app regularly. There might be an option to disable this behavior in Android's settings (depending on the ROM).
* BCR will lose all of its settings if the ROM is booted once without Magisk being fully installed. (This can't be worked around. Android deletes app data if the app disappears, even for a single boot.)

**Comment by chenxiaolong** [comment]
Thanks for the additional info. It's unfortunate OxygenOS behaves like that. I don't think there's any way BCR can work around that.
