### ISSUE TITLE
[Suggestion] auto delete with condition 

### ISSUE THREAD

**Issue by lavoie005** [chenxiaolong/BCR#421]
Hi, hope you doing good.
Is it possible to add condition for the auto delete folder?
I mean
Keep all recording and
Delete recording after 3 month from this contact, all contact, this number...
Let me know if you dont understand what i'm talking about.
It just because i want to keep all recording except my friend, but other contact like business contact, i want to keep it for ever.
Thank in advance

**Comment by chenxiaolong** [comment]
Thanks for the suggestion. This is currently not something I expect to implement.

To implement this, BCR would need to store and access metadata for past calls. There's no existing feature that requires this and adding it would complicate the code, which I intend to keep as simple as possible.
