### ISSUE TITLE
Need help

### ISSUE THREAD

**Issue by Alatien69** [chenxiaolong/BCR#423]
![Screenshot_20230916-100611_Teléfono](https://github.com/chenxiaolong/BCR/assets/145358677/3453a328-60df-417a-b233-40305e80210b)
I have the same error with all the recording options. Any solution

**Comment by chenxiaolong** [comment]
Any chance you're using a "debloated" ROM? The error means that the Opus audio encoder is missing, but that's been built into Android since Android 10.

You'll probably have to pick a different output file format. (If the ROM is missing all encoders, then your only choice will be `WAV/PCM`.)

**Comment by chenxiaolong** [comment]
You'll probably have to ask the folks who created the ROM you're running. This might help with troubleshooting: https://play.google.com/store/apps/details?id=com.parseus.codecinfo

These are the encoders that are expected to exist:

* OGG/Opus: `c2.android.opus.encoder`
* M4A/AAC: `c2.android.aac.encoder`
* FLAC: `c2.android.flac.encoder`
