### ISSUE TITLE
Enable recording of VoIP apps like Linphone and Fongo.

### ISSUE THREAD

**Issue by Venomtek** [chenxiaolong/BCR#428]
This app is wonderful, I wouldn't be able to live without it!
If it was able to record sip/VoIP apps like Fongo and Linphone, it would be the best thing ever made!

**Comment by Venomtek** [comment]
Sorry, never mind, I just noticed another request and your answer to it.  
Would you be able to recommend another recording app that does support VoIP?

**Comment by Venomtek** [comment]
Sorry, never mind, I just noticed another request and your answer to it.
Would you be able to recommend another recording app that does support VoIP?

**Comment by chenxiaolong** [comment]
Sorry, I don't have any recommendations. I don't personally use any VoIP calling apps, so I haven't looked around to see which call recorders might support them.
