### ISSUE TITLE
Record all

### ISSUE THREAD

**Issue by RV7PR** [chenxiaolong/BCR#429]
Please add back the ability to just record everything like in previous versions.
I dont want to create a rule for each contact or tap keep recording for every call because i will forget it.

**Comment by chenxiaolong** [comment]
That's already the default behavior. If you don't configure any rules, it records everything. If you already changed some rules, just make sure the `All other calls` option is on.

**Comment by RV7PR** [comment]
@chenxiaolong Well thats weird because I never set any rules and it just stopped recording anything from 2023-05-16 after an update probably except for a few days ago because i explicitly used the keep recording in notification.
I never changed any setting nor did i add any rule and my rules were empty

**Comment by RV7PR** [comment]
@chenxiaolong Now i understand the switchers for "Unknown calls" and "All other calls" its very confusing because the description says "Delete the recording when the calls ends" which I thought that when i switch it to ON that it will delete those recordings so i never messed with that but now i see that when you switch it to ON the description changes

**Comment by chenxiaolong** [comment]
Ah, I can definitely see that being confusing. Do you have any suggestions for how to better word the description? (I'm open to making it just static text and not something that changes too.)

**Comment by RV7PR** [comment]
I think the best way is to indeed keep the text static so when the switch is off the recordings will be saved and when the switch is on the recordings will be deleted.
