### ISSUE TITLE
Possibility of Whatsapp Call Record

### ISSUE THREAD

**Issue by Deathwish98** [chenxiaolong/BCR#431]
I do respect the fact that it is a simple SIM call recorder and recording Whatsapp call is not in scope of this app, I just wanted to ask out of curiosity, how much different recording whatsapp call is from recording SIM call and how much effort it would to be fork the repo and add such a functionality ?

**Comment by chenxiaolong** [comment]
It would likely take a significant amount of work. The [recording](https://github.com/chenxiaolong/BCR/blob/master/app/src/main/java/com/chiller3/bcr/RecorderThread.kt) and [encoding](https://github.com/chenxiaolong/BCR/tree/master/app/src/main/java/com/chiller3/bcr/format) components might work with minimal modifications, but the call [detection](https://github.com/chenxiaolong/BCR/blob/master/app/src/main/java/com/chiller3/bcr/RecorderInCallService.kt) and [metadata](https://github.com/chenxiaolong/BCR/blob/master/app/src/main/java/com/chiller3/bcr/output/CallMetadataCollector.kt) components definitely will not.

For phone calls, Android provides an standard API (`InCallService`) for detecting calls and gathering info about them. BCR, Android Auto, and smartwatch companion apps all use this API. For calls in third party apps, you're stuck with doing something hacky using the Accessibility API to detect WhatsApp's in-call UI and scrape the relevant metadata from the screen. It'll likely require changes any time WhatsApp updates their UI. I've never personally used the accessibility API, so I'm not sure if this is difficult or just tedious to do.

**Comment by Deathwish98** [comment]
https://stackoverflow.com/a/49431215/7895283

Could this be of any help in detecting the call state ?

**Comment by chenxiaolong** [comment]
It's a bit of a brute force method, but at first glance, it seems like that could potentially work.

**Comment by Deathwish98** [comment]
Okay, Thanks a lot . :)

**Comment by Turhvjbufv** [comment]
> It's a bit of a brute force method, but at first glance, it seems like that could potentially work.

Any updated?

**Comment by Mesoryb** [comment]
Is it possible to add the ability to start and stop recording manually for VoIP apps, with possibility to select parameters manually?
