### ISSUE TITLE
OnePlus 10 Pro is not recording at all

### ISSUE THREAD

**Issue by Corleone91** [chenxiaolong/BCR#435]
Using Stock dialer app

US version.
Android 13 
Build number: NE2215_13.1..580(EX01)
firmware version: Q_V1_P14

**Comment by chenxiaolong** [comment]
During a call, do you see BCR's notification at all?

If not, can you grab a logcat immediately after a call and upload that here?

**Comment by Corleone91** [comment]
It works now

пн, 2 окт. 2023 г. в 08:42, Andrew Gunnerson ***@***.***>:
