### ISSUE TITLE
Version 1.52 battery optimization cannot be undone

### ISSUE THREAD

**Issue by R44D44** [chenxiaolong/BCR#437]
Version 1.52 battery optimization cannot be undone once it is enabled. not within the app, not by uninstalling it via magisk or twrp, nor by clearing cache+memory. LOS 20/Android 13

**Comment by chenxiaolong** [comment]
This is unfortunately normal behavior. Android only allows apps to request it to be enabled, not disabled.

In version 1.52, if you try to disable it in-app, it should take you to Android's settings page:

[Screenshot_20231002-122458](https://github.com/chenxiaolong/BCR/assets/646253/65941641-c982-4c6b-9d8a-a477aa1ca614)
[Screenshot_20231002-122506](https://github.com/chenxiaolong/BCR/assets/646253/9b95e42a-e869-41e5-84a8-d9641e3dc5a2)

Not every ROM supports this shortcut though. If Android's Settings doesn't automatically open to the correct page, you'll have to manually find the option.

**Comment by R44D44** [comment]
thanx for your swift reply. i tried android settings before, it wouldnt work, so i uninstalled/disabled bcr. when you replied i tried again and it worked in android settings :-)
