### ISSUE TITLE
on my phone BCR cannot record calls 

### ISSUE THREAD

**Issue by Stroov** [chenxiaolong/BCR#445]
so i have used BCR and after 10 sep 23 the app is unable to record any calls i have updated to the latest verison as well 
![Screenshot_20231016-101908](https://github.com/chenxiaolong/BCR/assets/108878153/bc6c865c-d194-4657-aa87-01459d423eac)
BCR gives this error message 
i tried changing the directory and still same bug 
![Screenshot_20231016-103648](https://github.com/chenxiaolong/BCR/assets/108878153/c9f68f1b-c4f0-4620-8930-875b83fb2504)
i have changed the directory twice still this error happens

**Comment by chenxiaolong** [comment]
Do you have any Magisk module that might impact `/sdcard/Android/data`? Not sure why it wouldn't be able to write there--Android does not require any permissions to write to that directory.

(No matter what output directory is selected, BCR always writes to `/sdcard/Android/data/com.chiller3.bcr/files` first and the moves the file when the call ends.)

Also, can you grab a logcat immediately after trying to make a call? Hopefully, it'll have more details about what is going wrong.

**Comment by Stroov** [comment]
> Do you have any Magisk module that might impact `/sdcard/Android/data`? Not sure why it wouldn't be able to write there--Android does not require any permissions to write to that directory.
> 
> (No matter what output directory is selected, BCR always writes to `/sdcard/Android/data/com.chiller3.bcr/files` first and the moves the file when the call ends.)
> 
> Also, can you grab a logcat immediately after trying to make a call? Hopefully, it'll have more details about what is going wrong.

sir i can try logcat that wont be an issue , i think its a pixel os rom issue as another app boost for android had simmilar issues where it was not able to download any pics of vids on the phone 
regarding the modules i have on magisk they are 
shamiko 0.7.3
and universal safety net fix 2.4.0 
[Log_2023-10-16_12-02-13.txt](https://github.com/chenxiaolong/BCR/files/12912923/Log_2023-10-16_12-02-13.txt)

i will try to capture log cat will this work

**Comment by Stroov** [comment]
> Thanks for the logs!
> 
> > i think its a pixel os rom issue as another app boost for android had simmilar issues where it was not able to download any pics of vids on the phone
> 
> I think it might be a ROM issue as well. Looking at the logcat, Android is failing to set up the directory for BCR.
> 
> ```
> 10-16 12:02:21.288   635  3993 E vold    : Failed to set project id on /data/media/0/Android/data/com.chiller3.bcr/: Operation not supported on transport endpoint
> 10-16 12:02:21.289  1728 16030 E StorageManagerService: Failed to fixup app dir for com.chiller3.bcr
> ```
> 
> I see the same error for other apps in the log too, like Telegram and LogcatX (but maybe they still work if they don't need access to `/sdcard/Android/data/`).

i will try and change rom and fingers crossed if this bug gets resolved and will update you in 2-3 days

**Comment by mrrakshi** [comment]
any help please
![Screenshot_2024-02-12-20-23-19-12_54063fc6848ac98a54ce5f2a63661433](https://github.com/chenxiaolong/BCR/assets/17087734/cf0d8a03-409e-4d5c-a32b-03e7a5a45d44)
![Screenshot_2024-02-12-20-21-50-74_b783bf344239542886fee7b48fa4b892](https://github.com/chenxiaolong/BCR/assets/17087734/b4dff37a-5cf9-4336-b165-c8eb3179cfe2)

**Comment by mrrakshi** [comment]
the app show in green is the app BCR

**Comment by chenxiaolong** [comment]
@mrrakshi If you're using KernelSU, Shamiko, or some other root hiding mechanism, please see some other folks' suggestions in https://github.com/chenxiaolong/BCR/issues/486. Otherwise, please open a new issue as it is unrelated to this one.

**Comment by mrrakshi** [comment]
tank you sir 🥰
