### ISSUE TITLE
Call audio is distorted when using a Bluetooth device

### ISSUE THREAD

**Issue by jbro129** [chenxiaolong/BCR#446]
Hello, I am using the most recent version of BCR, I have it installed through Magisk 26.3, and my device is running android 13. I also granted BCR all the permissions.

I have noticed that when I use my Bluetooth earbuds while I'm in a call, the recorded audio just plays static. I have also noticed that when I connect calls to my car through Bluetooth, only my side of the audio records and the recipients audio isn't.

I did some test and I found out that these kind of issues only happen when I'm using a Bluetooth device to capture or playback any audio during a call. For example I called my friend and tried with and without my earbuds. The audio was static when my earbuds were connected and perfectly fine without. 

Does BCR have the capability of recording calls even if using a Bluetooth device with the calls?

Edit: BCR does not display any errors.

**Comment by chenxiaolong** [comment]
Unfortunately, there's not really anything you can do to fix that aside from trying different ROMs. The actual recorded audio is controlled entirely by Android and its audio drivers. Some devices handle bluetooth out of the box with no known issues (eg. Google Pixels and recent Samsungs running stock firmware), but most other devices have trouble.

Some folks have reported that switching to speakerphone and back might sometimes fix the audio, but that workaround probably won't work on every device.
