### ISSUE TITLE
BCR looses all permissions when updating 

### ISSUE THREAD

**Issue by srt54558** [chenxiaolong/BCR#448]
Hi,
I updated BCR recently for the first time and noticed that nothing is ever recorded since then. I looked up and saw that the app has no permission and the settings were reset. I updated from the GitHub directly.

Device: Pixel 8 pro
ROM: stock Android 14

**Comment by chenxiaolong** [comment]
Can you clarify how the upgrade was installed? Did you flash the new version from Magisk without doing anything else? Also, are you using the official version of Magisk or one of the forks, like Magisk Delta?

I can't reproduce this on my Pixel 8 Pro (also running stock firmware), but I know that Android will wipe BCR's data if the device boots even a single time without BCR's module installed.

**Comment by srt54558** [comment]
> Can you clarify how the upgrade was installed? Did you flash the new version from Magisk without doing anything else? Also, are you using the official version of Magisk or one of the forks, like Magisk Delta?
> 
> I can't reproduce this on my Pixel 8 Pro (also running stock firmware), but I know that Android will wipe BCR's data if the device boots even a single time without BCR's module installed.

So basically I just downloaded the newest BCR release and flashed it directly into the official magisk stable app. That's it. 

I'm not 100% sure if it's because of that update or Android taking away the permission itself. But I don't see one single recording since the update

**Comment by chenxiaolong** [comment]
Got it. Yeah, that's the correct procedure. If all of the settings got reset (including the output directory), then it's very likely Android wiped BCR's data. Unfortunately, unless you happened to grab a logcat immediately after the reboot following the BCR update, there's not much that can be done to troubleshoot this until/unless it happens again.

**Comment by srt54558** [comment]
> Got it. Yeah, that's the correct procedure. If all of the settings got reset (including the output directory), then it's very likely Android wiped BCR's data. Unfortunately, unless you happened to grab a logcat immediately after the reboot following the BCR update, there's not much that can be done to troubleshoot this until/unless it happens again.

Okay thanks for letting me know! I was really curious why something like this happens
