### ISSUE TITLE
[feature-request] Add ability to disable/enable notification after successful recording.

### ISSUE THREAD

**Issue by 2shrestha22** [chenxiaolong/BCR#449]
We generally don't need the recording right after call is finished. Maybe users like me want to disable the notification of successful call recording so we don't need to swipe call recording notification after finishing a call. Or may be user just don't want a notification to appear and want recording in the background.

**Comment by chenxiaolong** [comment]
This is already supported. If you go to Android's Settings -> Apps -> BCR -> Notifications, you can turn each type of notification on or off. To stop the notifications at the end of the call, turn off the `Success alerts` category.
