### ISSUE TITLE
Need Help for Oneplus 10T Rooted Magisk

### ISSUE THREAD

**Issue by MrWolfTv** [chenxiaolong/BCR#452]
Hello, I rooted my oneplus 10t under android 13 with magisk. everything works I was just looking for an application to record calls, I read that it was necessary to extract the zip on OnePlus and install the .apk things done but the application does not record any calls.. And I can't not to install the module via magisk manager it does not detect it like shamiko or other functional modules. Could you help me please ?

**Comment by chenxiaolong** [comment]
> And I can't not to install the module via magisk manager it does not detect it like shamiko or other functional modules.

Can you post more details about this? What errors are you seeing?
