### ISSUE TITLE
wifi calling incomming call recording caller voice not record problem

### ISSUE THREAD

**Issue by subham2002** [chenxiaolong/BCR#461]
i am using samsung device as everyone know that samsung device auto call features not workin wifi calling time there i use BCR but i noticed the when i call someone in wifi call in recording no issu but incomming call is comming there was an issu of recording the caller voice

**Comment by chenxiaolong** [comment]
There's nothing that can be done about this in BCR, unfortunately. Android's system components are completely responsible for what audio gets recorded. It's very likely there's a bug in the drivers or modem firmware. Most devices have driver bugs that interfere with call recording, even on mostly well-behaved devices like Google Pixels. There's not much you can do other than maybe testing different ROMs to see if they work better.
