### ISSUE TITLE
Gsi VoiceCallIn route issue

### ISSUE THREAD

**Issue by Osanosa** [chenxiaolong/BCR#463]
On gsi rom I need to enable "disable voice call in route" to fix echo and calls but calls recordings don't work
![Screenshot_20231126-161432](https://github.com/chenxiaolong/BCR/assets/80209416/1f53ff8a-7b5d-455d-b546-e6360f14d994)

**Comment by chenxiaolong** [comment]
This is expected behavior. The "voice call" audio stream (from the setting you mentioned) is required for call recording to work. That's how the Android system provides the audio to BCR.
