### ISSUE TITLE
The recordings are blank with no sound

### ISSUE THREAD

**Issue by dvhamham** [chenxiaolong/BCR#466]
After version 1.53, all recordings record blank without sound... but version 1.53 works fine.

**Comment by chenxiaolong** [comment]
Sorry, I don't really have any idea why that is happening. The audio recording part of BCR hasn't changed since version 1.40. The only thing that changed between 1.53 and 1.54 is how files are named when dialing via Google Voice.

**Comment by Shihabus-Sakib-Rad** [comment]
The first recording was blank. But subsequent recording is okay in my case. V1.56

**Comment by GuruDev1736** [comment]
can you check the permissions of the application

**Comment by ZombieJesus9000** [comment]
Fresh install here, replicated the issue on a Pixel 8 Pro Build Number UQ1A.231205.015.A1. Only the first generated recording is blank and all subsequent recordings are present and as expected.

**Comment by S-trace** [comment]
> The first recording was blank. But subsequent recording is okay in my case. V1.56

You saved my day! 

This issue happened on my phone too, but onlt first call had no voice, next two test calls are recorded just fine.
