### ISSUE TITLE
Donations how to

### ISSUE THREAD

**Issue by LiAlH4-Tr** [chenxiaolong/BCR#467]
How can I make donations?
Expressing great thanks to all the developers!

**Comment by chenxiaolong** [comment]
Thanks for the kind words and glad you're liking BCR!

I currently do not accept donations. Thank you messages are more than enough :slightly_smiling_face:

**Comment by Willster419** [comment]
I also would love to donate to this project. This has provided me more then enough usage to consider donating. I want to help support it!
