### ISSUE TITLE
Recoding not working on latest qpr beta on pixel fold

### ISSUE THREAD

**Issue by hubono** [chenxiaolong/BCR#471]
Hi
I updated to latest qpr.
First i jad zygist problems which i managed by installing the latest commited magisk release. I then reinstalled bcr because recording stopped working. Even after reinstall it doesnt work. Im on bcr 1.56

**Comment by chenxiaolong** [comment]
Please explain what you see in more detail. Does BCR show up and does the app open?

**Comment by hubono** [comment]
The app opens if i open it. I made sure all the permissions are granted for the app. 
Before usually after a call i would get a notification that the recording was completed, now i get nothing.

**Comment by hubono** [comment]
I tried removing bcr from magisk and uninstalling the app and reboot. 
When i reflash the module again after removing everything, the app doesnt get installed and i have to go into the zip and extract the apk and install it manually

**Comment by chenxiaolong** [comment]
> When i reflash the module again after removing everything, the app doesnt get installed and i have to go into the zip and extract the apk and install it manually.

Thanks for testing that. This is very likely to be the issue. If the app doesn't show up with just the Magisk module, that also means it's not getting the system permissions needed for call recording.

Can you save the logs from Magisk's logs tab and upload it here? Hopefully that will have more information about why it's not working.

**Comment by hubono** [comment]
Hi
Got an update for magisk and the issue was fixed.
Cheers
