### ISSUE TITLE
BCR not working with Kitsune Mask 26403, keeps crashing

### ISSUE THREAD

**Issue by kartikbillimoria** [chenxiaolong/BCR#479]
BCR not working with Kitsune Mask 26403, keeps crashing

What information can I provide to help resolve this issue, tried on both my Pixel 7 and Pixel 8 Pro, same issue.

**Comment by chenxiaolong** [comment]
Please see https://github.com/chenxiaolong/BCR/issues/470#issuecomment-1853879310. The crash is caused by these custom Magisk builds blocking the Android system's access to BCR's apk.
