### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by Dimon-015** [chenxiaolong/BCR#482]
The application crashes completely after installing the module and rebooting.  The application weighs 0 KB.  This is how it is shown in the system.  here are the logs.
[com.chiller3.bcr_2023-12-31T04_15_03.892.log](https://github.com/chenxiaolong/BCR/files/13799909/com.chiller3.bcr_2023-12-31T04_15_03.892.log)

**Comment by chenxiaolong** [comment]
> The application weighs 0 KB

Are you using Magisk Delta/Alpha/Kitsune or any module that tries to hide root? This kind of issue usually happens when the Android system can't access BCR's apk due to things being hidden.

**Comment by Dimon-015** [comment]
> > The application weighs 0 KB
> 
> Are you using Magisk Delta/Alpha/Kitsune or any module that tries to hide root? This kind of issue usually happens when the Android system can't access BCR's apk due to things being hidden.

Kitsune Mask

**Comment by Dimon-015** [comment]
> > The application weighs 0 KB
> 
> Are you using Magisk Delta/Alpha/Kitsune or any module that tries to hide root? This kind of issue usually happens when the Android system can't access BCR's apk due to things being hidden.

will you fix this?))

**Comment by chenxiaolong** [comment]
This can't be fixed in BCR. Please see https://github.com/chenxiaolong/BCR/issues/470#issuecomment-1853879310 for a workaround that folks have discovered.

**Comment by Dimon-015** [comment]
> This can't be fixed in BCR. Please see [#470 (comment)](https://github.com/chenxiaolong/BCR/issues/470#issuecomment-1853879310) for a workaround that folks have discovered.

Yes, indeed, it works now.  but the size of the application itself remains 0 KB.
