### ISSUE TITLE
Ask to record call's !

### ISSUE THREAD

**Issue by Djmahdi0098** [chenxiaolong/BCR#484]
We don't need Recording All Call's, if can add Bubble or check to Rec on Screen, it's can be helpful.

**Comment by chenxiaolong** [comment]
This is possible already. To default to not recording, go to BCR -> Auto-record rules and turn off all the checkboxes. Then, during a call, you can decide to keep a recording via BCR's notification.

Even if you decide to keep the recording during the middle of the call, BCR will still save the audio of the whole call.
