### ISSUE TITLE
Not working with KernelSu

### ISSUE THREAD

**Issue by Snehdeep0011** [chenxiaolong/BCR#486]
Hello Sir, really thanks for your great work. I was using BCR call recorder in my Moto G54 5g which was rooted with magisk and it was flawless. But when I rooted with KernelSu the module installation was successful. No error there. But app icon and name was com.android.chillar something like that and after giving root permission from KernelSu also the recording is not working. Tried different formats also. Attaching crash logs here.
Thanks in advance Sir. Really appreciate your support.
[crash.log.txt](https://github.com/chenxiaolong/BCR/files/13877721/crash.log.txt)
[crash.log (3).txt](https://github.com/chenxiaolong/BCR/files/13877723/crash.log.3.txt)
[crash.log (2).txt](https://github.com/chenxiaolong/BCR/files/13877724/crash.log.2.txt)
[crash.log (1).txt](https://github.com/chenxiaolong/BCR/files/13877725/crash.log.1.txt)

**Comment by AlirezaParsi** [comment]
its not working for me too 
Ksu a14

**Comment by chenxiaolong** [comment]
Thanks for the logs. It looks like the system is unable to access BCR's icon from its apk. There isn't really anything I can do to fix that. It's almost always caused by some feature that tries to hide root access.

You already gave BCR root access, which normally fixes this problem. The only suggestion I have is to make sure you don't have anything else installed that tries to hide root. The Shamiko module, for example, is known to cause issues.

**Comment by dvirbe** [comment]
I had the same problem, what worked for me was install via recovery and not via kernalSu

**Comment by Snehdeep0011** [comment]
Sir but call recorder by skvalex is working. Is BCR works different than that?

**Comment by TechExhibeo** [comment]
thanks to @dvirbe workaround.
KSU users without shamiko or any other root hide modules can just install apk from zip which fixed crash for me including package name as app name like OP

**Comment by HamiltonUtilities** [comment]
I extracted app-release.apk from BCR-1.61-release.zip, installed it first. In KSU manager I saw it showing up as "Unmount", granted it root and then flashed the BCR-1.61-release.zip. After rebooting, I can see the icon showing up correctly and call recording processing fine too.

**Comment by Snehdeep0011** [comment]
> I extracted app-release.apk from BCR-1.61-release.zip, installed it first. In KSU manager I saw it showing up as "Unmount", granted it root and then flashed the BCR-1.61-release.zip. After rebooting, I can see the icon showing up correctly and call recording processing fine too. I have Shamiko installed along with PIF through ZygiskNext.

Can you share apk file please?

**Comment by cocoderss** [comment]
as @TechExhibeo mentioned, all you need to do if you are using KernelSu is:
1 - Flash BCR zip with KernelSu
2- Extract the zip file, and browse to `system/priv-app/com.chiller3.bcr` there you will find a file `app-release.apk`. 
3- Install the apk (it will prompt you to update).
4- Reboot

That should get the issue solved.

**Comment by pbanj** [comment]
Just tell ksu to show system apps if you can't see bcr in it
