### ISSUE TITLE
Add BCR to Magisk Alt Repo or Androidacy Repo

### ISSUE THREAD

**Issue by dreamflasher** [chenxiaolong/BCR#487]
I'd appreciate a lot if you would add BCR to 
https://github.com/Magisk-Modules-Alt-Repo
or
https://www.androidacy.com/magisk-modules-repository/
so that we can receive auto updates via Androidacy [MagiskModuleManager](https://github.com/Androidacy/MagiskModuleManager) (AMM).

With the added benefit of more users noticing your awesome work!

**Comment by chenxiaolong** [comment]
Thanks for the suggestion. I currently don't plan on publishing releases anywhere else. I prefer to only have a single place where releases are uploaded.

It's not as convenient as with the app you're using, but BCR also supports updating directly from the Magisk app (using the `Update` button next to the module).
