### ISSUE TITLE
Unable to retrieve AudioRecord pointer for frameCount();

### ISSUE THREAD

**Issue by CelularBat** [chenxiaolong/BCR#488]
My phone is Samsung Galaxy 7 with LineageOS 19. (rooted)

I've installed BCR via magisk. The odd thing it's not listed on Superuser list, it didn't want root access at all.

I'm getting a message that it failed to record a phone call, it was an error in internal Android component (android.media.AudioRecord.native_get_buffer_size_in_frames).

Unable to retrieve AudioRecord pointer for frameCount();

**Comment by chenxiaolong** [comment]
Unfortunately, there's probably not much you can do. That error shows up when the ROM doesn't support call recording. This is very common with custom ROMs on Samsung devices.

> The odd thing it's not listed on Superuser list, it didn't want root access at all.

This is normal. BCR uses Magisk's module functionality just for installing as a system app. It doesn't actually require root permissions to work--only system permissions.
