### ISSUE TITLE
Voip call 

### ISSUE THREAD

**Issue by rahulary** [chenxiaolong/BCR#489]
Any way to record WhatsApp calls?

**Comment by chenxiaolong** [comment]
Nope, sorry. BCR is designed completely around Android's telephony framework, which is only used for phone calls. For recording calls in third-party apps, you'll have to use a different call recorder.

(Duplicate of https://github.com/chenxiaolong/BCR/issues/228, https://github.com/chenxiaolong/BCR/issues/235, https://github.com/chenxiaolong/BCR/issues/267, https://github.com/chenxiaolong/BCR/issues/340, https://github.com/chenxiaolong/BCR/issues/341, https://github.com/chenxiaolong/BCR/issues/355)
