### ISSUE TITLE
Not able to build magisk zip

### ISSUE THREAD

**Issue by pakhranijatin97** [chenxiaolong/BCR#495]
* What went wrong:
A problem occurred configuring root project 'BCR'.
> Could not resolve all files for configuration ':classpath'.
   > Could not resolve com.android.tools.build:gradle:8.1.3.
     Required by:
         project : > com.android.application:com.android.application.gradle.plugin:8.1.3
      > No matching variant of com.android.tools.build:gradle:8.1.3 was found. The consumer was configured to find a library for use during runtime, compatible with Java 8, packaged as a jar, and its dependencies declared externally, as well as attribute 'org.gradle.plugin.api-version' with value '8.4' but:
          - Variant 'apiElements' capability com.android.tools.build:gradle:8.1.3 declares a library, packaged as a jar, and its dependencies declared externally:
              - Incompatible because this component declares a component for use during compile-time, compatible with Java 11 and the consumer needed a component for use during runtime, compatible with Java 8
              - Other compatible attribute:
                  - Doesn't say anything about org.gradle.plugin.api-version (required '8.4')
          - Variant 'javadocElements' capability com.android.tools.build:gradle:8.1.3 declares a component for use during runtime, and its dependencies declared externally:
              - Incompatible because this component declares documentation and the consumer needed a library
              - Other compatible attributes:
                  - Doesn't say anything about its target Java version (required compatibility with Java 8)
                  - Doesn't say anything about its elements (required them packaged as a jar)
                  - Doesn't say anything about org.gradle.plugin.api-version (required '8.4')
          - Variant 'runtimeElements' capability com.android.tools.build:gradle:8.1.3 declares a library for use during runtime, packaged as a jar, and its dependencies declared externally:
              - Incompatible because this component declares a component, compatible with Java 11 and the consumer needed a component, compatible with Java 8
              - Other compatible attribute:
                  - Doesn't say anything about org.gradle.plugin.api-version (required '8.4')
          - Variant 'sourcesElements' capability com.android.tools.build:gradle:8.1.3 declares a component for use during runtime, and its dependencies declared externally:
              - Incompatible because this component declares documentation and the consumer needed a library
              - Other compatible attributes:
                  - Doesn't say anything about its target Java version (required compatibility with Java 8)
                  - Doesn't say anything about its elements (required them packaged as a jar)
                  - Doesn't say anything about org.gradle.plugin.api-version (required '8.4')

**Comment by chenxiaolong** [comment]
Which version of Java are you building with? BCR requires version 17, but it seems like you might be using version 8.

https://github.com/chenxiaolong/BCR/blob/e77000383c5b610464568feea8203aac96fa5139/app/build.gradle.kts#L189-L195

**Comment by pakhranijatin97** [comment]
<img width="1440" alt="Screenshot 2024-02-09 at 10 16 19 AM" src="https://github.com/chenxiaolong/BCR/assets/36292794/62e16af7-7337-4004-8de4-b8cad10a5ae3">

Using version 17 of Java to build but it still fails.

**Comment by chenxiaolong** [comment]
Can you post the new error message you get? If it's correctly picking up that setting, it should no longer say:

```
The consumer was configured to find a library for use during runtime, compatible with Java 8
```

**Comment by pakhranijatin97** [comment]
Still getting the same issue while building magisk zip. Other than that project is working fine. Anything else I can try?

**Comment by chenxiaolong** [comment]
Are you building the magisk zip on the command line (vs. Android Studio)? Maybe the Java version used on the command line is different. You can check with `java -version`.
