### ISSUE TITLE
Internet Calls

### ISSUE THREAD

**Issue by sameera-madushan** [chenxiaolong/BCR#5]
Great program. It would be great if you can add the functionality of recording internet calls such as whatsapp, viber etc...

**Comment by chenxiaolong** [comment]
It'd be a nice feature, but unfortunately, I won't be adding support for it at this time. As far as I'm aware, there's no generic way to detect when audio calls occur in third party apps. Other call recorder apps have to add workarounds for each third party app (eg. WhatsApp) that they want to support.

If Android ever has a decent API for detecting these calls (and their corresponding audio streams), I may consider adding support for it.

**Comment by turb1te** [comment]
Hi, @chenxiaolong! 🙂 I'm not familiar with these things, but would you look at the following links if they would be useful:

* https://stackoverflow.com/questions/49302694/how-do-i-detect-skype-telegram-whatsapp-calls-when-my-messenger-app-is-in-a-call
* https://source.android.com/devices/tech/connect/third-party-call-apps

**Comment by chenxiaolong** [comment]
Hello! Those unfortunately aren't too useful for call recording purposes. AudioManager can tell you the current state of the device (ringing, in call, etc.), but does not tell you when the state changes. It also doesn't tell you which audio stream the 3rd party calling app uses.

The call recorder apps that support VOIP aren't open source, so I'm not 100% sure, but I believe they work by specifically looking for the 3rd party app's activities (eg. WhatsApp's in-call screen) and they hardcode the audio stream that's expected for the app.

**Comment by Ashish393** [comment]
Please added Internet call features, like WhatsApp, Messenger etc. If Don't detected internet call but you can added Users can manually click on a button to turn the record on or off.
