### ISSUE TITLE
Call recording is not functioning properly, after switching from mono to stereo.

### ISSUE THREAD

**Issue by sreejith-1210** [chenxiaolong/BCR#500]
Call recording is functioning on only one channel after switching to CHANNEL_IN_STEREO. It works for 90% of the cases, but in 10% of instances, it fails. After downloading recording, only one side of the sound can be heard.

**Comment by chenxiaolong** [comment]
If BCR produced an audio file for the failing instances, then this is very likely a bug in the audio drivers. BCR encodes every audio sample it receives from the `AudioRecord` without modification. I'm actually quite surprised stereo recording works at all for you--I haven't seen a single device that supports that.

I unfortunately have no suggestions for how to troubleshoot the audio driver. It's not open source for many devices.

**Comment by sreejith-1210** [comment]
private static final int CHANNEL_CONFIG = android.media.AudioFormat.CHANNEL_IN_STEREO

The configuration I modified is functioning well on Samsung A04 and A05; however, it is encountering failures in approximately 10% of cases.

**Comment by chenxiaolong** [comment]
With #772, which will be included in version 2.0, BCR can now optionally record in stereo for devices that support it. The uplink is recorded to the left channel and the downlink to the right channel. Currently, only newer Google Pixel devices are known to support this, but it might work on other devices.
