### ISSUE TITLE
Only records my audio not the other person

### ISSUE THREAD

**Issue by Vaibhav1579** [chenxiaolong/BCR#501]
So basically i install BCR a while ago when I rooted my device it's Realme Narzo 20A based on android 11.Earlier the app worked really fine but recently out of nowhere it started to not work anymore now it just records my audio. I literally didn't even change any kind of setting in the app but it decided to stop working . I am using kitsune mask if that helps to resolve the issue.Also changing the sample rate (hz) seemed to help it but it still was cutting really badly for the other person. I am not using any kind of custom ROM.

**Comment by Vaibhav1579** [comment]
Forgot to mention tried reinstalling the whole module but it didn't help/

**Comment by chenxiaolong** [comment]
It might be worth checking if there were updates to system/built-in apps. Reinstalling/updating Magisk or BCR won't make a difference because the audio stream is controlled entirely by the ROM you're running. BCR doesn't do anything more than saving the exact audio it received from the Android system.

> Also changing the sample rate (hz) seemed to help it but it still was cutting really badly for the other person.

That sounds very much like a buggy audio driver. I have no idea why it would only start happening now though and not before.

**Comment by Vaibhav1579** [comment]
**Update**= I reinstalled the module again and called myself and for some reason it started working again I don't get it. The audio seemed kind of low but I think it was because of the audio I had during calls.

**Comment by Vaibhav1579** [comment]
> It might be worth checking if there were updates to system/built-in apps.
> 
There is not any kind of ROM update for sure as I am using the latest and the last build of my stock ROM.For the i don't have any idea as I didn't download any major app recently according to how I remember. I want to point out one thing recently my kitsune mask automatically uninstalled itself like the app and it had a Android icon when I clicked it, it said click install to download and upgrade to the latest magisk(something like that I don't remember.).But the problem was way before happening with the app this magisk thing happened with me yesterday.

**Comment by Vaibhav1579** [comment]
It stopped working again 😭.

**Comment by Vaibhav1579** [comment]
**Another update**  I started checking my older call recording and noticed when ever I changed my phone to speaker it stopped recording the other person's sound . So I tested it with speaker and guess it literally did yeh exact opposite thing now it records the sounf when it is in loud speaker mode. I hope this helps at any point I don't want any other call recorder as this is the best.

**Comment by Vaibhav1579** [comment]
Hey does this problem has to do something with my battery optimization apps??? I use naptime but then why it suddenly starts working with speaker mode. Also i think it didn't used to work with my phone from the start as i just figured out that since when i installed the app while i received a call i always use to wear my headsets and it used to record them fine. *Sigh* I think something is wrong with my ROM or my drivers is there any way i can change this ??Also i also noticed a really strange behaviour, i was in a call with my default microphone and suddenly after like 5 secs it slowly started picking up the other person's audio. I am really confused sorry for bothering you this much i tried reading all other issues but couldn't find one that is just like me, You can close this issue thanks for the app i really like it 😊.

**Comment by chenxiaolong** [comment]
Glad you like BCR!

> Hey does this problem has to do something with my battery optimization apps???

BCR uses a very reliable mechanism where Android will explicitly start BCR every time a call is answered/placed. Unless the battery optimization app is force stopping BCR, it shouldn't matter at all. (It would be obvious if that was happening because no output file would exist.)

> *Sigh* I think something is wrong with my ROM or my drivers is there any way i can change this ??

Since you're already on the stock ROM, the current setup is already the best you can do. Custom ROMs frequently tend to break call recording instead of fixing issues with it.

**Comment by chenxiaolong** [comment]
Thanks for pointing that out! I did not know Google Assistant had any functionality that would interfere with call recording. I'm sure this will help other folks running into the same issue.
