### ISSUE TITLE
Need to implement this in my code.

### ISSUE THREAD

**Issue by pakhranijatin97** [chenxiaolong/BCR#502]
Hello,

I'm looking to incorporate this into my code. I've copied the files and included them in the Manifest. Could you please guide me on the additional steps required to build the Magisk zip? I attempted to do it manually, but unfortunately, I wasn't successful.

**Comment by chenxiaolong** [comment]
Please post more details about what you've tried or errors you ran into. All of the build logic, including the module zip, are defined in `app/build.gradle.kts`.

---

In general, BCR is probably going to be tough to integrate into another app. It's not really modular enough to be used as a library. (Also, keep in mind that BCR's license means your app must be GPLv3 too.)
