### ISSUE TITLE
Recording not working / crashing app

### ISSUE THREAD

**Issue by grasmanek94** [chenxiaolong/BCR#510]
Hello,

I installed this app yesterday via Magisk onto Samsung S21+ Android 14 (path from february).

For one call it worked, and now when I restarted and try other calls it keeps crashing, and during call it keeps saying "call recording initialized".

[crash.log (7).txt](https://github.com/chenxiaolong/BCR/files/14517006/crash.log.7.txt)
[crash.log (8).txt](https://github.com/chenxiaolong/BCR/files/14517007/crash.log.8.txt)
[crash.log (9).txt](https://github.com/chenxiaolong/BCR/files/14517008/crash.log.9.txt)
[crash.log (10).txt](https://github.com/chenxiaolong/BCR/files/14517009/crash.log.10.txt)
[crash.log (11).txt](https://github.com/chenxiaolong/BCR/files/14517010/crash.log.11.txt)
[crash.log (12).txt](https://github.com/chenxiaolong/BCR/files/14517011/crash.log.12.txt)
[crash.log.txt](https://github.com/chenxiaolong/BCR/files/14517012/crash.log.txt)
[crash.log (1).txt](https://github.com/chenxiaolong/BCR/files/14517000/crash.log.1.txt)
[crash.log (2).txt](https://github.com/chenxiaolong/BCR/files/14517001/crash.log.2.txt)
[crash.log (3).txt](https://github.com/chenxiaolong/BCR/files/14517002/crash.log.3.txt)
[crash.log (4).txt](https://github.com/chenxiaolong/BCR/files/14517003/crash.log.4.txt)
[crash.log (5).txt](https://github.com/chenxiaolong/BCR/files/14517004/crash.log.5.txt)
[crash.log (6).txt](https://github.com/chenxiaolong/BCR/files/14517005/crash.log.6.txt)

I see it can't create a notification? Is the notification so much important? Or is it because of an unsupported codec choice? I tried changing coded but that didn't fix the issue. I changed from working ogg to mp4/aac, then back to ogg but it's still crashing.

**Comment by grasmanek94** [comment]
Awesome, this seems to work!

I don't have many changes, only official samsung rom where bootloader is patched with magisk, 
Modules: play integrity fix (banking apps), liboemcryptodisabler (netflix fix), ssh for magisk

In zygisk mode with deny list enforce (all apps denied except a few that need root).

I also have Automate with a flow that enables do not disturb depending on if I receive too many messages in a short time span, and a flow that checks if microphone is being used, if not restart the service for app 'Echo'.

**Comment by chenxiaolong** [comment]
Great, glad it's working now! It'll likely stay working without any further workarounds when you install BCR updates in the future.

I don't think the issue was caused by any of the things you listed. Root hiding tools that unmount directories (like Shamiko) can cause this sort of thing, but in your case, I'm thinking it's likely a bug in the changes that Samsung made on top of Android.

**Comment by deoxal** [comment]
> Interesting. This has been reported in the past, but usually only on devices like Xiaomi, where they make a ton of changes to Android.
> 
> > I see it can't create a notification?
> 
> It appears to be an issue with displaying the notification icon. Though you said you can see the "call recording initializing" notification? Not sure why Android would complain if the notification is already visible.
> 
> > Is the notification so much important?
> 
> Yep, it's required. Android only allows apps to reliably and continuously run in the background if it shows a notification.
> 
> It might be worth extracting the `.apk` from the Magisk module zip file and then installing that. Other folks who have run into this before have reported that this workaround seems to fix the problem.

I have a Pixel 8a and went from Android 14 to 15 and it stopped working. Installing the apk got it to work though. Thanks for the help.
