### ISSUE TITLE
Not working on Samsung M04

### ISSUE THREAD

**Issue by RockeyDubey** [chenxiaolong/BCR#512]
I have installed via Magisk and granted all permissions, but no recording at all, tried to record WhatsApp call, but no log or nothing. Running android version 12

**Comment by chenxiaolong** [comment]
Sorry, there is no support for WhatsApp calls. Only regular phone calls are supported. For recording calls in third-party apps, you'll have to use a different call recorder.

(Duplicate of https://github.com/chenxiaolong/BCR/issues/228, https://github.com/chenxiaolong/BCR/issues/235, https://github.com/chenxiaolong/BCR/issues/267, https://github.com/chenxiaolong/BCR/issues/340, https://github.com/chenxiaolong/BCR/issues/341, https://github.com/chenxiaolong/BCR/issues/355, https://github.com/chenxiaolong/BCR/issues/489)
