### ISSUE TITLE
No icon in app drawer 

### ISSUE THREAD

**Issue by gerard87** [chenxiaolong/BCR#514]
I see the default app icon in the app drawer instead of the expected one.
In app info settings it shows the proper one.
Android 14, pixel 8 pro.
It's the only app I have with that issue.

![Screenshot_20240314-195007](https://github.com/chenxiaolong/BCR/assets/1914692/d1a102c3-cb06-443a-b7f6-3084da4fac52)
![Screenshot_20240314-195037](https://github.com/chenxiaolong/BCR/assets/1914692/d58f7129-8d1e-4907-80c7-4c2f5b33ae7d)

**Comment by chenxiaolong** [comment]
This is usually caused by root hiding modules, like Shamiko. They sometimes cause Android's system components to not be able to read the icon from BCR's `.apk` (because things are hidden).

Can you list which root solution you're using (Magisk/KernelSU/etc.) and every module you have installed?

**Comment by gerard87** [comment]
You're right, the issue was pixel launcher in deny list. After disabling it and clear launcher data the icon was back. Thank you so much and sorry for the noise.

**Comment by chenxiaolong** [comment]
No worries! Thanks for reporting back.
