### ISSUE TITLE
Where's the apk at?

### ISSUE THREAD

**Issue by rthfhgyhy567** [chenxiaolong/BCR#525]
The readme says I just simply install the module by importing the zip into magisk (I'm running zygisk, whatever that is supposed to mean).  Then restart and open BCR.  There is no app icon but the module is loaded.  I can't find any BCR app even in the package names app.  There is also no apk in the zip folder either, although the readme states otherwise.

Why does EVERYTHING related to GitHub have to be so difficult to install and use?  A better question actually, why is call recordings so taboo that you literally have to void your warranty and root your phone in order to do so?  It should not be up to the software company to make sure that users are following local laws correctly.

Okay I'm done ranting so can I get some help?

**Comment by rthfhgyhy567** [comment]
Here are my modules that I have installed:

BCR v1.62
Detach3 v3.13 by hinxnz
Systemless hosts v1.0 y Magisk
Universal Safetynet Fix v2.4.0-MOD_2.0 by kdrag0n
Zygisk - Lsposed v1.9.2 (7024) by Lsposed

I am running Magisk fdac22ba-delta (25210) with the app version R65C33E4F-Kitsune

After navigating to the folder in your post and installing the APK manually, I was able to get the app installed.  So it seems your instructions may be incorrect because it doesn't say that I have to manually install the apk from that folder.

Now, onto the initial use.  I have enabled call recording in the BCR app and turned off battery optimization but the calls are not being recorded.  Even the Json logs aren't being made to the output folder.  I also don't see any notifications either stating the call is being recorded.  I am using android 13 Samsung S23 SM-9180

**Comment by chenxiaolong** [comment]
I'm guessing Magisk kitsune is likely the issue. Other folks have reported issues using BCR with it in the past. The problem is that it doesn't make all of BCR's files available to the system by default (unlike official Magisk). Someone mentioned that [manually adding BCR to the superuser list](https://github.com/chenxiaolong/BCR/issues/470#issuecomment-1853879310) fixes the problem. I don't have any experience with that personally, so I don't have more detailed instructions.

> Now, onto the initial use. I have enabled call recording in the BCR app and turned off battery optimization but the calls are not being recorded. Even the Json logs aren't being made to the output folder. I also don't see any notifications either stating the call is being recorded. I am using android 13 Samsung S23 SM-9180

Based on this behavior, Android itself is definitely not able to access the module's files. Without those, Android will never notify BCR of calls, so nothing gets recorded or logged.

**Comment by rthfhgyhy567** [comment]
After updating the Magisk app and manually adding BCR to the SUenforce list I was able to get to the point where the BCR notifications display after a call, but it fails to record anything because it can't pick up any audio.

![image](https://github.com/chenxiaolong/BCR/assets/104237805/df68a6a5-b516-4de1-8292-e7837d303f7d)

**Comment by chenxiaolong** [comment]
Ah, that sucks. That means BCR did not receive any actual audio from the audio driver. Looks like Samsung did not implement call recording properly on your device. Stock ROMs usually have the best compatibility for call recording, but if you're already on the stock ROM (or a custom ROM based on it without a lot of "debloating"), then there's probably nothing you can do to get it to work.

**Comment by rthfhgyhy567** [comment]
I fixed it!

I had another module called Firefds kit which has an option to enable the OEM call recording feature (which did nothing btw) which sounds like was competing for the audio.

**Comment by chenxiaolong** [comment]
Oh nice! Thanks for reporting back with the solution. If something else was also trying to record, that would definitely explain it. There is currently no device I'm aware of that allows simultaneous recordings.
