### ISSUE TITLE
Release via F-Droid (repository). 

### ISSUE THREAD

**Issue by RokeJulianLockhart** [chenxiaolong/BCR#531]
Either the primary repository, a reputable 3rd-party repository like IzzyOnDroid, or a self-hosted one.

**Comment by chenxiaolong** [comment]
Sorry, I don't plan on doing that because BCR is not usable without the other files in the Magisk module.

**Comment by RokeJulianLockhart** [comment]
> https://github.com/chenxiaolong/BCR/issues/531#issuecomment-2067872944

@RokeJulianLockhart, for future reference, due to https://github.com/chenxiaolong/BCR/issues/532#issuecomment-2067873314.

**Comment by EvanCarroll** [comment]
@chenxiaolong there are other packages that require magisk too. so long as the requirement isn't to build them but it's the environment to run them -- everything is fine (afaik).
