### ISSUE TITLE
Release APKs directly. 

### ISSUE THREAD

**Issue by RokeJulianLockhart** [chenxiaolong/BCR#532]
https://github.com/chenxiaolong/BCR/releases/download/v1.62/BCR-1.62-release.zip is annoying to deal with, considering https://github.com/ImranR98/Obtainium/issues/983#issue-1937911759 and how `com.android.documentsui` doesn't support archive content extraction.

**Comment by chenxiaolong** [comment]
The zip is meant to be flashed in Magisk. Installing the APK alone is not sufficient for BCR to work.

**Comment by RokeJulianLockhart** [comment]
> https://github.com/chenxiaolong/BCR/issues/532#issuecomment-2067873314

@chenxiaolong, apologies. I neglected to read https://github.com/chenxiaolong/BCR/blob/cd6f307f88bf3581052a1f5e6176d954c6311cb2/README.md?plain=1#L43, thinking that it was worth reading after this issue had been closed.
