### ISSUE TITLE
Unable to Install in Recovery : Samsung S22 Ultra ( United States )

### ISSUE THREAD

**Issue by oliveratutexas** [chenxiaolong/BCR#534]
Hi there, I was attempting to install the call recorder apk. I booted into recovery and then selected apply update from ADB on my recovery screen. I think connected to adb and ran `adb install app-release.apk` but it fails with "footer wrong" and "system verificaiton failed" when verifying the update package. Do you know how I can fix this

**Comment by chenxiaolong** [comment]
Since you mentioned you're on US model S22 Ultra: is your device actually rooted? My understanding was that all US model Samsung phones have locked bootloaders.

Unless you're rooted or have an unlocked bootloader, there's no way to use BCR.
