### ISSUE TITLE
Storage full upto 2TB

### ISSUE THREAD

**Issue by ask9027** [chenxiaolong/BCR#535]
after installing BCR in KernelSu.
storage full upto 2TB
![Screenshot_2024-04-26-10-50-42-067_com miui securitycenter](https://github.com/chenxiaolong/BCR/assets/61283438/87974f07-019f-4449-8c35-76ceb387e4e6)
![Screenshot_2024-04-26-10-50-25-694_com android settings](https://github.com/chenxiaolong/BCR/assets/61283438/b68c0306-fffe-4d7a-afef-10bb32076982)

**Comment by chenxiaolong** [comment]
Please report this to KernelSU. It's likely related to how KernelSU mounts modules from a filesystem image.
