### ISSUE TITLE
[enhancement] Recording rule for contact GROUP

### ISSUE THREAD

**Issue by StanTody** [chenxiaolong/BCR#536]
Hi, dear friend !

I like your app very much - it is the only one, I found working on my device (Samsung S23, A14).

I have a suggestion for an enhancement - it will be great if rules can be set for contact GROUPS too. In that way number of rules may decrease A LOT.

Thanks in advance and easy coding !

**Comment by chenxiaolong** [comment]
Glad you like BCR!

I think this is a good idea. I currently don't have time to implement it, but will likely do so in the future.
