### ISSUE TITLE
Question / Feature: record emergency calls

### ISSUE THREAD

**Issue by ElsAr4e** [chenxiaolong/BCR#537]
As far as I know Android will use the stock / own dialer even if you've changed the default phone calling app AND your device is rooted.

The OS will use its own app anyway?

For example if you make an emergency call using the emergency call button from lock screen and other ways https://www.samsung.com/us/support/answer/ANS00050849/ . (And you can't bypass the Android lock screen)

Can you also use the Basic Call Recorder (BCR) to record emergency calls of all countries?

**Comment by chenxiaolong** [comment]
I don't know the exact answer for this as I (thankfully) have not needed to call emergency services.

The recording aspect of BCR would definitely work. The only thing I'm unsure about is the detection of calls (whether Android even tells BCR that a call is active). BCR's call detection mechanism is the same as what smartwatches and Android Auto use. If emergency calls show up on those devices, then emergency calls should also be detected by BCR.

**Comment by ElsAr4e** [comment]
Can you know if BCR can record emergency calls by reading the source code of Android OS?

--
If the default dialer already has a recording option (on non-rooted Android 10+ phones) you should simply ask the manufactor if it is possible to record a emergency calls using the built-in call recorder? - Especially if it's a modified Android version like EMUI or One UI etc?

**Comment by chenxiaolong** [comment]
> Can you know if BCR can record emergency calls by reading the source code of Android OS?

No, the code is very complicated and it's unfortunately not sufficient. The modem is involved with the recording and that's not open source.

---

Yeah, if a device has a built-in recorder and it supports emergency calls, then BCR should support it too (on those devices).

**Comment by blackwind** [comment]
I can confirm that BCR successfully records emergency calls.

**Comment by chenxiaolong** [comment]
> I can confirm that BCR successfully records emergency calls.

Thanks for confirming! Hopefully it wasn't something too serious.

**Comment by ElsAr4e** [comment]
> I can confirm that BCR successfully records emergency calls.

@blackwind Can you please name the device and the root method (Magisk vs KernelSU) you've been using?

**Comment by blackwind** [comment]
Pixel 7 Pro, Magisk.

**Comment by ElsAr4e** [comment]
> Pixel 7 Pro, Magisk.

Thanks. And the original ROM rooted (NOT for example /e/OS or linage rooted)?

**Comment by blackwind** [comment]
Correct.

**Comment by ElsAr4e** [comment]
@blackwind thank you for your information and sharing your experience with others!

**Comment by blackwind** [comment]
> I can confirm that BCR successfully records emergency calls.

So, I just placed another emergency call on a Pixel 9 Pro XL with Magisk and this time BCR *didn't* record. Different modem? Android 15 this time instead of 14? Changes to BCR in the interim? Whatever the case, it seems this may be hit and miss after all.
