### ISSUE TITLE
Crash on Lineage OS 21

### ISSUE THREAD

**Issue by 2shrestha22** [chenxiaolong/BCR#539]
App does not start at all. It crashes immediately. I have attached log.

[crash.log.txt](https://github.com/chenxiaolong/BCR/files/15213199/crash.log.txt)

BRC: v1.62
Lineage OS: 20
Installation type: System (via flashable zip)

**Comment by chenxiaolong** [comment]
Can you double check that the `/system/etc/sysconfig/config-com.chiller3.bcr.xml` file exists with a root file manager?

It's crashing because Android is denying BCR access to some system APIs. This config file is required to allow that access.

**Comment by 1223421** [comment]
same problem, file /system/etc/sysconfig/config-com.chiller3.bcr.xml exists:

```
$ cat /system/etc/sysconfig/config-com.chiller3.bcr.xml
<?xml version="1.0" encoding="utf-8"?>
<config>
    <hidden-api-whitelisted-app package="com.chiller3.bcr" />
</config>

```

BRC: v1.62
Lineage OS: 21
Installation type: System (via flashable zip)

after first reboot it's work, after second reboot - crash

[crash.log.txt](https://github.com/chenxiaolong/BCR/files/15225527/crash.log.txt)

with 1.61 no problem.

**Comment by twu2** [comment]
same issue (No field SAMPLE_RATE_HZ_MIN) here (integrated with rom, not flash zip).
after flash rom, 1st boot work, but 2nd boot not working.
but sometimes, 1st boot not work, but 2nd boot working.

**Comment by chenxiaolong** [comment]
Please grab a logcat with `adb logcat -d > logcat.txt` after a reboot. (If you're able to grab one for a working boot and one for a non-working boot, even better.)

I don't really have any idea why the issue would be intermittent. Hopefully the logcat will have some indication as to why.

**Comment by 2shrestha22** [comment]
> Can you double check that the `/system/etc/sysconfig/config-com.chiller3.bcr.xml` file exists with a root file manager?
> 
> It's crashing because Android is denying BCR access to some system APIs. This config file is required to allow that access.

Yes there is /system/etc/sysconfig/config-com.chiller3.bcr.xml

**Comment by twu2** [comment]
not working log:
[logcat_not_working.txt](https://github.com/chenxiaolong/BCR/files/15229416/logcat_not_working.txt)

working log:
[logcat_working.txt](https://github.com/chenxiaolong/BCR/files/15229419/logcat_working.txt)

**Comment by chenxiaolong** [comment]
Thanks for the logs. It confirms that the issue indeed is Android denying access to the hidden APIs:

(from `logcat_not_working.txt`)
```
05-07 11:29:50.910 28887 28887 W om.chiller3.bcr: Accessing hidden field Landroid/media/AudioFormat;->SAMPLE_RATE_HZ_MIN:I (max-target-o, reflection, denied)
```

I really have no idea why LineageOS is sometimes not respecting `/system/etc/sysconfig/config-com.chiller3.bcr.xml`. Since you're flashing directly and not using Magisk, the file always exists.

---

This is a total crapshoot, but can you give #541 a try? Test build: [BCR-1.62.r9.g0b843bc-release.zip](https://github.com/chenxiaolong/BCR/files/15242053/BCR-1.62.r9.g0b843bc-release.zip)


It fixes a bug where the sysconfig file is deleted when flashing a LineageOS update without also flashing BCR again. I highly doubt it'll fix this issue though.

**Comment by twu2** [comment]
Using zip file as kernelsu module work fine for me. but integrated to rom might not working.
I found the zip put the files under /system, but integrated to rom put it under /product.
I change it to /system and build the rom again, it seems work fine now.

**Comment by radzix88** [comment]
> Thanks for the logs. It confirms that the issue indeed is Android denying access to the hidden APIs:
> 
> (from `logcat_not_working.txt`)
> 
> ```
> 05-07 11:29:50.910 28887 28887 W om.chiller3.bcr: Accessing hidden field Landroid/media/AudioFormat;->SAMPLE_RATE_HZ_MIN:I (max-target-o, reflection, denied)
> ```
> 
> I really have no idea why LineageOS is sometimes not respecting `/system/etc/sysconfig/config-com.chiller3.bcr.xml`. Since you're flashing directly and not using Magisk, the file always exists.
> 
> This is a total crapshoot, but can you give #541 a try? Test build: [BCR-1.62.r9.g0b843bc-release.zip](https://github.com/chenxiaolong/BCR/files/15242053/BCR-1.62.r9.g0b843bc-release.zip)
> 
> It fixes a bug where the sysconfig file is deleted when flashing a LineageOS update without also flashing BCR again. I highly doubt it'll fix this issue though.

It works for me only after first boot. After second boot it crashes again. LOS 21
[crash.log (7).txt](https://github.com/chenxiaolong/BCR/files/15303495/crash.log.7.txt)
[crash.log (6).txt](https://github.com/chenxiaolong/BCR/files/15303498/crash.log.6.txt)

**Comment by twu2** [comment]
> Using zip file as kernelsu module work fine for me. but integrated to rom might not working. I found the zip put the files under /system, but integrated to rom put it under /product. I change it to /system and build the rom again, it seems work fine now.

still get same error sometimes after this.
but if I got this issue, just install the apk again, then it will work.
so my workaround is: integrated the old version (1.61) to the rom, then install new version (1.62) again

**Comment by twu2** [comment]
> still get same error sometimes after this. but if I got this issue, just install the apk again, then it will work. so my workaround is: integrated the old version (1.61) to the rom, then install new version (1.62) again

still got this sometimes after reboot.
but install apk again will make it work (uninstall it after install still working).
so I use a script to install and uninstall the apk after boot.

**Comment by chenxiaolong** [comment]
@twu2 It sounds like you're building your own ROM. If so, can you give this build a try? [BCR-1.62.r19.gc4346df-release.zip](https://github.com/chenxiaolong/BCR/files/15382659/BCR-1.62.r19.gc4346df-release.zip) (source code: c4346df7db3376f4623fa956c0b0ee03967a4f87) 

This uses an alternative method of allowing access to system APIs. Maybe it'll avoid this OS bug where the sysconfig file is sometimes ignored.

When testing, please don't use any workarounds (like installing the apk as a user app). Also, please delete the sysconfig file because the new method doesn't use it.

**Comment by twu2** [comment]
> @twu2 It sounds like you're building your own ROM. If so, can you give this build a try? [BCR-1.62.r19.gc4346df-release.zip](https://github.com/chenxiaolong/BCR/files/15382659/BCR-1.62.r19.gc4346df-release.zip) (source code: [c4346df](https://github.com/chenxiaolong/BCR/commit/c4346df7db3376f4623fa956c0b0ee03967a4f87))
> 
> This uses an alternative method of allowing access to system APIs. Maybe it'll avoid this OS bug where the sysconfig file is sometimes ignored.
> 
> When testing, please don't use any workarounds (like installing the apk as a user app). Also, please delete the sysconfig file because the new method doesn't use it.

this build work fine for me.
