### ISSUE TITLE
Jumps in recorded file.

### ISSUE THREAD

**Issue by robertio** [chenxiaolong/BCR#54]
Hi, 
Thanks for this project efforts!

Recorded files with (all version including Version 1.6) sounds have random small jumps (sounds like hiccups) 
It seems there is no problem with the BCR-1.4.r3.gaa21633-debug-dump_raw_wave_16kHz.zip you provided in other issue#39.

I have Redmi K30 Pro (Poco F2 Pro) - with LOS 19.1 (Android 12)
Sample file having jumps - errors- in it: 
[sample error from recorded sound ](https://easyupload.io/l01tem)
Original recorded file is 1 minutes 10 sec - this sample is from ~27seconds where the error started, and as you can hear after a 5 seconds sounds good again as it was earlier and after.

**This is the Codec debug info:**
`OMX.qcom.video.encoder.heic:
  - Canonical name: OMX.qcom.video.encoder.heic
  - Is alias: false
  - Is hardware accelerated: true
  - Is software only: false
  - Is vendor: true
  - Supported types:
    - image/vnd.android.heic

OMX.qcom.video.encoder.avc:
  - Canonical name: OMX.qcom.video.encoder.avc
  - Is alias: false
  - Is hardware accelerated: true
  - Is software only: false
  - Is vendor: true
  - Supported types:
    - video/avc

OMX.qcom.video.encoder.h263sw:
  - Canonical name: OMX.qcom.video.encoder.h263sw
  - Is alias: false
  - Is hardware accelerated: true
  - Is software only: false
  - Is vendor: true
  - Supported types:
    - video/3gpp

OMX.qcom.video.encoder.hevc:
  - Canonical name: OMX.qcom.video.encoder.hevc
  - Is alias: false
  - Is hardware accelerated: true
  - Is software only: false
  - Is vendor: true
  - Supported types:
    - video/hevc

OMX.qcom.video.encoder.hevc.cq:
  - Canonical name: OMX.qcom.video.encoder.hevc.cq
  - Is alias: false
  - Is hardware accelerated: true
  - Is software only: false
  - Is vendor: true
  - Supported types:
    - video/hevc

OMX.qcom.video.encoder.mpeg4sw:
  - Canonical name: OMX.qcom.video.encoder.mpeg4sw
  - Is alias: false
  - Is hardware accelerated: false
  - Is software only: false
  - Is vendor: true
  - Supported types:
    - video/mp4v-es

OMX.qcom.video.encoder.vp8:
  - Canonical name: OMX.qcom.video.encoder.vp8
  - Is alias: false
  - Is hardware accelerated: true
  - Is software only: false
  - Is vendor: true
  - Supported types:
    - video/x-vnd.on2.vp8

c2.android.aac.encoder:
  - Canonical name: c2.android.aac.encoder
  - Is alias: false
  - Is hardware accelerated: false
  - Is software only: true
  - Is vendor: false
  - Supported types:
    - audio/mp4a-latm
      - Bitrate range: [8000, 510000]
      - Sample rate ranges: [[8000, 8000], [11025, 11025], [12000, 12000], [16000, 16000], [22050, 22050], [24000, 24000], [32000, 32000], [44100, 44100], [48000, 48000]]
      - Sample rates: [8000, 11025, 12000, 16000, 22050, 24000, 32000, 44100, 48000]

OMX.google.aac.encoder:
  - Canonical name: c2.android.aac.encoder
  - Is alias: true
  - Is hardware accelerated: false
  - Is software only: true
  - Is vendor: false
  - Supported types:
    - audio/mp4a-latm
      - Bitrate range: [8000, 510000]
      - Sample rate ranges: [[8000, 8000], [11025, 11025], [12000, 12000], [16000, 16000], [22050, 22050], [24000, 24000], [32000, 32000], [44100, 44100], [48000, 48000]]
      - Sample rates: [8000, 11025, 12000, 16000, 22050, 24000, 32000, 44100, 48000]

c2.android.amrnb.encoder:
  - Canonical name: c2.android.amrnb.encoder
  - Is alias: false
  - Is hardware accelerated: false
  - Is software only: true
  - Is vendor: false
  - Supported types:
    - audio/3gpp
      - Bitrate range: [4750, 12200]
      - Sample rate ranges: [[8000, 8000]]
      - Sample rates: [8000]

OMX.google.amrnb.encoder:
  - Canonical name: c2.android.amrnb.encoder
  - Is alias: true
  - Is hardware accelerated: false
  - Is software only: true
  - Is vendor: false
  - Supported types:
    - audio/3gpp
      - Bitrate range: [4750, 12200]
      - Sample rate ranges: [[8000, 8000]]
      - Sample rates: [8000]

c2.android.amrwb.encoder:
  - Canonical name: c2.android.amrwb.encoder
  - Is alias: false
  - Is hardware accelerated: false
  - Is software only: true
  - Is vendor: false
  - Supported types:
    - audio/amr-wb
      - Bitrate range: [6600, 23850]
      - Sample rate ranges: [[16000, 16000]]
      - Sample rates: [16000]

OMX.google.amrwb.encoder:
  - Canonical name: c2.android.amrwb.encoder
  - Is alias: true
  - Is hardware accelerated: false
  - Is software only: true
  - Is vendor: false
  - Supported types:
    - audio/amr-wb
      - Bitrate range: [6600, 23850]
      - Sample rate ranges: [[16000, 16000]]
      - Sample rates: [16000]

c2.android.flac.encoder:
  - Canonical name: c2.android.flac.encoder
  - Is alias: false
  - Is hardware accelerated: false
  - Is software only: true
  - Is vendor: false
  - Supported types:
    - audio/flac
      - Bitrate range: [1, 21000000]
      - Sample rate ranges: [[7350, 192000]]
      - Sample rates: null

OMX.google.flac.encoder:
  - Canonical name: c2.android.flac.encoder
  - Is alias: true
  - Is hardware accelerated: false
  - Is software only: true
  - Is vendor: false
  - Supported types:
    - audio/flac
      - Bitrate range: [1, 21000000]
      - Sample rate ranges: [[7350, 192000]]
      - Sample rates: null

c2.android.opus.encoder:
  - Canonical name: c2.android.opus.encoder
  - Is alias: false
  - Is hardware accelerated: false
  - Is software only: true
  - Is vendor: false
  - Supported types:
    - audio/opus
      - Bitrate range: [6000, 510000]
      - Sample rate ranges: [[8000, 8000], [12000, 12000], [16000, 16000], [24000, 24000], [48000, 48000]]
      - Sample rates: [8000, 12000, 16000, 24000, 48000]

c2.android.avc.encoder:
  - Canonical name: c2.android.avc.encoder
  - Is alias: false
  - Is hardware accelerated: false
  - Is software only: true
  - Is vendor: false
  - Supported types:
    - video/avc

OMX.google.h264.encoder:
  - Canonical name: c2.android.avc.encoder
  - Is alias: true
  - Is hardware accelerated: false
  - Is software only: true
  - Is vendor: false
  - Supported types:
    - video/avc

c2.android.h263.encoder:
  - Canonical name: c2.android.h263.encoder
  - Is alias: false
  - Is hardware accelerated: false
  - Is software only: true
  - Is vendor: false
  - Supported types:
    - video/3gpp

OMX.google.h263.encoder:
  - Canonical name: c2.android.h263.encoder
  - Is alias: true
  - Is hardware accelerated: false
  - Is software only: true
  - Is vendor: false
  - Supported types:
    - video/3gpp

c2.android.hevc.encoder:
  - Canonical name: c2.android.hevc.encoder
  - Is alias: false
  - Is hardware accelerated: false
  - Is software only: true
  - Is vendor: false
  - Supported types:
    - video/hevc

c2.android.mpeg4.encoder:
  - Canonical name: c2.android.mpeg4.encoder
  - Is alias: false
  - Is hardware accelerated: false
  - Is software only: true
  - Is vendor: false
  - Supported types:
    - video/mp4v-es

OMX.google.mpeg4.encoder:
  - Canonical name: c2.android.mpeg4.encoder
  - Is alias: true
  - Is hardware accelerated: false
  - Is software only: true
  - Is vendor: false
  - Supported types:
    - video/mp4v-es

c2.android.vp8.encoder:
  - Canonical name: c2.android.vp8.encoder
  - Is alias: false
  - Is hardware accelerated: false
  - Is software only: true
  - Is vendor: false
  - Supported types:
    - video/x-vnd.on2.vp8

OMX.google.vp8.encoder:
  - Canonical name: c2.android.vp8.encoder
  - Is alias: true
  - Is hardware accelerated: false
  - Is software only: true
  - Is vendor: false
  - Supported types:
    - video/x-vnd.on2.vp8

c2.android.vp9.encoder:
  - Canonical name: c2.android.vp9.encoder
  - Is alias: false
  - Is hardware accelerated: false
  - Is software only: true
  - Is vendor: false
  - Supported types:
    - video/x-vnd.on2.vp9

OMX.google.vp9.encoder:
  - Canonical name: c2.android.vp9.encoder
  - Is alias: true
  - Is hardware accelerated: false
  - Is software only: true
  - Is vendor: false
  - Supported types:
    - video/x-vnd.on2.vp9
`

How can i provide debug info to you?

**Comment by chenxiaolong** [comment]
> It seems there is no problem with the BCR-1.4.r3.gaa21633-debug-dump_raw_wave_16kHz.zip you provided in other issue#39.

Hmm, if that's the case, I suspect this is caused by the same issue as in #39. I'm still working on troubleshooting that issue.

By the way, with stable version 1.7, it's possible to select WAV/PCM output + 16kHz so you don't have to use the debug build.

**Comment by chenxiaolong** [comment]
Can you give the test build in #59 a try? I think I may have found the issue :slightly_smiling_face:

**Comment by robertio** [comment]
Yes.
I'll do it in few hours.
Many thanks for your work.
Robert
