### ISSUE TITLE
No option to hide the notification

### ISSUE THREAD

**Issue by xposed73** [chenxiaolong/BCR#542]
There should be an option to not show notifications for recorded calls so that the recording can be done privately without notifying users.

**Comment by chenxiaolong** [comment]
This is already supported, but it needs to be done from Android's Settings -> Apps -> BCR -> Notifications.

The recording in progress, recording complete, and recording error notifications can be individually disabled from there.

**Comment by xposed73** [comment]
Thanks it is working
