### ISSUE TITLE
Crashing of BCR app

### ISSUE THREAD

**Issue by SharmagRit** [chenxiaolong/BCR#546]
Logs: https://bin.kv2.dev/~6649ddae5de7ed6bfdc3acd8
When it was booted with A14 system, then it working fine with 2 to 3 days of usage but after its completely dead automatically.
Hope can u fix it soon.
Thanks

**Comment by chenxiaolong** [comment]
Is BCR installed via Magisk/KernelSU or was it flashed from recovery? If it was flashed from recovery, this is likely https://github.com/chenxiaolong/BCR/issues/539 (I have no idea why the issue happens though.)

**Comment by SharmagRit** [comment]
Like we are using this repo: https://github.com/Chaitanyakm/vendor_bcr
as prebuilt with roms, Does crash logs didn't helped?

**Comment by chenxiaolong** [comment]
Ah, that's the same as #539 then. The crash is because some Android ROMs seem to not always respect the `/system/etc/sysconfig/config-com.chiller3.bcr.xml` config file. I don't have any idea why it happens.

**Comment by SharmagRit** [comment]
Thanks we will try and update you as soon as possible.
