### ISSUE TITLE
unable to change output directory

### ISSUE THREAD

**Issue by tryfonaskam** [chenxiaolong/BCR#557]
hi I recently rooted my phone and installed BCR I got it to record after some troubleshooting but I can't change the output directory. when I click change directory it opens the file manager in the recent tab(doesn't show anything except the 3 dots too left
and the sort by... button)my device is Redmi note 12 pro 5g(ruby)
![Screenshot_2024-06-10-12-54-18-531_com google android documentsui](https://github.com/chenxiaolong/BCR/assets/172261927/401d2e73-3e99-4862-a915-a45ccb506318)

**Comment by chenxiaolong** [comment]
That's really weird. I think you might need to investigate if there's something potentially causing conflicts in your ROM (the file picker is part of Android, not BCR).

(One example of something that's known to cause issues is the MiXplorer Magisk module.)

**Comment by tryfonaskam** [comment]
I did manage to fix this problem I installed a file manager called "mix" it's now working
