### ISSUE TITLE
I don't want see the log.txt file.

### ISSUE THREAD

**Issue by ngothang2805** [chenxiaolong/BCR#559]
Please help me prevent the .txt log file from appearing even though I am not using debug mode ...thank you very much . My device xiaomi android 12 . Miui 14.0.2 .

**Comment by chenxiaolong** [comment]
Please upload one of the log files. When debug mode is turned off, the log file is only created if an error occurs, so there might be something going wrong with the recording process.

**Comment by ngothang2805** [comment]
> Please upload one of the log files. When debug mode is turned off, the log file is only created if an error occurs, so there might be something going wrong with the recording process.

this is my log.txt
[mylog.txt](https://github.com/user-attachments/files/15916629/mylog.txt)
The recording function works fine but I just don't want it to create a log.txt file

**Comment by chenxiaolong** [comment]
Thanks for the logs! It's saving the log because an error occurred: Android is blocking access to the call log even though the permission is granted.

```
06-20 19:44:56.692  7617 12028 E RecorderThread/210: java.lang.SecurityException: Permission Denial: reading com.android.providers.contacts.CallLogProvider uri content://call_log/calls?limit=1 from pid=7617, uid=10216 requires android.permission.READ_CALL_LOG, or grantUriPermission()
```

I think this might be a MIUI bug. You might be able to work around it by going to Android's settings for BCR and denying the call log permission.

**Comment by ngothang2805** [comment]
> Thanks for the logs! It's saving the log because an error occurred: Android is blocking access to the call log even though the permission is granted.
> 
> ```
> 06-20 19:44:56.692  7617 12028 E RecorderThread/210: java.lang.SecurityException: Permission Denial: reading com.android.providers.contacts.CallLogProvider uri content://call_log/calls?limit=1 from pid=7617, uid=10216 requires android.permission.READ_CALL_LOG, or grantUriPermission()
> ```
> 
> I think this might be a MIUI bug. You might be able to work around it by going to Android's settings for BCR and denying the call log permission.

This issue has not been resolved . it is only resolved when I stop granting access to read contacts but there is another problem that the contact name is not displayed

**Comment by chenxiaolong** [comment]
It still happens even if you deny only the call logs permission?

If so, I have no idea how to fix this for MIUI.

**Comment by ngothang2805** [comment]
> Nó vẫn xảy ra ngay cả khi bạn chỉ từ chối quyền ghi nhật ký cuộc gọi?
> 
> Nếu vậy, tôi không biết làm cách nào để khắc phục điều này cho MIUI.
Yes, that's right, as I said above
