### ISSUE TITLE
Does not record unconnected calls / voicemail

### ISSUE THREAD

**Issue by mesvam** [chenxiaolong/BCR#563]
BCR does not start recording until call is successfully connected, and so does not record the beginning of outgoing calls. One important example is calls that go to voicemail sometimes go unrecorded

It would be useful to have an option to also record these "one-sided" conversations, for example, to keep a recording of the voicemail that was sent to another person.

To reproduce: call a non-existent number such as (555) 555-5555, or dial a number that goes to voicemail (only sometimes)

**Comment by chenxiaolong** [comment]
BCR currently only starts recording when Android reports that the call enters the `ACTIVE` state. Calls to non-existent numbers remain in the `DIALING` state until they disconnect.

#564 adds a toggle to start recording as soon as the call enters the `DIALING` state (though it's disabled by default). Please give this test build a try: [BCR-1.65.r2.g2f92c39-release.zip](https://github.com/user-attachments/files/16169596/BCR-1.65.r2.g2f92c39-release.zip)

As for voicemails, please enable debug mode by long pressing BCR's version number, reproduce the problem, and then upload the log file that BCR creates in the output directory. When a call reaches voicemail, the call should always enter the `ACTIVE` state, but it's possible your device's modem has a bug and doesn't do that. The log file will contain details about all the states the call goes through.

I wasn't able to reproduce the problem on my Pixel 8 Pro. I tried 10 times each of having the other party hang up immediately and also just ignoring the call to let it time out and go to voicemail.

**Comment by mesvam** [comment]
Thanks, so much! I could not reliably reproduce the voicemail issue either (I only discovered it when some voicemail recordings seemed missing), but I will try to debug it further
