### ISSUE TITLE
Only the other party's voice is being recorded.

### ISSUE THREAD

**Issue by k15uke** [chenxiaolong/BCR#575]
I am using an Android 13.0 P-UP MODE1 retro2. The security update is from March 5, 2024, and the Google Play system update is from July 1, 2024. I have rooted the device and installed Magisk. When using other voice recorder apps, only my voice is recorded. BCR only records the other party's voice. Even when using only BCR, it only records the other party's voice. Is there a solution for this?

**Comment by chenxiaolong** [comment]
Unfortunately, there's nothing BCR can do about this. The audio that gets recorded depends on your ROM. The modem and audio drivers are responsible for merging your audio and the other party's audio into a single audio stream. BCR (and other voice recorder apps) only receive a single audio stream from Android.
