### ISSUE TITLE
Migrating recordings after every boot.

### ISSUE THREAD

**Issue by Gawd21** [chenxiaolong/BCR#576]
This keeps coming up, but I haven't made any recorded calls, since before the update.  What is it migrating and to where? 
![Screenshot_20240802-113323](https://github.com/user-attachments/assets/959f57fe-e542-4e31-bc90-c74e364a3872)

**Comment by chenxiaolong** [comment]
This is related to version 1.68's new feature that allows recording calls before the device is first unlocked after a reboot. When you unlock the device, it'll move those recordings from BCR's internal directory to your output directory.

This seems like a bug in the ROM though, if the notification is not getting dismissed automatically (Android controls when the notification is shown and dismissed for foreground services). Can you reboot, grab a logcat as soon as possible after the notification appears, and then upload that?
