### ISSUE TITLE
1.69 bug

### ISSUE THREAD

**Issue by TonyK922** [chenxiaolong/BCR#582]
一加12 氧os 14.0.0.830 已root

1.69版本打开bcr app启用通话录音按钮，更改保存目录，更改保存格式，打开禁用电池优化，打开写入metadata

然后关掉app 重新打开 除了打开禁用电池优化的选项外，其他更改全部重置，导致无法正常录音使用。

退回1.65 正常。

谢谢作者！

**Comment by chenxiaolong** [comment]
Can you please try this?

1. Change some BCR settings again (like you did before)
2. Using a root file manager, grab the `.xml` files inside these folders and upload them here:
   * `/data/data/com.chiller3.bcr/shared_prefs/`
   * `/data/user_de/0/com.chiller3.bcr/shared_prefs/`

**Comment by TonyK922** [comment]
The .xml file only exists in /data/data/com.chiller3.bcr/shared_prefs/. 
here：
![Screenshot_2024-08-10-15-35-10-70_9e8df3d0c7c1f50248b6ee043a653d26](https://github.com/user-attachments/assets/83dfad2a-26fb-449e-9389-e870b903cf91)

![Screenshot_2024-08-10-15-33-35-66_9e8df3d0c7c1f50248b6ee043a653d26](https://github.com/user-attachments/assets/1cef0818-93f4-4d82-b76c-5b7fe9521bef)

/data/user_de/0/com.chiller3.bcr/shared_prefs/ no such path.
![Screenshot_2024-08-10-15-35-14-26_9e8df3d0c7c1f50248b6ee043a653d26](https://github.com/user-attachments/assets/59288242-316f-4514-8d0a-54838e644ce5)

**Comment by chenxiaolong** [comment]
Thanks. It looks like OnePlus might have a broken direct boot implementation. That would explain why BCR 1.65 works for you. BCR >=1.68 uses direct boot to record calls before the device is initially unlocked after a reboot.

Can you flash this test build and then take a screenshot of the debug info at the bottom? [BCR-1.69.r4.g8013736-release.zip](https://github.com/user-attachments/files/16570816/BCR-1.69.r4.g8013736-release.zip)

It should look something like this: [Screenshot_20240810-162021](https://github.com/user-attachments/assets/341fcfd0-8381-42c4-af2a-3550f66c2438)

**Comment by TonyK922** [comment]
Ahhhh no wonder.

![Screenshot_2024-08-11-06-02-30-86_88a63a93497fdafe6b6f2215ec875412](https://github.com/user-attachments/assets/9d0652ca-d84a-420d-87ba-817115fd9373)

**Comment by chenxiaolong** [comment]
Hmm, everything looks correct there and matches my device. I noticed that in your `.xml` file, it's missing:

```xml
    <boolean name="already_migrated" value="true" />
```

so maybe something is going wrong with the settings migration.

Please try this:

1. Flash this test build: [BCR-1.69.r6.gdb2bd80-release.zip](https://github.com/user-attachments/files/16571149/BCR-1.69.r6.gdb2bd80-release.zip)
2. Change some BCR settings
3. Reopen BCR to reproduce the problem
4. Reopen BCR one more time
5. Upload `/data/user_de/0/com.chiller3.bcr/files/migrate.log` and `preferences.log` here

---

Also, which other Magisk/KernelSU modules are installed?

**Comment by TonyK922** [comment]
I cannot open bcr app with after flashing this test build.
Modules I installed:
![Screenshot_2024-08-11-14-21-42-42_26ccd656f4ada08d09da6514b90ed2c0](https://github.com/user-attachments/assets/f5084f6b-1fa4-49c0-990b-fe60587788d9)
![Screenshot_2024-08-11-14-21-39-28_26ccd656f4ada08d09da6514b90ed2c0](https://github.com/user-attachments/assets/6bcd82ac-6683-4218-aa3a-b4c06566479a)
![Screenshot_2024-08-11-14-21-25-47_26ccd656f4ada08d09da6514b90ed2c0](https://github.com/user-attachments/assets/ca5527cf-9979-4cd7-91d0-d5dddeff8067)
![Screenshot_2024-08-11-14-21-20-73_26ccd656f4ada08d09da6514b90ed2c0](https://github.com/user-attachments/assets/a7526374-a1aa-4ced-8eb0-2d765a51edd3)

**Comment by TonyK922** [comment]
The only crash log is in /sdcard/Android/data/com.chiller3.bcr/files
[crash.log.txt](https://github.com/user-attachments/files/16580072/crash.log.txt)

**Comment by chenxiaolong** [comment]
Aha!
```
08-12 17:18:33.864 19759 19759 E AndroidRuntime: Caused by: java.io.FileNotFoundException: /data/user_de/0/com.chiller3.bcr/files/migrate.log: open failed: EACCES (Permission denied)
```

Android is not allowing BCR to write to its own `/data/user_de` folder.

Please try uninstalling BCR, manually deleting `/data/user_de/0/com.chiller3.bcr`, and then installing it again. If that doesn't work, I'll try installing all the Magisk modules you have on my device to see if one of them might be causing this.

**Comment by TonyK922** [comment]
Well... I presume 1.69 bcr affects the file system.
I cannot save apatch options with 1.69 installed. But everything is ok with 1.65.:)

**Comment by chenxiaolong** [comment]
Hmm, BCR doesn't modify any filesystem permissions or mount any files. I really have no idea how it could affect any other apps.

**Comment by TonyK922** [comment]
I have tried to reinstall bcr as you told me. But it still doesnt work. 
1.65 version works perfectly and is good enough to me.
