### ISSUE TITLE
Some recordings only contain my voice - the other side is not recorded

### ISSUE THREAD

**Issue by Lassie111** [chenxiaolong/BCR#587]
My device is Samsung Galaxy S21 FE.

Some of the calls are recorded flawlessly, but some others only contain my voice. I can't see any pattern when this is happening and when it is not. Here is a log created in debug mode from a call which was not recorded correctly:
[20240820_153111.346+0300_out.log.txt](https://github.com/user-attachments/files/16675872/20240820_153111.346%2B0300_out.log.txt)

And also the crash log:
[crash.log.txt](https://github.com/user-attachments/files/16675879/crash.log.txt)

**Comment by chenxiaolong** [comment]
Thanks for the logs!

This is not something that's fixable in BCR. Android itself is responsible for mixing the audio for both sides into a single audio stream. BCR just saves what it receives from Android into a file.

The crash is an unrelated issue that's already fixed in #578, which will be included in the upcoming 1.70 version.

**Comment by Lassie111** [comment]
> This is not something that's fixable in BCR. Android itself is responsible for mixing the audio for both sides into a single audio stream. BCR just saves what it receives from Android into a file.

Checking through my recordings directory, I notices that the problem appeared after updating from one UI 6.0 to 6.1.
Before the update almost all of the recordings are fine. After the update - almost all are not fine.
I don't think they are going to fix that in the future unfortunately.

**Comment by Lassie111** [comment]
> I can't see any pattern when this is happening and when it is not.

Found the pattern. Fails on all VoWiFi calls. Disabling it solves the problem.

**Comment by sourcevault** [comment]
> > I can't see any pattern when this is happening and when it is not.
> 
> Found the pattern. Fails on all VoWiFi calls. Disabling it solves the problem.

Exactly. I have Cube ACR also installed for recording VoWiFi calls and it had the option of recording regular calls, which I disabled and now BCR seems to be working fine !
