### ISSUE TITLE
VOIP call recordings

### ISSUE THREAD

**Issue by amandewett** [chenxiaolong/BCR#588]
Is there any chance that we will get WhatsApp (VOIP) call recording feature?

**Comment by chenxiaolong** [comment]
No, sorry. BCR is completely designed around Android's telephony framework, which only handles phone calls.

(Duplicate of #228, #235, #267, #340, #341, #355, #489, #490)

**Comment by amandewett** [comment]
> No, sorry. BCR is completely designed around Android's telephony framework, which only handles phone calls.
> 
> (Duplicate of #228, #235, #267, #340, #341, #355, #489, #490)

Ok, thank you :-(
