### ISSUE TITLE
BCR and OnePlus (OOS14)

### ISSUE THREAD

**Issue by clemenlg** [chenxiaolong/BCR#591]
Hello, 
After install BCR Magisk module and BCR app (from zip module) after reboot, following the installation steps, after reboot all preferences are wiped. 
Searching, I can't find the data files (XML) in /data/ path.
I saw some issues similar, but all have the BCR directories in the /data, and no in my device (following the steps for OnePlus devices).
BCR: v1.69
Magisk Canary: 27007
Android: 14
Kernel: 6.1.57
Regards

**Comment by chenxiaolong** [comment]
Do you have any other Magisk modules installed? If so, can you disable all of them except for BCR to see if that makes a difference?

As of BCR 1.68, the XML files are stored in `/data/user_de/0/com.chiller3.bcr`. This is to support recording calls before the device is initially unlocked during boot.

**Comment by clemenlg** [comment]
Hello, 
Other Magisk modules:
-Liboemcrypto disabler
-Play integrity fix
-Shamiko
-Zygisk - Lsposed
I tried deactivating Magisk modules and there wasn't any change (in every boot the user preferences was wiped).
In /data there wasn't BCR files.
After some changes reinstalling a couple of times the BCR APK from the zip file, finally user settings wasn't wiped (and I can find now the XML file).
Do you want to close the issue o do you want to do some verifications?
Regards

**Comment by chenxiaolong** [comment]
Thanks for testing. I really have no idea why that might be happening. If it happens again in the future, please feel free to reopen this issue.

And if it happens again, please run this command with adb and post the output:
```bash
adb shell ls -ldZ /data/user_de/0/com.chiller3.bcr /data/data/com.chiller3.bcr
```
