### ISSUE TITLE
low call volume after installing BCR 

### ISSUE THREAD

**Issue by abdoo507** [chenxiaolong/BCR#593]
hello. i've been using this app for a year now and i really love it !

my only issue is after installing it the call volume is reduced 

i can't hear the caller properly and if i'm in a noisy place i can't hear him at all

is there anything i can do to increase the volume ?

**Comment by chenxiaolong** [comment]
Glad you like BCR!

Just to make sure, you're saying the volume of the actual call is reduced, not in the recording? If so, that's pretty crazy--I've never seen that before. Unfortunately, there's nothing BCR can do to improve that.

Everything about the audio itself is controlled by Android. BCR only asks the system for a copy of the raw call audio stream. It doesn't touch the volume, mixer, or any other system settings.
