### ISSUE TITLE
BCR not working when using with bluetooth earphones

### ISSUE THREAD

**Issue by MysticMaestro** [chenxiaolong/BCR#595]
BCR works fine when using without bluetooth but faces an issue when using with earphones.
I am on a rooted device.

Any solution to this?
<img width="169" alt="Untitled" src="https://github.com/user-attachments/assets/92f1d8b2-7ba4-4c74-9d25-c5692e1ea174">

**Comment by chenxiaolong** [comment]
Unfortunately, your only option here is to try different ROMs. Android controls what audio gets sent to BCR.

Something based on the stock ROM tends to work better. If you're already using the stock ROM, then you're probably out of luck.

**Comment by MysticMaestro** [comment]
Yeah I was using a custom rom on a xiaomi device.
Will try to get the maintainer of the ROM to work on it.

Thanks
