### ISSUE TITLE
我的手机无法使用？

### ISSUE THREAD

**Issue by novoHJ** [chenxiaolong/BCR#599]
我的手机是红米turbo3，系统是澎湃OS1.0.15.0，使用magisk刷最近版本的包，成功了，但是重启以后打不开。是什么原因呢？不支持OS吗？

**Comment by chenxiaolong** [comment]
Hmm, can you grab a logcat with:

```
adb logcat -d > logcat.txt
```

right after it crashes and the upload that?

**Comment by novoHJ** [comment]
大神，我不知道如何提取log，但是我能使用了，我现在ZIP包里面找到APP安装，然后再用magisk刷包，这就是正确安装方式吧。使用的非常好，没有发现任何问题。有一个疑问，为什么非要打开通知才能使用，我就是想要悄悄使用不被人看见的，不过我打开通知，但是把通知里面的具体通知项目都关闭了，暂时使用BCR功能的时候没有提醒。挺好的。

**Comment by chenxiaolong** [comment]
Yep, if extracting the apk from the zip and installing it works, that's good. For disabling notifications, the best way is from Android's settings (like what you already did).
