### ISSUE TITLE
Not found in Fox's magisk module manager 

### ISSUE THREAD

**Issue by praveenpkallambalam** [chenxiaolong/BCR#60]
Is it possible to add this module to **fox's magisk module manager**'s repository?

It will help to expand the number of users for this module 

**Suggestion**

**Comment by chenxiaolong** [comment]
I think it's a good idea, but I cannot currently satisfy the rules for adding BCR to the repository. I posted some more details in another issue here: https://github.com/Magisk-Modules-Alt-Repo/submission/issues/94
