### ISSUE TITLE
Crashing 

### ISSUE THREAD

**Issue by msalah-kw** [chenxiaolong/BCR#601]
![crash.log (21).txt](https://github.com/user-attachments/files/16940451/crash.log.21.txt)

**Comment by chenxiaolong** [comment]
Do you have Shamiko installed or anything else that hides root? That's usually the cause of this crash. It happens when some system component of Android can't access BCR's apk.

You might be able to work around the problem by extracting the apk from BCR's module zip and installing it.

**Comment by msalah-kw** [comment]
Thank you for your support 
I've followed your instructions, and it's working properly now..
one last thing, can I use it for WhatsApp calls or messenger?

**Comment by chenxiaolong** [comment]
Glad you got it working! 

BCR only supports recording calls that are integrated with Android's telephony system, so basically only phone calls. WhatsApp calls and other VOIP apps are not supported.
