### ISSUE TITLE
Discard too short recordings

### ISSUE THREAD

**Issue by vk496** [chenxiaolong/BCR#604]
Hello again!

Im not sure if it was dicussed previously, so please close this issue if is duplicate.

A common thing when calling someone (that are not your contacts) is that a voicemail popups. Or small calls about "Im here" of 5s.

It would be really nice to have the ability to discard/remove the recordings that are less than X seconds. 

If there are any setup/init guide, I can try to do a PR myself, but I didn't touch Android in the past 10 years...

**Comment by chenxiaolong** [comment]
Please give the test build at https://github.com/chenxiaolong/BCR/pull/605#issuecomment-2362648389 a try.
