### ISSUE TITLE
REQUEST

### ISSUE THREAD

**Issue by paaavann** [chenxiaolong/BCR#618]
As I want to install this in my parents phone can you please add feature to listen recording from the app itself? Cuz its a bit advance method and they want it to be simple. So please consider this. My both parents are using BCR.

**Comment by chenxiaolong** [comment]
Sorry, I don't plan to add an audio player to BCR. You can check out some companion apps that other folks have made:

* https://github.com/nicorac/bcr-gui
* https://github.com/DHD2280/BCR-Manager

**Comment by paaavann** [comment]
thanks
