### ISSUE TITLE
Use without root

### ISSUE THREAD

**Issue by SalvatoreNoschese** [chenxiaolong/BCR#641]
Hi, I know is an already asked question 😅
Atm I've a P7P A15 with root just for his app (and revanced, but this can work also without root).

Yep, I know, BCR can work also without root (install via recovery) but I don't have a TWRP for pixel series.

So, just to be sure, is there any other way to use this app without root in a pixel device?

Shizuku, allow extra permission via adb?

Thank'u 😊

**Comment by chenxiaolong** [comment]
Sorry, this isn't possible with BCR. While root (as in Linux user ID 0) is not strictly required, system app permissions are. The only way to achieve that is by installing as a module in Magisk/KernelSU, flashing from recovery, or bundling BCR with the OS (eg. in a custom ROM).

Discussion about Shizuku can be found in #278 (there's no solution though).

**Comment by SalvatoreNoschese** [comment]
Ty, no probs.
Anyway, maybe u can consider to alloranalso record via mic (just like do ACR and similar app in play store).
Maybe this will be a valid solution 😊
