### ISSUE TITLE
Themed Icon Support

### ISSUE THREAD

**Issue by CodElixer** [chenxiaolong/BCR#78]
Hi Andrew!

It was really great for working together n helping to fix the Audio Overlapping Issue :)

As that major issue has been fixed, I would suggest you some minor enhancement for the app.

1. As currently the BCR doesn't support Themed Icon, You can look into this for future updates.
I've attached the screenshot, As you can see WhatsApp and other app icons are themed according to the System Theme.
![IMG_20220614_204017.jpg](https://user-images.githubusercontent.com/40817467/173620284-d407f3e7-346f-4eef-be09-d4e0eb80d20d.jpg)

2. For me the app hasn't permission for the contact and that's why it wasn't saving contacts name in the recordings. When I provided the permission manually then It was saving the Contacts name with recordings.
You can mention it in GitHub's Readme.md for manually providing Contacts Permission will record the contacts name in recordings or an option within the app that will specifically ask for the same.

Best Regards,
Yash

**Comment by chenxiaolong** [comment]
Hmm, I'm not sure what would cause that. BCR has supported themed icons since the first version. It's working for me with the default Pixel launcher: [Screenshot_20220614-133402](https://user-images.githubusercontent.com/646253/173641205-6313871c-79e4-4eb1-bc30-a549b34061e1.png) Does clearing the launcher's cache help at all?

> You can mention it in GitHub's Readme.md for manually providing Contacts Permission will record the contacts name in recordings or an option within the app that will specifically ask for the same.

👍 I'll add it to the README for sure and think about whether to add an option to the app.

**Comment by CodElixer** [comment]
> Hmm, I'm not sure what would cause that. BCR has supported themed icons since the first version. It's working for me with the default Pixel launcher: [Screenshot_20220614-133402](https://user-images.githubusercontent.com/646253/173641205-6313871c-79e4-4eb1-bc30-a549b34061e1.png) Does clearing the launcher's cache help at all?

Ohh! And I thought it doesn't support because it never themed from the first install. Strange!!
 
> EDIT: Maybe I can make it part of the initial permissions prompt (notifications required, microphone required, contacts optional).

Yeah, That'd be better 👍🏻

**Comment by CodElixer** [comment]
Tried clearing Cache of the Pixel Launcher but didn't helped either!
![Screenshot_20220614-233723_Settings.png](https://user-images.githubusercontent.com/40817467/173659518-4dcabe79-eb94-4867-a2e4-0e5a203210dd.png)![Screenshot_20220614-233808_Settings.png](https://user-images.githubusercontent.com/40817467/173659535-bd4d5186-d6eb-40ab-a10a-39b620a3e50d.png)

**Comment by chenxiaolong** [comment]
Oh, I just thought of something: is your ROM based on Android 12 or 13? Themed icon support was officially added to Android in 13, but some ROMs make it work for third party apps on 12 by bundling icons for popular apps into the ROM. I wonder if that's the case here.

**Comment by CodElixer** [comment]
> Oh, I just thought of something: is your ROM based on Android 12 or 13? Themed icon support was officially added to Android in 13, but some ROMs make it work for third party apps on 12 by bundling icons for popular apps into the ROM. I wonder if that's the case here.

Oops, It's Pixel Experience Plus based on Android 12L https://github.com/chenxiaolong/BCR/issues/39#issuecomment-1143070745.

**Comment by chenxiaolong** [comment]
I've added a section to the README about permissions and also added the contacts permission to the initial permissions prompt. That will be included in version 1.13.
