### ISSUE TITLE
Use In-Call Based Call Recording in BCR instead of MIC Based Recording

### ISSUE THREAD

**Issue by AdishSagarawat** [chenxiaolong/BCR#79]
Use In-Call Based Call Recording in BCR instead of MIC Based Recording as it is more clearer, accurate and sharp (Like in Lineage OS Dialer call Recording)

**Comment by AdishSagarawat** [comment]
Then , why is asks for MIC Permission?

**Comment by chenxiaolong** [comment]
That's just how Android presents the `RECORD_AUDIO` permission. It says microphone regardless of which audio stream is actually used for recording.

https://github.com/chenxiaolong/BCR/blob/a41589dbe17ccfd44016f1e7b111c1cd20183b01/app/src/main/AndroidManifest.xml#L18
