### ISSUE TITLE
Not working on OOS 12 OP8

### ISSUE THREAD

**Issue by idanny76** [chenxiaolong/BCR#8]
When I open the system app after installing it through Magisk.... All I get is a grey screen without any options. 

![Screenshot_2022-05-22-09-49-48-95_88a63a93497fdafe6b6f2215ec875412](https://user-images.githubusercontent.com/85074566/169698479-3fd44ebe-d01a-4238-b94f-fb736b2cdff2.jpg)
![Screenshot_2022-05-22-09-49-57-04_b783bf344239542886fee7b48fa4b892](https://user-images.githubusercontent.com/85074566/169698480-0e5caed1-c7bb-4d4c-8bbe-1931a4cda19f.jpg)
![Screenshot_2022-05-22-09-50-22-52_fc704e6b13c4fb26bf5e411f75da84f2](https://user-images.githubusercontent.com/85074566/169698484-1b323df0-6d8b-4207-b9bb-ac505e9edba4.jpg)

**Comment by chenxiaolong** [comment]
Hmm, could you grab a logcat?

I have no idea why that might be happening. BCR doesn't do anything on startup when opening the app.

**Comment by chenxiaolong** [comment]
Also, if you go to the Android Developer Options and enable `Show layout bounds`, do you at least see the boundaries in the gray screen? Eg. something like this:

![Screenshot_20220522-124202](https://user-images.githubusercontent.com/646253/169706226-31805d5c-86da-4343-82fd-496349166b60.png)

**Comment by idanny76** [comment]
Here is the screenshot and the logcat
![Screenshot_2022-05-22-16-34-57-30_b783bf344239542886fee7b48fa4b892](https://user-images.githubusercontent.com/85074566/169715019-e3be5987-8be0-489e-934d-693a698376f7.jpg)
![Screenshot_2022-05-22-16-34-44-19_88a63a93497fdafe6b6f2215ec875412](https://user-images.githubusercontent.com/85074566/169715020-425f2140-37dd-4268-8474-9cfbc72ee0ad.jpg)
[logcat_05-22-2022_16-40-03.txt](https://github.com/chenxiaolong/BCR/files/8750250/logcat_05-22-2022_16-40-03.txt)

**Comment by chenxiaolong** [comment]
I think the issue is in here:
```
 63425 [05-22 16:36:35.540 19059:19059 F/app_process64]
 63426 jni_internal.cc:748] JNI FatalError called: (com.chiller3.bcr) frameworks/base/core/jni/com_android_internal_os_Zygote.cpp:845: Failed to mount /data_mirror/data_de/null/0/com.chiller3.bcr to /data/user_de/0/com.chiller3.bcr: No such file or directory
```

It seems like after you try to open BCR, some oneplus-specific things run (OplusStartingWindowManager, OplusHansManager, OplusDisplayPolicy, etc.), and then Android fails to create BCR's app data directory. BCR never actually begins running.

I have no idea what would cause that. Do you have the latest version of Magisk installed? Any chance there are some other magisk modules (or LSPosed modules if you have that) that might be causing issues?

**Comment by idanny76** [comment]
> 

This what I have
![Screenshot_2022-05-22-18-58-47-43_785cfb1f0fb0c9a2030c9b38a1c3479a](https://user-images.githubusercontent.com/85074566/169719610-3ef7d963-3f6f-481f-99c5-a4864f6f97d6.jpg)
![Screenshot_2022-05-22-18-59-02-86_785cfb1f0fb0c9a2030c9b38a1c3479a](https://user-images.githubusercontent.com/85074566/169719611-a389cd5f-a469-4fd4-8b95-5e1772229144.jpg)
![Screenshot_2022-05-22-18-59-19-71_785cfb1f0fb0c9a2030c9b38a1c3479a](https://user-images.githubusercontent.com/85074566/169719614-1330524e-6c70-4d24-a2b9-f9740eada84a.jpg)
![Screenshot_2022-05-22-18-59-24-78_785cfb1f0fb0c9a2030c9b38a1c3479a](https://user-images.githubusercontent.com/85074566/169719615-7ab6fde3-90eb-4e59-992d-6412a646cbbc.jpg)

**Comment by idanny76** [comment]
I am using LSPosed with Hide my list to hide YouTube Vanced from the play store to keep it from updating.

**Comment by chenxiaolong** [comment]
> I am using LSPosed with Hide my list to hide YouTube Vanced from the play store to keep it from updating. Just updated LSPosed and BCR is still not loading. So you think LSPosed is the problem?

I don't think just having LSPosed is a problem, but having Hide My Applist enabled for `System Framework` might potentially be.

I'd suggest trying to temporarily disable both the `Hide My Applist` LSPosed module and also the `Enhance mode for HideMyApplist` Magisk module. If BCR works after that, then maybe try disabling `Hide My AppList` for `System Framework` only.

**Comment by idanny76** [comment]
I tried to just disable the System Framework and reboot first..... but now its stuck on the boot logo loading and it never loads.

**Comment by idanny76** [comment]
> Crap :( I just saw this on Hide My Applist's changelog: https://github.com/Dr-TSNG/Hide-My-Applist/releases
> 
> > If the Magisk module is enabled with the Xposed module disabled, it will cause bootloop
> 
> If you can boot into safe mode: https://www.verizon.com/support/knowledge-base-231289/, Magisk will not load any modules for that boot. That should hopefully give you a chance to disable Hide My Applist completely and prevent the hang.

The safe mode only works if you can boot into the OS. I was trying to boot into TWRP, but that is not working either. Is there a way to uninstall magisk through ADB commands?

**Comment by idanny76** [comment]
I found this to uninstall all magisk modules. https://didgeridoohan.com/magisk/Magisk#hn_Module_causing_issues_Magisk_functionality_bootloop_loss_of_root_etc

**Comment by idanny76** [comment]
The Magisk abd command did not work. Do you think if I flash the Stock boot img, that will prevent magisk from running the modules?

**Comment by idanny76** [comment]
is there a working TWRP for OOS12?

**Comment by idanny76** [comment]
If I switch from active Slot A to Slot B.... Will that allow me to then use the C.16 update? Will a factory reset delete the data in the internal storage?

**Comment by idanny76** [comment]
I was able to find the EU OOS 12 C.16 Full OTA and used to dirty flash the system and other partitions without deleting my data. When the Next Full OTA for global comes out, I will just overwrite the EU to Global. I will try the BCR now that I am in Stock and then will root and try it without LSPosed.

**Comment by idanny76** [comment]
It's working now, but I really need the hide my applist to block the play store from updating the YouTube app. Anyway to get both settings to work together. Maybe a setting on LSPosed or hide my applist? ![Screenshot_2022-05-23-18-23-14-08_88a63a93497fdafe6b6f2215ec875412](https://user-images.githubusercontent.com/85074566/169914540-9de2cb5d-09c7-462c-83d9-4e105cfe01e4.jpg)

**Comment by chenxiaolong** [comment]
> I was able to find the EU OOS 12 C.16 Full OTA and used to dirty flash the system and other partitions without deleting my data. When the Next Full OTA for global comes out, I will just overwrite the EU to Global. I will try the BCR now that I am in Stock and then will root and try it without LSPosed.

Glad to hear you got the boot issues fixed and that BCR is working!

> It's working now, but I really need the hide my applist to block the play store from updating the YouTube app. Anyway to get both settings to work together. Maybe a setting on LSPosed or hide my applist?

Is it sufficient to uncheck auto updates for YouTube from within the Play Store? I've never tried blocking updates for a specific app, so I'm not sure if there's another way to do it.

![Screenshot_20220523-195735](https://user-images.githubusercontent.com/646253/169922620-bb9bd7cf-8ec5-451c-b44f-2680acb6d49c.png)

**Comment by idanny76** [comment]
I tried to disable the YouTube auto update from within the play store..... But after a couple of days or less it forces the update. The hide my applist has been the only permanent solution.

**Comment by idanny76** [comment]
What is the hide my applist doing that is interfering with BCR? HMA is just blocking the play store from finding the YouTube app as being installed.

**Comment by chenxiaolong** [comment]
Ah, I see. I don't know of any other workaround then :(

> What is the hide my applist doing that is interfering with BCR?

I don't think it conflicts with BCR specifically, but rather any new system app that gets added via Magisk. I don't know enough about HMA or why it might be breaking things though.

**Comment by HepoH3** [comment]
> When I open the system app after installing it through Magisk.... All I get is a grey screen without any options.

Same thing on 1+9pro (OOS 12) without HMA:
![photo_2022-05-25_14-31-04](https://user-images.githubusercontent.com/17159587/170252389-db7d87f9-3ed4-438f-8d7a-eb9ed6fa1251.jpg)

**Comment by emolenaar** [comment]
I have the same problem with OOS 12 on my OnePlus 8 Pro. However I did find something interesting. Oxygen OS has a feature that allow the user to 'clone' certain apps like Telegram and WhatsApp which allows them to have two instances running at the same time with a different account.

These cloned apps show up under 'work profiles', and it turns out that after installing BCR with Magisk, the BCR app icon appears under both normal and work mode. When I open the BCR app under normal mode it just shows a white screen, but when I open it under work mode (which is the cloned app, even tho I didn't clone it myself) the app opens.

Here is a screenshot: 
![Screenshot_2022-05-26-12-58-17-75_88a63a93497fdafe6b6f2215ec875412](https://user-images.githubusercontent.com/19408580/170569499-384a8845-76aa-4961-8358-aa3bc794bfde.jpg)
![Screenshot_2022-05-26-12-58-10-59_fc704e6b13c4fb26bf5e411f75da84f2](https://user-images.githubusercontent.com/19408580/170569527-3e5ae132-1520-414e-a185-df87faf4b447.jpg)

Maybe the module tries to load the app under the emulated 999 storage instead of 0?

**Comment by chenxiaolong** [comment]
That's an interesting find.

Currently, the magisk module only creates the following 2 files. It doesn't run any scripts or try to do anything else.
* `/system/etc/permissions/privapp-permissions-com.chiller3.bcr.xml`
* `/system/priv-app/com.chiller3.bcr/app-release.apk`

I'm not really sure what could possibly conflict with that OnePlus feature.

**Comment by idanny76** [comment]
> > I tried to disable the YouTube auto update from within the play store..... But after a couple of days or less it forces the update. The hide my applist has been the only permanent solution.
> 
> ![Screenshot_20220527-104738_Shell](https://user-images.githubusercontent.com/87088283/170634411-e4fdbcb5-7d17-441c-9e0a-604bfff09038.png) Use Update Locker Lsposed module , works like a charm for YouTube and YouTube Music , no need to use HMA

Thank you very much. Will give it a try today.
