### ISSUE TITLE
Must Needed Feature : For Privacy add an option to automatically Delete Call Recording after Certain Period 

### ISSUE THREAD

**Issue by AdishSagarawat** [chenxiaolong/BCR#81]
We want privacy in call recordings and also want to save our space.

**Comment by AdishSagarawat** [comment]
May I know the reason please?

**Comment by chenxiaolong** [comment]
I wrote a little bit about it in the README: https://github.com/chenxiaolong/BCR#non-features I intend to keep BCR as simple as possible to make it easier to maintain the project.

If you're interested in another open source call recorder app that has more features, I'd recommend taking a look at https://gitlab.com/axet/android-call-recorder
