### ISSUE TITLE
Problems with bluetooth

### ISSUE THREAD

**Issue by Ioivi** [chenxiaolong/BCR#89]
BCR works great but I have a problem with bluetooth connections. I am using it on Motorola edge pro + magisk. Connected with bluetooth headphones but even more frequently with the bluetooth of the car, after 30/60 seconds the interlocutor no longer hears my voice while I hear well and BCR records everything perfectly both voices. Is there a solution?

**Comment by chenxiaolong** [comment]
I suspect this is a firmware issue unfortunately. BCR doesn't interact with the actual call besides asking Android for access to the `VOICE_CALL` audio stream.

Do you experience the same problem with other call recorders?

**Comment by Ioivi** [comment]
> Do you experience the same problem with other call recorders?

I have previously used another call recorder on a Samsung S8 which worked perfectly fine. 

That software, which asks to specify the processor, on the Motorola edge 30 pro, gives the same type of error that I reported to you but the Snapdragon 8 gen 1 was not available as an option. 

For this reason I tried your call recorder. I find your software very good but I need to fix the Bluetooth problem. Among other things, with bluetooth headphones (Soundpeats true air 2 bt 5.2) it rarely gives problems, while in the car (Audi A6 2018, therefore not of the latest generation) this problem occurs very frequently, so I deduce it is also a problem of generation of bluetooth. Initially I saw that HD calling seems to be less of a problem.

**Comment by chenxiaolong** [comment]
Thanks for the reply. Since the issue happens with other call recorders too, I suspect this is an issue in the ROM and/or the modem firmware. I'm not familiar with the lower level details of the bluetooth stack though, so I don't really have any suggestions for how to further troubleshoot this.
