### ISSUE TITLE
Ability to record calls by contact. 

### ISSUE THREAD

**Issue by Dr-Ari-Gami** [chenxiaolong/BCR#93]
I know, I know, KISS. An issue I have, however, is that I don't want to record all of my calls. I really only want to record calls from unknown numbers and from a few contacts. 

I already checked the non-features list, and this isn't in it. 

Apologies if this isn't the right place to request a feature.

**Comment by chenxiaolong** [comment]
Hmm, I'd suggest looking into Tasker or something similar to delete unwanted recordings as a workaround.

This would be quite nontrivial to implement with BCR's current design, so I probably won't be adding this feature. On some devices, the Android API that BCR uses doesn't even provide provide the contact information until well after the recording already started.

**Comment by Dr-Ari-Gami** [comment]
Thanks for the quick response! 

That's unfortunate, but makes sense. My issue is that recording the calls in the background all the time kills my battery faster than I'd like. 

Is it possible to add a way to start a recording mid-call? That way if needed I can start a recording, but it won't always be recording in the background?

**Comment by chenxiaolong** [comment]
> Is it possible to add a way to start a recording mid-call? That way if needed I can start a recording, but it won't always be recording in the background?

I'll think about it, but this might be a bit difficult with BCR's current design as well.

If you're willing to sacrifice a bit of space with larger files, picking the WAV output format + 8000Hz sample rate might help for your use case. WAV output does not require encoding, so BCR's CPU usage should drop from ~25% to <1%. That should help quite a bit with battery drain during recording.

**Comment by lbdroid** [comment]
> Is it possible to add a way to start a recording mid-call? That way if needed I can start a recording, but it won't always be recording in the background?

This is best implemented within the dialer itself. Some dialers do have this capability, including google dialer (location dependent), and soon also GrapheneOS dialer (https://github.com/GrapheneOS/platform_packages_apps_Dialer/pull/12)

**Comment by Dr-Ari-Gami** [comment]
> > Is it possible to add a way to start a recording mid-call? That way if needed I can start a recording, but it won't always be recording in the background?
> 
> I'll think about it, but this might be a bit difficult with BCR's current design as well.
> 
> If you're willing to sacrifice a bit of space with larger files, picking the WAV output format + 8000Hz sample rate might help for your use case. WAV output does not require encoding, so BCR's CPU usage should drop from ~25% to <1%. That should help quite a bit with battery drain during recording.

Okie! Done, it uses much less cpu now. Thanks!

**Comment by chenxiaolong** [comment]
Similar situation there too :( BCR's current design doesn't work well for accepting intents (actions from other apps, like Tasker).

**Comment by chenxiaolong** [comment]
This has been implemented in #327 and will be included in the upcoming 1.42 release.
